/* C code for program kohzuCtl_soft, generated by snc from ../kohzuCtl_soft.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 93 "../kohzuCtl_soft.st"
static const EF_ID H_mon = 1;
# line 99 "../kohzuCtl_soft.st"
static const EF_ID K_mon = 2;
# line 105 "../kohzuCtl_soft.st"
static const EF_ID L_mon = 3;
# line 111 "../kohzuCtl_soft.st"
static const EF_ID A_mon = 4;
# line 121 "../kohzuCtl_soft.st"
static const EF_ID E_mon = 5;
# line 136 "../kohzuCtl_soft.st"
static const EF_ID lambda_mon = 6;
# line 151 "../kohzuCtl_soft.st"
static const EF_ID theta_mon = 7;
# line 232 "../kohzuCtl_soft.st"
static const EF_ID thetaDmov_mon = 8;
# line 238 "../kohzuCtl_soft.st"
static const EF_ID yDmov_mon = 9;
# line 244 "../kohzuCtl_soft.st"
static const EF_ID zDmov_mon = 10;
# line 257 "../kohzuCtl_soft.st"
short kohzuCtl_soft_LS_TEST = 0;
# line 303 "../kohzuCtl_soft.st"
static const EF_ID thetaMotHiLim_mon = 11;
# line 309 "../kohzuCtl_soft.st"
static const EF_ID thetaMotLoLim_mon = 12;
# line 340 "../kohzuCtl_soft.st"
static const EF_ID thetaMotCmdMon_mon = 13;
# line 346 "../kohzuCtl_soft.st"
static const EF_ID yMotCmdMon_mon = 14;
# line 352 "../kohzuCtl_soft.st"
static const EF_ID zMotCmdMon_mon = 15;
# line 361 "../kohzuCtl_soft.st"
static const EF_ID thetaMotVel_mon = 16;
# line 370 "../kohzuCtl_soft.st"
static const EF_ID yMotVel_mon = 17;
# line 379 "../kohzuCtl_soft.st"
static const EF_ID zMotVel_mon = 18;
# line 385 "../kohzuCtl_soft.st"
static const EF_ID thetaMotRdbk_mon = 19;
# line 387 "../kohzuCtl_soft.st"
static const EF_ID thetaMotRdbkPseudo_mon = 20;
# line 392 "../kohzuCtl_soft.st"
static const EF_ID yMotRdbk_mon = 21;
# line 398 "../kohzuCtl_soft.st"
static const EF_ID zMotRdbk_mon = 22;
# line 405 "../kohzuCtl_soft.st"
static const EF_ID useSetMode_mon = 23;
# line 411 "../kohzuCtl_soft.st"
static const EF_ID thetaMotSet_mon = 24;
# line 417 "../kohzuCtl_soft.st"
static const EF_ID yMotSet_mon = 25;
# line 423 "../kohzuCtl_soft.st"
static const EF_ID zMotSet_mon = 26;
# line 430 "../kohzuCtl_soft.st"
static const EF_ID yOffset_mon = 27;
# line 439 "../kohzuCtl_soft.st"
#include <string.h>
# line 440 "../kohzuCtl_soft.st"
#include <math.h>
# line 442 "../kohzuCtl_soft.st"
double kohzuCtl_soft_calc2dSpacing();
# line 443 "../kohzuCtl_soft.st"
char *kohzuCtl_soft_pmacP;
# line 444 "../kohzuCtl_soft.st"
char *kohzuCtl_soft_pmacM;
# line 445 "../kohzuCtl_soft.st"
char *kohzuCtl_soft_pmacGEOM;

/* Variable declarations */
# line 45 "../kohzuCtl_soft.st"
static	short kohzuCtlDebug;
# line 49 "../kohzuCtl_soft.st"
static	string seqMsg1;
# line 52 "../kohzuCtl_soft.st"
static	string seqMsg2;
# line 55 "../kohzuCtl_soft.st"
static	short opAlert;
# line 58 "../kohzuCtl_soft.st"
static	short opAck;
# line 66 "../kohzuCtl_soft.st"
static	short putVals;
# line 74 "../kohzuCtl_soft.st"
static	short autoMode;
# line 79 "../kohzuCtl_soft.st"
static	short ccMode;
# line 83 "../kohzuCtl_soft.st"
static	short kohzuMoving;
# line 87 "../kohzuCtl_soft.st"
static	short kohzuDone;
# line 90 "../kohzuCtl_soft.st"
static	double H;
# line 96 "../kohzuCtl_soft.st"
static	double K;
# line 102 "../kohzuCtl_soft.st"
static	double L;
# line 108 "../kohzuCtl_soft.st"
static	double A;
# line 114 "../kohzuCtl_soft.st"
static	double D;
# line 118 "../kohzuCtl_soft.st"
static	double E;
# line 124 "../kohzuCtl_soft.st"
static	double EHi;
# line 127 "../kohzuCtl_soft.st"
static	double ELo;
# line 130 "../kohzuCtl_soft.st"
static	double ERdbk;
# line 133 "../kohzuCtl_soft.st"
static	double lambda;
# line 139 "../kohzuCtl_soft.st"
static	double lambdaHi;
# line 142 "../kohzuCtl_soft.st"
static	double lambdaLo;
# line 145 "../kohzuCtl_soft.st"
static	double lambdaRdbk;
# line 148 "../kohzuCtl_soft.st"
static	double theta;
# line 154 "../kohzuCtl_soft.st"
static	double thetaHi;
# line 157 "../kohzuCtl_soft.st"
static	double thetaLo;
# line 160 "../kohzuCtl_soft.st"
static	double thetaRdbk;
# line 169 "../kohzuCtl_soft.st"
static	string thetaMotName;
# line 172 "../kohzuCtl_soft.st"
static	string yMotName;
# line 175 "../kohzuCtl_soft.st"
static	string zMotName;
# line 178 "../kohzuCtl_soft.st"
static	double thetaMotCmdEcho;
# line 181 "../kohzuCtl_soft.st"
static	double yMotCmdEcho;
# line 184 "../kohzuCtl_soft.st"
static	double zMotCmdEcho;
# line 187 "../kohzuCtl_soft.st"
static	double thetaMotRdbkEcho;
# line 190 "../kohzuCtl_soft.st"
static	double yMotRdbkEcho;
# line 193 "../kohzuCtl_soft.st"
static	double zMotRdbkEcho;
# line 196 "../kohzuCtl_soft.st"
static	double thetaMotVelEcho;
# line 199 "../kohzuCtl_soft.st"
static	double yMotVelEcho;
# line 202 "../kohzuCtl_soft.st"
static	double zMotVelEcho;
# line 205 "../kohzuCtl_soft.st"
static	short thetaDmovEcho;
# line 208 "../kohzuCtl_soft.st"
static	short yDmovEcho;
# line 211 "../kohzuCtl_soft.st"
static	short zDmovEcho;
# line 220 "../kohzuCtl_soft.st"
static	short thetaMotStop;
# line 223 "../kohzuCtl_soft.st"
static	short yStop;
# line 226 "../kohzuCtl_soft.st"
static	short zStop;
# line 229 "../kohzuCtl_soft.st"
static	short thetaDmov;
# line 235 "../kohzuCtl_soft.st"
static	short yDmov;
# line 241 "../kohzuCtl_soft.st"
static	short zDmov;
# line 248 "../kohzuCtl_soft.st"
static	short thetaHls;
# line 249 "../kohzuCtl_soft.st"
static	short thetaLls;
# line 250 "../kohzuCtl_soft.st"
static	short yHls;
# line 251 "../kohzuCtl_soft.st"
static	short yLls;
# line 252 "../kohzuCtl_soft.st"
static	short zHls;
# line 253 "../kohzuCtl_soft.st"
static	short zLls;
# line 284 "../kohzuCtl_soft.st"
static	double thetaMotDesired;
# line 288 "../kohzuCtl_soft.st"
static	double yMotDesired;
# line 291 "../kohzuCtl_soft.st"
static	double yMotDesiredHi;
# line 293 "../kohzuCtl_soft.st"
static	double yMotDesiredLo;
# line 296 "../kohzuCtl_soft.st"
static	double zMotDesired;
# line 300 "../kohzuCtl_soft.st"
static	double thetaMotHiLim;
# line 306 "../kohzuCtl_soft.st"
static	double thetaMotLoLim;
# line 312 "../kohzuCtl_soft.st"
static	double yMotHiLim;
# line 316 "../kohzuCtl_soft.st"
static	double yMotLoLim;
# line 320 "../kohzuCtl_soft.st"
static	double zMotHiLim;
# line 324 "../kohzuCtl_soft.st"
static	double zMotLoLim;
# line 328 "../kohzuCtl_soft.st"
static	double thetaMotCmd;
# line 331 "../kohzuCtl_soft.st"
static	double yMotCmd;
# line 334 "../kohzuCtl_soft.st"
static	double zMotCmd;
# line 337 "../kohzuCtl_soft.st"
static	double thetaMotCmdMon;
# line 343 "../kohzuCtl_soft.st"
static	double yMotCmdMon;
# line 349 "../kohzuCtl_soft.st"
static	double zMotCmdMon;
# line 355 "../kohzuCtl_soft.st"
static	double thTime;
# line 356 "../kohzuCtl_soft.st"
static	double oldThSpeed;
# line 357 "../kohzuCtl_soft.st"
static	double newThSpeed;
# line 358 "../kohzuCtl_soft.st"
static	double thSpeed;
# line 364 "../kohzuCtl_soft.st"
static	double yTime;
# line 365 "../kohzuCtl_soft.st"
static	double oldYSpeed;
# line 366 "../kohzuCtl_soft.st"
static	double newYSpeed;
# line 367 "../kohzuCtl_soft.st"
static	double ySpeed;
# line 373 "../kohzuCtl_soft.st"
static	double zTime;
# line 374 "../kohzuCtl_soft.st"
static	double oldZSpeed;
# line 375 "../kohzuCtl_soft.st"
static	double newZSpeed;
# line 376 "../kohzuCtl_soft.st"
static	double zSpeed;
# line 382 "../kohzuCtl_soft.st"
static	double thetaMotRdbk;
# line 389 "../kohzuCtl_soft.st"
static	double yMotRdbk;
# line 395 "../kohzuCtl_soft.st"
static	double zMotRdbk;
# line 402 "../kohzuCtl_soft.st"
static	short useSetMode;
# line 408 "../kohzuCtl_soft.st"
static	short thetaMotSet;
# line 414 "../kohzuCtl_soft.st"
static	short yMotSet;
# line 420 "../kohzuCtl_soft.st"
static	short zMotSet;
# line 427 "../kohzuCtl_soft.st"
static	double yOffset;
# line 433 "../kohzuCtl_soft.st"
static	double yOffsetHi;
# line 436 "../kohzuCtl_soft.st"
static	double yOffsetLo;
# line 446 "../kohzuCtl_soft.st"
static	short geom;
# line 448 "../kohzuCtl_soft.st"
static	short causedMove;
# line 449 "../kohzuCtl_soft.st"
static	short initSeq;
# line 450 "../kohzuCtl_soft.st"
static	short initSeqDone;
# line 451 "../kohzuCtl_soft.st"
static	float avg;
# line 452 "../kohzuCtl_soft.st"
static	int nint;
# line 453 "../kohzuCtl_soft.st"
static	double hc;
# line 454 "../kohzuCtl_soft.st"
static	double radConv;
# line 456 "../kohzuCtl_soft.st"
static	int riskAverse;
# line 457 "../kohzuCtl_soft.st"
static	double prev_E;
# line 458 "../kohzuCtl_soft.st"
static	double prev_theta;
# line 459 "../kohzuCtl_soft.st"
static	double prev_lambda;
# line 460 "../kohzuCtl_soft.st"
static	double prev_thetaMotDesired;
# line 461 "../kohzuCtl_soft.st"
static	double prev_yMotDesired;
# line 462 "../kohzuCtl_soft.st"
static	double prev_zMotDesired;
# line 463 "../kohzuCtl_soft.st"
static	int willViolateLimit;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "kohzuCtl_soft" ******/

/* Event function for state "init" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 468 "../kohzuCtl_soft.st"
			initSeq = 0;
# line 469 "../kohzuCtl_soft.st"
			riskAverse = 0;
		}
		return;
	}
}

/****** Code for state "initSequence" in state set "kohzuCtl_soft" ******/

/* Event function for state "initSequence" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_initSequence(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 474 "../kohzuCtl_soft.st"
	if (initSeq == 0)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 537 "../kohzuCtl_soft.st"
	if (initSeq == 1)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 542 "../kohzuCtl_soft.st"
	if (initSeq == 2)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 547 "../kohzuCtl_soft.st"
	if ((initSeq == 3) && seq_delay(seqg_env, 1.))
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 3;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "initSequence" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_initSequence(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 475 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:initSequence:initSeq=0\n");
# line 476 "../kohzuCtl_soft.st"
			hc = 12.3984244;
# line 477 "../kohzuCtl_soft.st"
			radConv = 57.2958;
# line 478 "../kohzuCtl_soft.st"
			thetaMotStop = 1;
# line 479 "../kohzuCtl_soft.st"
			yStop = 1;
# line 480 "../kohzuCtl_soft.st"
			zStop = 1;
# line 481 "../kohzuCtl_soft.st"
			putVals = 0;
# line 482 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 5/*putVals*/, DEFAULT, DEFAULT_TIMEOUT);
# line 483 "../kohzuCtl_soft.st"
			autoMode = 0;
# line 484 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 485 "../kohzuCtl_soft.st"
			opAck = 0;
# line 486 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 4/*opAck*/, DEFAULT, DEFAULT_TIMEOUT);
			
  kohzuCtl_soft_pmacP = seq_macValueGet(ssId,"P");
  kohzuCtl_soft_pmacM = seq_macValueGet(ssId,"M_THETA");
  if (kohzuCtl_soft_pmacP == 0 || kohzuCtl_soft_pmacM == 0) {
   sprintf(thetaMotName,"??????");
  } else {
   strcpy(thetaMotName, kohzuCtl_soft_pmacP);
   strcat(thetaMotName, kohzuCtl_soft_pmacM);
  }
  kohzuCtl_soft_pmacM = seq_macValueGet(ssId,"M_Y");
  if (kohzuCtl_soft_pmacP == 0 || kohzuCtl_soft_pmacM == 0) {
   sprintf(yMotName,"??????");
  } else {
   strcpy(yMotName, kohzuCtl_soft_pmacP);
   strcat(yMotName, kohzuCtl_soft_pmacM);
  }
  kohzuCtl_soft_pmacM = seq_macValueGet(ssId,"M_Z");
  if (kohzuCtl_soft_pmacP == 0 || kohzuCtl_soft_pmacM == 0) {
   sprintf(zMotName,"??????");
  } else {
   strcpy(zMotName, kohzuCtl_soft_pmacP);
   strcat(zMotName, kohzuCtl_soft_pmacM);
  }
  kohzuCtl_soft_pmacGEOM = seq_macValueGet(ssId,"GEOM");
  geom = 1;
  if (*kohzuCtl_soft_pmacGEOM == '2') geom = 2;

# line 514 "../kohzuCtl_soft.st"
			if (geom == 1)
			{
# line 515 "../kohzuCtl_soft.st"
				yOffsetHi = 17.5 + .000001;
# line 516 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 81/*yOffsetHi*/, DEFAULT, DEFAULT_TIMEOUT);
# line 517 "../kohzuCtl_soft.st"
				yOffsetLo = 17.5 - .000001;
# line 518 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 82/*yOffsetLo*/, DEFAULT, DEFAULT_TIMEOUT);
# line 519 "../kohzuCtl_soft.st"
				yOffset = 17.5;
# line 520 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 80/*yOffset*/, DEFAULT, DEFAULT_TIMEOUT);
# line 521 "../kohzuCtl_soft.st"
				yMotDesiredHi = 0.;
# line 522 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 55/*yMotDesiredHi*/, DEFAULT, DEFAULT_TIMEOUT);
# line 523 "../kohzuCtl_soft.st"
				yMotDesiredLo = -35;
# line 524 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 56/*yMotDesiredLo*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			else
			{
# line 526 "../kohzuCtl_soft.st"
				yMotDesiredHi = 60.;
# line 527 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 55/*yMotDesiredHi*/, DEFAULT, DEFAULT_TIMEOUT);
# line 528 "../kohzuCtl_soft.st"
				yMotDesiredLo = 0.;
# line 529 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 56/*yMotDesiredLo*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 531 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 26/*thetaMotName*/, DEFAULT, DEFAULT_TIMEOUT);
# line 532 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 27/*yMotName*/, DEFAULT, DEFAULT_TIMEOUT);
# line 533 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 28/*zMotName*/, DEFAULT, DEFAULT_TIMEOUT);
# line 534 "../kohzuCtl_soft.st"
			initSeq = 1;
		}
		return;
	case 1:
		{
# line 538 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:initSequence:initSeq=1\n");
# line 539 "../kohzuCtl_soft.st"
			initSeq = 2;
		}
		return;
	case 2:
		{
# line 543 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:initSequence:initSeq=2\n");
# line 544 "../kohzuCtl_soft.st"
			initSeq = 3;
		}
		return;
	case 3:
		{
# line 548 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:initSequence:initSeq=3\n");
# line 549 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "Kohzu Control Ready");
# line 550 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 551 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, " ");
# line 552 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 553 "../kohzuCtl_soft.st"
			initSeqDone = 1;
# line 554 "../kohzuCtl_soft.st"
			theta = thetaMotRdbk;
# line 555 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 22/*theta*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "waitForCmndEnter" in state set "kohzuCtl_soft" ******/

/* Event function for state "waitForCmndEnter" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_waitForCmndEnter(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 560 "../kohzuCtl_soft.st"
	if (initSeqDone && seq_delay(seqg_env, .1))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 620 "../kohzuCtl_soft.st"
	if (!initSeqDone)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waitForCmndEnter" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_waitForCmndEnter(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 561 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmndEnter:initSeqDone\n");
# line 562 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, H_mon);
# line 563 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, K_mon);
# line 564 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, L_mon);
# line 565 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, A_mon);
# line 566 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, E_mon);
# line 567 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, lambda_mon);
# line 568 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, theta_mon);
# line 570 "../kohzuCtl_soft.st"
			thetaMotRdbkEcho = thetaMotRdbk;
# line 571 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 32/*thetaMotRdbkEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 572 "../kohzuCtl_soft.st"
			yMotRdbkEcho = yMotRdbk;
# line 573 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 33/*yMotRdbkEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 574 "../kohzuCtl_soft.st"
			zMotRdbkEcho = zMotRdbk;
# line 575 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 34/*zMotRdbkEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 576 "../kohzuCtl_soft.st"
			thetaMotVelEcho = thSpeed;
# line 577 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 35/*thetaMotVelEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 578 "../kohzuCtl_soft.st"
			yMotVelEcho = ySpeed;
# line 579 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 36/*yMotVelEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 580 "../kohzuCtl_soft.st"
			zMotVelEcho = zSpeed;
# line 581 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 37/*zMotVelEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 582 "../kohzuCtl_soft.st"
			thetaMotCmdEcho = thetaMotCmdMon;
# line 583 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 29/*thetaMotCmdEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 584 "../kohzuCtl_soft.st"
			yMotCmdEcho = yMotCmdMon;
# line 585 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 30/*yMotCmdEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 586 "../kohzuCtl_soft.st"
			zMotCmdEcho = zMotCmdMon;
# line 587 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 31/*zMotCmdEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 588 "../kohzuCtl_soft.st"
			thetaDmovEcho = thetaDmov;
# line 589 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 38/*thetaDmovEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 590 "../kohzuCtl_soft.st"
			yDmovEcho = yDmov;
# line 591 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 39/*yDmovEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 592 "../kohzuCtl_soft.st"
			zDmovEcho = zDmov;
# line 593 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 40/*zDmovEcho*/, DEFAULT, DEFAULT_TIMEOUT);
# line 594 "../kohzuCtl_soft.st"
			if (autoMode || useSetMode)
			{
# line 595 "../kohzuCtl_soft.st"
				thetaRdbk = thetaMotRdbk;
# line 596 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 25/*thetaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 597 "../kohzuCtl_soft.st"
				lambdaRdbk = D * sin(thetaRdbk / radConv);
# line 598 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 21/*lambdaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 599 "../kohzuCtl_soft.st"
				ERdbk = hc / lambdaRdbk;
# line 600 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 17/*ERdbk*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 602 "../kohzuCtl_soft.st"
			opAck = 0;
# line 603 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 4/*opAck*/, DEFAULT, DEFAULT_TIMEOUT);
# line 604 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmndEnter: kohzuMoving=%d; kohzuDone=%d\n", kohzuMoving, kohzuDone);
# line 605 "../kohzuCtl_soft.st"
			if (kohzuMoving && kohzuDone)
			{
# line 606 "../kohzuCtl_soft.st"
				if (kohzuCtlDebug)
					printf("kohzuCtl:waitForCmndEnter: asserting 'done'.\n");
# line 607 "../kohzuCtl_soft.st"
				kohzuMoving = 0;
# line 607 "../kohzuCtl_soft.st"
				kohzuDone = 0;
# line 608 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 8/*kohzuMoving*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 611 "../kohzuCtl_soft.st"
			prev_theta = theta;
# line 612 "../kohzuCtl_soft.st"
			prev_E = E;
# line 613 "../kohzuCtl_soft.st"
			prev_lambda = lambda;
# line 614 "../kohzuCtl_soft.st"
			prev_thetaMotDesired = thetaMotDesired;
# line 615 "../kohzuCtl_soft.st"
			prev_yMotDesired = yMotDesired;
# line 616 "../kohzuCtl_soft.st"
			prev_zMotDesired = zMotDesired;
# line 617 "../kohzuCtl_soft.st"
			willViolateLimit = 0;
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "waitForCmnd" in state set "kohzuCtl_soft" ******/

/* Event function for state "waitForCmnd" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_waitForCmnd(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 625 "../kohzuCtl_soft.st"
	if (seq_efTest(seqg_env, H_mon) || seq_efTest(seqg_env, K_mon) || seq_efTest(seqg_env, L_mon) || seq_efTest(seqg_env, A_mon))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 637 "../kohzuCtl_soft.st"
	if (seq_efTest(seqg_env, thetaMotHiLim_mon) || seq_efTest(seqg_env, thetaMotLoLim_mon))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 647 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, thetaMotRdbk_mon))
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 652 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, E_mon))
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 656 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, lambda_mon))
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 660 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, theta_mon))
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 5;
		return TRUE;
	}
# line 664 "../kohzuCtl_soft.st"
	if (putVals && seq_delay(seqg_env, .1))
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 6;
		return TRUE;
	}
# line 668 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, yOffset_mon))
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 7;
		return TRUE;
	}
# line 678 "../kohzuCtl_soft.st"
	if (opAck)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 8;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waitForCmnd" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_waitForCmnd(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 626 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmnd:HKLA_mon\n");
# line 627 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "Lattice Spacing Changed");
# line 628 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 629 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, " ");
# line 630 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 631 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, H_mon);
# line 632 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, K_mon);
# line 633 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, L_mon);
# line 634 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, A_mon);
		}
		return;
	case 1:
		{
# line 638 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmnd:thetaMotXxLim_mon\n");
# line 639 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "Theta Motor Soft Limits Changed");
# line 640 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 641 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, " ");
# line 642 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 643 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, thetaMotHiLim_mon);
# line 644 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, thetaMotLoLim_mon);
		}
		return;
	case 2:
		{
# line 648 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmnd:thetaMotRdbk_mon\n");
# line 649 "../kohzuCtl_soft.st"
			seq_efSet(seqg_env, thetaMotRdbkPseudo_mon);
		}
		return;
	case 3:
		{
# line 653 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmnd:E_mon\n");
		}
		return;
	case 4:
		{
# line 657 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmnd:lambda_mon\n");
		}
		return;
	case 5:
		{
# line 661 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmnd:theta_mon\n");
		}
		return;
	case 6:
		{
# line 665 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmnd:putVals\n");
		}
		return;
	case 7:
		{
# line 669 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmnd:yOffset_mon\n");
# line 670 "../kohzuCtl_soft.st"
			autoMode = 0;
# line 671 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 672 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "y offset changed to %f", yOffset);
# line 673 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 674 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, "Set to Manual Mode");
# line 675 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 8:
		{
# line 679 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:waitForCmnd:opAck\n");
# line 680 "../kohzuCtl_soft.st"
			opAlert = 0;
# line 681 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 682 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, " ");
# line 683 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 684 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, " ");
# line 685 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "dInputChanged" in state set "kohzuCtl_soft" ******/

/* Event function for state "dInputChanged" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_dInputChanged(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "dInputChanged" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_dInputChanged(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 691 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:dInputChanged\n");
# line 692 "../kohzuCtl_soft.st"
			autoMode = 0;
# line 693 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 694 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, "Set to Manual Mode");
# line 695 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 696 "../kohzuCtl_soft.st"
			D = kohzuCtl_soft_calc2dSpacing();
# line 697 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 13/*D*/, DEFAULT, DEFAULT_TIMEOUT);
# line 698 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 699 "../kohzuCtl_soft.st"
			lambdaHi = D * sin(thetaHi / radConv);
# line 700 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 19/*lambdaHi*/, DEFAULT, DEFAULT_TIMEOUT);
# line 701 "../kohzuCtl_soft.st"
			lambdaLo = D * sin(thetaLo / radConv);
# line 702 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 20/*lambdaLo*/, DEFAULT, DEFAULT_TIMEOUT);
# line 703 "../kohzuCtl_soft.st"
			EHi = hc / lambdaLo;
# line 704 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 15/*EHi*/, DEFAULT, DEFAULT_TIMEOUT);
# line 705 "../kohzuCtl_soft.st"
			ELo = hc / lambdaHi;
# line 706 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 16/*ELo*/, DEFAULT, DEFAULT_TIMEOUT);
# line 707 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "thetaLimits" in state set "kohzuCtl_soft" ******/

/* Event function for state "thetaLimits" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_thetaLimits(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "thetaLimits" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_thetaLimits(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 713 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:thetaLimits\n");
# line 714 "../kohzuCtl_soft.st"
			thetaHi = thetaMotHiLim;
# line 715 "../kohzuCtl_soft.st"
			thetaLo = thetaMotLoLim;
# line 716 "../kohzuCtl_soft.st"
			if (thetaHi > 89.0)
			{
# line 717 "../kohzuCtl_soft.st"
				thetaHi = 89.0;
# line 718 "../kohzuCtl_soft.st"
				sprintf(seqMsg2, "ThetaHiLim > 89 deg. (Using 89 deg.)");
# line 719 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 721 "../kohzuCtl_soft.st"
			if (thetaLo < 1.0)
			{
# line 722 "../kohzuCtl_soft.st"
				thetaLo = 1.0;
# line 723 "../kohzuCtl_soft.st"
				sprintf(seqMsg2, "ThetaLoLim < 1 deg. (Using 1 deg.)");
# line 724 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 726 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 23/*thetaHi*/, DEFAULT, DEFAULT_TIMEOUT);
# line 727 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 24/*thetaLo*/, DEFAULT, DEFAULT_TIMEOUT);
# line 728 "../kohzuCtl_soft.st"
			lambdaHi = D * sin(thetaHi / radConv);
# line 729 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 19/*lambdaHi*/, DEFAULT, DEFAULT_TIMEOUT);
# line 730 "../kohzuCtl_soft.st"
			lambdaLo = D * sin(thetaLo / radConv);
# line 731 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 20/*lambdaLo*/, DEFAULT, DEFAULT_TIMEOUT);
# line 732 "../kohzuCtl_soft.st"
			EHi = hc / lambdaLo;
# line 733 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 15/*EHi*/, DEFAULT, DEFAULT_TIMEOUT);
# line 734 "../kohzuCtl_soft.st"
			ELo = hc / lambdaHi;
# line 735 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 16/*ELo*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "eChanged" in state set "kohzuCtl_soft" ******/

/* Event function for state "eChanged" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_eChanged(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "eChanged" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_eChanged(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 741 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:eChanged\n");
# line 742 "../kohzuCtl_soft.st"
			lambda = hc / E;
# line 743 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 18/*lambda*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "lChanged" in state set "kohzuCtl_soft" ******/

/* Event function for state "lChanged" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_lChanged(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 748 "../kohzuCtl_soft.st"
	if (lambda > D)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "lChanged" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_lChanged(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 749 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:lChanged: lambda>D\n");
# line 751 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "Wavelength > 2d spacing.");
# line 752 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 753 "../kohzuCtl_soft.st"
			opAlert = 1;
# line 754 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 758 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:lChanged\n");
# line 759 "../kohzuCtl_soft.st"
			theta = radConv * asin(lambda / D);
# line 760 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 22/*theta*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "thChanged" in state set "kohzuCtl_soft" ******/

/* Event function for state "thChanged" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_thChanged(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "thChanged" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_thChanged(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 766 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:thChanged\n");
# line 767 "../kohzuCtl_soft.st"
			if ((theta <= thetaLo) || (theta >= thetaHi))
			{
# line 768 "../kohzuCtl_soft.st"
				sprintf(seqMsg1, "Theta constrained to LIMIT");
# line 769 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 770 "../kohzuCtl_soft.st"
				opAlert = 1;
# line 771 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 772 "../kohzuCtl_soft.st"
				if (theta < thetaLo)
# line 772 "../kohzuCtl_soft.st"
					theta = thetaLo;
# line 773 "../kohzuCtl_soft.st"
				if (theta > thetaHi)
# line 773 "../kohzuCtl_soft.st"
					theta = thetaHi;
# line 774 "../kohzuCtl_soft.st"
				if (riskAverse)
				{
# line 775 "../kohzuCtl_soft.st"
					autoMode = 0;
# line 776 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 777 "../kohzuCtl_soft.st"
					sprintf(seqMsg2, "Set to Manual Mode");
# line 778 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
				}
				else
				{
# line 780 "../kohzuCtl_soft.st"
					willViolateLimit = 1;
				}
			}
# line 783 "../kohzuCtl_soft.st"
			lambda = D * sin(theta / radConv);
# line 784 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 18/*lambda*/, DEFAULT, DEFAULT_TIMEOUT);
# line 785 "../kohzuCtl_soft.st"
			E = hc / lambda;
# line 786 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 14/*E*/, DEFAULT, DEFAULT_TIMEOUT);
# line 789 "../kohzuCtl_soft.st"
			thetaRdbk = thetaMotRdbk;
# line 790 "../kohzuCtl_soft.st"
			lambdaRdbk = D * sin(thetaRdbk / radConv);
# line 791 "../kohzuCtl_soft.st"
			ERdbk = hc / lambdaRdbk;
# line 792 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 25/*thetaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 793 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 21/*lambdaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 794 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 17/*ERdbk*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "calcMovements" in state set "kohzuCtl_soft" ******/

/* Event function for state "calcMovements" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_calcMovements(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "calcMovements" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_calcMovements(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 800 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:calcMovements\n");
# line 803 "../kohzuCtl_soft.st"
			thetaMotDesired = theta;
# line 804 "../kohzuCtl_soft.st"
			if (geom == 1)
			{
# line 805 "../kohzuCtl_soft.st"
				yMotDesired = -yOffset / cos(theta / radConv);
# line 806 "../kohzuCtl_soft.st"
				zMotDesired = yOffset / sin(theta / radConv);
			}
			else
			{
# line 808 "../kohzuCtl_soft.st"
				yMotDesired = yOffset / (2 * cos(theta / radConv));
# line 809 "../kohzuCtl_soft.st"
				zMotDesired = yOffset / (2 * sin(theta / radConv));
			}
# line 811 "../kohzuCtl_soft.st"
			if (ccMode != 1 && ccMode != 3 && ((yMotDesired < yMotLoLim) || (yMotDesired > yMotHiLim)))
			{
# line 813 "../kohzuCtl_soft.st"
				sprintf(seqMsg1, "Y will exceed soft limits");
# line 814 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 815 "../kohzuCtl_soft.st"
				opAlert = 1;
# line 816 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 817 "../kohzuCtl_soft.st"
				if (riskAverse)
				{
# line 818 "../kohzuCtl_soft.st"
					sprintf(seqMsg2, "Setting to Manual Mode");
# line 819 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 820 "../kohzuCtl_soft.st"
					opAlert = 1;
# line 821 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 822 "../kohzuCtl_soft.st"
					autoMode = 0;
# line 823 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
				}
				else
				{
# line 825 "../kohzuCtl_soft.st"
					willViolateLimit = 1;
				}
			}
# line 828 "../kohzuCtl_soft.st"
			if (ccMode != 1 && ccMode != 2 && ((zMotDesired < zMotLoLim) || (zMotDesired > zMotHiLim)))
			{
# line 830 "../kohzuCtl_soft.st"
				sprintf(seqMsg1, "Z will exceed soft limits");
# line 831 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 832 "../kohzuCtl_soft.st"
				opAlert = 1;
# line 833 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 834 "../kohzuCtl_soft.st"
				if (riskAverse)
				{
# line 835 "../kohzuCtl_soft.st"
					sprintf(seqMsg2, "Setting to Manual Mode");
# line 836 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 837 "../kohzuCtl_soft.st"
					opAlert = 1;
# line 838 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 839 "../kohzuCtl_soft.st"
					autoMode = 0;
# line 840 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
				}
				else
				{
# line 842 "../kohzuCtl_soft.st"
					willViolateLimit = 1;
				}
			}
# line 845 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 53/*thetaMotDesired*/, DEFAULT, DEFAULT_TIMEOUT);
# line 846 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 54/*yMotDesired*/, DEFAULT, DEFAULT_TIMEOUT);
# line 847 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 57/*zMotDesired*/, DEFAULT, DEFAULT_TIMEOUT);
# line 850 "../kohzuCtl_soft.st"
			oldThSpeed = thSpeed;
# line 851 "../kohzuCtl_soft.st"
			oldYSpeed = ySpeed;
# line 852 "../kohzuCtl_soft.st"
			oldZSpeed = zSpeed;
# line 853 "../kohzuCtl_soft.st"
			thTime = fabs(theta - thetaMotRdbk) / thSpeed;
# line 854 "../kohzuCtl_soft.st"
			yTime = fabs(yMotDesired - yMotRdbk) / ySpeed;
# line 855 "../kohzuCtl_soft.st"
			zTime = fabs(zMotDesired - zMotRdbk) / zSpeed;
# line 857 "../kohzuCtl_soft.st"
			if (ccMode == 1)
			{
# line 859 "../kohzuCtl_soft.st"
				yTime = 0.0;
# line 860 "../kohzuCtl_soft.st"
				zTime = 0.0;
			}
			else
# line 861 "../kohzuCtl_soft.st"
				if (ccMode == 2)
				{
# line 863 "../kohzuCtl_soft.st"
					zTime = 0.0;
				}
				else
# line 864 "../kohzuCtl_soft.st"
					if (ccMode == 3)
					{
# line 866 "../kohzuCtl_soft.st"
						yTime = 0.0;
					}
# line 869 "../kohzuCtl_soft.st"
			if ((thTime >= yTime) && (thTime >= zTime))
			{
# line 870 "../kohzuCtl_soft.st"
				newThSpeed = thSpeed;
# line 871 "../kohzuCtl_soft.st"
				newYSpeed = fabs(yMotDesired - yMotRdbk) / thTime;
# line 872 "../kohzuCtl_soft.st"
				newZSpeed = fabs(zMotDesired - zMotRdbk) / thTime;
			}
			else
# line 873 "../kohzuCtl_soft.st"
				if ((yTime >= thTime) && (yTime >= zTime))
				{
# line 874 "../kohzuCtl_soft.st"
					newThSpeed = fabs(theta - thetaMotRdbk) / yTime;
# line 875 "../kohzuCtl_soft.st"
					newYSpeed = ySpeed;
# line 876 "../kohzuCtl_soft.st"
					newZSpeed = fabs(zMotDesired - zMotRdbk) / yTime;
				}
				else
				{
# line 878 "../kohzuCtl_soft.st"
					newThSpeed = fabs(theta - thetaMotRdbk) / zTime;
# line 879 "../kohzuCtl_soft.st"
					newYSpeed = fabs(yMotDesired - yMotRdbk) / zTime;
# line 880 "../kohzuCtl_soft.st"
					newZSpeed = zSpeed;
				}
		}
		return;
	}
}

/****** Code for state "moveKohzu" in state set "kohzuCtl_soft" ******/

/* Event function for state "moveKohzu" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_moveKohzu(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 887 "../kohzuCtl_soft.st"
	if (autoMode || putVals || useSetMode)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 935 "../kohzuCtl_soft.st"
	if (1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "moveKohzu" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_moveKohzu(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 888 "../kohzuCtl_soft.st"
			if (willViolateLimit)
			{
# line 889 "../kohzuCtl_soft.st"
				E = prev_E;
# line 890 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 14/*E*/, DEFAULT, DEFAULT_TIMEOUT);
# line 891 "../kohzuCtl_soft.st"
				theta = prev_theta;
# line 892 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 22/*theta*/, DEFAULT, DEFAULT_TIMEOUT);
# line 893 "../kohzuCtl_soft.st"
				lambda = prev_lambda;
# line 894 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 18/*lambda*/, DEFAULT, DEFAULT_TIMEOUT);
# line 895 "../kohzuCtl_soft.st"
				thetaMotDesired = prev_thetaMotDesired;
# line 896 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 53/*thetaMotDesired*/, DEFAULT, DEFAULT_TIMEOUT);
# line 897 "../kohzuCtl_soft.st"
				yMotDesired = prev_yMotDesired;
# line 898 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 54/*yMotDesired*/, DEFAULT, DEFAULT_TIMEOUT);
# line 899 "../kohzuCtl_soft.st"
				zMotDesired = prev_zMotDesired;
# line 900 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 57/*zMotDesired*/, DEFAULT, DEFAULT_TIMEOUT);
# line 901 "../kohzuCtl_soft.st"
				sprintf(seqMsg2, "Command ignored");
# line 902 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			else
			{
# line 904 "../kohzuCtl_soft.st"
				if (kohzuCtlDebug)
					printf("kohzuCtl:moveKohzu:auto|put\n");
# line 905 "../kohzuCtl_soft.st"
				thSpeed = newThSpeed;
# line 906 "../kohzuCtl_soft.st"
				ySpeed = newYSpeed;
# line 907 "../kohzuCtl_soft.st"
				zSpeed = newZSpeed;
# line 908 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 70/*thSpeed*/, DEFAULT, DEFAULT_TIMEOUT);
# line 909 "../kohzuCtl_soft.st"
				if (ccMode == 0 || ccMode == 2)
				{
# line 910 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 71/*ySpeed*/, DEFAULT, DEFAULT_TIMEOUT);
				}
# line 912 "../kohzuCtl_soft.st"
				if (ccMode == 0 || ccMode == 3)
				{
# line 913 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 72/*zSpeed*/, DEFAULT, DEFAULT_TIMEOUT);
				}
# line 915 "../kohzuCtl_soft.st"
				thetaMotCmd = thetaMotDesired;
# line 916 "../kohzuCtl_soft.st"
				yMotCmd = yMotDesired;
# line 917 "../kohzuCtl_soft.st"
				zMotCmd = zMotDesired;
# line 918 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 64/*thetaMotCmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 919 "../kohzuCtl_soft.st"
				if (ccMode == 0)
				{
# line 920 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 65/*yMotCmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 921 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 66/*zMotCmd*/, DEFAULT, DEFAULT_TIMEOUT);
				}
				else
# line 922 "../kohzuCtl_soft.st"
					if (ccMode == 1)
					{
# line 923 "../kohzuCtl_soft.st"
						;
					}
					else
# line 924 "../kohzuCtl_soft.st"
						if (ccMode == 2)
						{
# line 925 "../kohzuCtl_soft.st"
							seq_pvPutTmo(seqg_env, 65/*yMotCmd*/, DEFAULT, DEFAULT_TIMEOUT);
						}
						else
# line 926 "../kohzuCtl_soft.st"
							if (ccMode == 3)
							{
# line 927 "../kohzuCtl_soft.st"
								seq_pvPutTmo(seqg_env, 66/*zMotCmd*/, DEFAULT, DEFAULT_TIMEOUT);
							}
# line 929 "../kohzuCtl_soft.st"
				putVals = 0;
# line 930 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 5/*putVals*/, DEFAULT, DEFAULT_TIMEOUT);
# line 931 "../kohzuCtl_soft.st"
				causedMove = 1;
			}
		}
		return;
	case 1:
		{
# line 936 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:moveKohzu\n");
		}
		return;
	}
}

/****** Code for state "checkDone" in state set "kohzuCtl_soft" ******/

/* Event function for state "checkDone" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_checkDone(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 941 "../kohzuCtl_soft.st"
	if (thetaDmov && yDmov && zDmov)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 946 "../kohzuCtl_soft.st"
	if (!thetaDmov || !yDmov || !zDmov)
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "checkDone" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_checkDone(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 942 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:checkDone: done\n");
# line 943 "../kohzuCtl_soft.st"
			kohzuDone = 1;
		}
		return;
	case 1:
		{
# line 947 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:checkDone: not done\n");
		}
		return;
	}
}

/****** Code for state "updateRdbk" in state set "kohzuCtl_soft" ******/

/* Event function for state "updateRdbk" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_updateRdbk(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 953 "../kohzuCtl_soft.st"
	if (willViolateLimit == 1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 956 "../kohzuCtl_soft.st"
	if (thetaMotRdbk == 0)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 967 "../kohzuCtl_soft.st"
	if (thetaDmov && yDmov && zDmov && seq_delay(seqg_env, 0.01))
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 982 "../kohzuCtl_soft.st"
	if (thetaHls || thetaLls)
	{
		*seqg_pnst = 16;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 995 "../kohzuCtl_soft.st"
	if ((ccMode != 1) && (ccMode != 3) && (yHls || yLls))
	{
		*seqg_pnst = 16;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 1008 "../kohzuCtl_soft.st"
	if ((ccMode != 1) && (ccMode != 2) && (zHls || zLls))
	{
		*seqg_pnst = 16;
		*seqg_ptrn = 5;
		return TRUE;
	}
# line 1020 "../kohzuCtl_soft.st"
	if ((!thetaDmov || !yDmov || !zDmov) && seq_delay(seqg_env, .1))
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 6;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "updateRdbk" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_updateRdbk(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 957 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:updateRdbk:thetaMotRdbk==0\n");
# line 958 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "Theta Motor Readback is 0 !");
# line 959 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 960 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, "Monochromator stopped");
# line 961 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 962 "../kohzuCtl_soft.st"
			opAlert = 1;
# line 963 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 2:
		{
# line 968 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:updateRdbk:*Dmov (done=%d,moving=%d)\n", kohzuDone, kohzuMoving);
# line 969 "../kohzuCtl_soft.st"
			thetaRdbk = thetaMotRdbk;
# line 970 "../kohzuCtl_soft.st"
			lambdaRdbk = D * sin(thetaRdbk / radConv);
# line 971 "../kohzuCtl_soft.st"
			ERdbk = hc / lambdaRdbk;
# line 972 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 25/*thetaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 973 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 21/*lambdaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 974 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 17/*ERdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 975 "../kohzuCtl_soft.st"
			kohzuDone = 1;
# line 976 "../kohzuCtl_soft.st"
			seq_efSet(seqg_env, thetaMotRdbkPseudo_mon);
# line 977 "../kohzuCtl_soft.st"
			seq_efClear(seqg_env, thetaMotRdbk_mon);
# line 978 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:updateRdbk: done\n");
		}
		return;
	case 3:
		{
# line 983 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:updateRdbk: Th limit switch\n");
# line 984 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "Theta Motor hit a limit switch!");
# line 985 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 986 "../kohzuCtl_soft.st"
			opAlert = 1;
# line 987 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 988 "../kohzuCtl_soft.st"
			autoMode = 0;
# line 989 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 990 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, "Setting to Manual Mode");
# line 991 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 4:
		{
# line 996 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:updateRdbk: Y limit switch\n");
# line 997 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "Y Motor hit a limit switch!");
# line 998 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 999 "../kohzuCtl_soft.st"
			opAlert = 1;
# line 1000 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1001 "../kohzuCtl_soft.st"
			autoMode = 0;
# line 1002 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1003 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, "Setting to Manual Mode");
# line 1004 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 5:
		{
# line 1009 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:updateRdbk: Z limit switch\n");
# line 1010 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "Z Motor hit a limit switch!");
# line 1011 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1012 "../kohzuCtl_soft.st"
			opAlert = 1;
# line 1013 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1014 "../kohzuCtl_soft.st"
			autoMode = 0;
# line 1015 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1016 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, "Setting to Manual Mode");
# line 1017 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 6:
		{
# line 1021 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug > 1)
				printf("kohzuCtl:updateRdbk:moving\n");
# line 1022 "../kohzuCtl_soft.st"
			thetaRdbk = thetaMotRdbk;
# line 1023 "../kohzuCtl_soft.st"
			lambdaRdbk = D * sin(thetaRdbk / radConv);
# line 1024 "../kohzuCtl_soft.st"
			ERdbk = hc / lambdaRdbk;
# line 1025 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 25/*thetaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1026 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 21/*lambdaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1027 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 17/*ERdbk*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "thetaMotStopped" in state set "kohzuCtl_soft" ******/

/* Event function for state "thetaMotStopped" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_thetaMotStopped(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 1032 "../kohzuCtl_soft.st"
	if (causedMove)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 1045 "../kohzuCtl_soft.st"
	if (!causedMove)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "thetaMotStopped" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_thetaMotStopped(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 1033 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:thetaMotStopped:causedMove (done=%d,moving=%d)\n", kohzuDone, kohzuMoving);
# line 1034 "../kohzuCtl_soft.st"
			thSpeed = oldThSpeed;
# line 1035 "../kohzuCtl_soft.st"
			ySpeed = oldYSpeed;
# line 1036 "../kohzuCtl_soft.st"
			zSpeed = oldZSpeed;
# line 1037 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 70/*thSpeed*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1038 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 71/*ySpeed*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1039 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:thetaMotStopped: ySpeed = %f\n", ySpeed);
# line 1040 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 72/*zSpeed*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1041 "../kohzuCtl_soft.st"
			causedMove = 0;
		}
		return;
	case 1:
		{
# line 1046 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:thetaMotStopped:!causedMove (done=%d,moving=%d)\n", kohzuDone, kohzuMoving);
# line 1047 "../kohzuCtl_soft.st"
			if (initSeqDone)
			{
# line 1048 "../kohzuCtl_soft.st"
				opAlert = 1;
# line 1049 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1050 "../kohzuCtl_soft.st"
				sprintf(seqMsg1, "Only Theta Motor Moved");
# line 1051 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1052 "../kohzuCtl_soft.st"
				sprintf(seqMsg2, "Hit MOVE to Adjust Y & Z");
# line 1053 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1054 "../kohzuCtl_soft.st"
				autoMode = 0;
# line 1055 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 1057 "../kohzuCtl_soft.st"
			theta = thetaMotRdbk;
# line 1058 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 22/*theta*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1059 "../kohzuCtl_soft.st"
			lambda = D * sin(theta / radConv);
# line 1060 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 18/*lambda*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1061 "../kohzuCtl_soft.st"
			E = hc / lambda;
# line 1062 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 14/*E*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "chkMotorLimits" in state set "kohzuCtl_soft" ******/

/* Event function for state "chkMotorLimits" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_chkMotorLimits(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 15;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "chkMotorLimits" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_chkMotorLimits(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 1068 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:chkMotorLimits\n");
# line 1069 "../kohzuCtl_soft.st"
			opAlert = 0;
# line 1070 "../kohzuCtl_soft.st"
			thetaRdbk = thetaMotRdbk;
# line 1071 "../kohzuCtl_soft.st"
			lambdaRdbk = D * sin(thetaRdbk / radConv);
# line 1072 "../kohzuCtl_soft.st"
			ERdbk = hc / lambdaRdbk;
# line 1073 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 25/*thetaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1074 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 21/*lambdaRdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1075 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 17/*ERdbk*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1077 "../kohzuCtl_soft.st"
			if (ccMode != 1 && ccMode != 3)
			{
# line 1078 "../kohzuCtl_soft.st"
				if (yMotRdbk == 0)
				{
# line 1079 "../kohzuCtl_soft.st"
					sprintf(seqMsg1, "Y Readback of 0 not reasonable");
# line 1080 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1081 "../kohzuCtl_soft.st"
					opAlert = 1;
				}
# line 1083 "../kohzuCtl_soft.st"
				if ((yMotRdbk < yMotLoLim) || (yMotRdbk > yMotHiLim))
				{
# line 1084 "../kohzuCtl_soft.st"
					sprintf(seqMsg1, "Y Readback outside Motor Limits");
# line 1085 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1086 "../kohzuCtl_soft.st"
					opAlert = 1;
				}
			}
# line 1089 "../kohzuCtl_soft.st"
			if (ccMode != 1 && ccMode != 2)
			{
# line 1090 "../kohzuCtl_soft.st"
				if (zMotRdbk == 0)
				{
# line 1091 "../kohzuCtl_soft.st"
					sprintf(seqMsg1, "Z Readback of 0 not reasonable");
# line 1092 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1093 "../kohzuCtl_soft.st"
					opAlert = 1;
				}
# line 1095 "../kohzuCtl_soft.st"
				if ((zMotRdbk < zMotLoLim) || (zMotRdbk > zMotHiLim))
				{
# line 1096 "../kohzuCtl_soft.st"
					sprintf(seqMsg1, "Z Readback outside Motor Limits");
# line 1097 "../kohzuCtl_soft.st"
					seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1098 "../kohzuCtl_soft.st"
					opAlert = 1;
				}
			}
# line 1101 "../kohzuCtl_soft.st"
			if (thetaMotRdbk == 0)
			{
# line 1102 "../kohzuCtl_soft.st"
				sprintf(seqMsg1, "Theta Readback of 0 not reasonable");
# line 1103 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1104 "../kohzuCtl_soft.st"
				opAlert = 1;
			}
# line 1106 "../kohzuCtl_soft.st"
			if ((thetaMotRdbk < thetaMotLoLim) || (thetaMotRdbk > thetaMotHiLim))
			{
# line 1107 "../kohzuCtl_soft.st"
				sprintf(seqMsg1, "Theta Readback outside Motor Limits");
# line 1108 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1109 "../kohzuCtl_soft.st"
				opAlert = 1;
			}
# line 1111 "../kohzuCtl_soft.st"
			if (opAlert)
			{
# line 1112 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1113 "../kohzuCtl_soft.st"
				autoMode = 0;
# line 1114 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 6/*autoMode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1115 "../kohzuCtl_soft.st"
				sprintf(seqMsg2, "Set to Manual Mode");
# line 1116 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

/****** Code for state "chkMotorLimitsExit" in state set "kohzuCtl_soft" ******/

/* Event function for state "chkMotorLimitsExit" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_chkMotorLimitsExit(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 1122 "../kohzuCtl_soft.st"
	if (!opAlert)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 1129 "../kohzuCtl_soft.st"
	if (opAlert && seq_delay(seqg_env, 2.))
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "chkMotorLimitsExit" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_chkMotorLimitsExit(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 1123 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:chkMotorLimitsExit: OK\n");
# line 1124 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1125 "../kohzuCtl_soft.st"
			sprintf(seqMsg1, "All motors within limits");
# line 1126 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 1/*seqMsg1*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 1130 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:chkMotorLimitsExit: opAlert\n");
# line 1131 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 3/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1132 "../kohzuCtl_soft.st"
			sprintf(seqMsg2, "Modify Motor Positions/Limits");
# line 1133 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 2/*seqMsg2*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "stopKohzu" in state set "kohzuCtl_soft" ******/

/* Event function for state "stopKohzu" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_stopKohzu(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 17;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "stopKohzu" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_stopKohzu(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 1139 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:stopKohzu\n");
# line 1140 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 41/*thetaMotStop*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1141 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 42/*yStop*/, DEFAULT, DEFAULT_TIMEOUT);
# line 1142 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 43/*zStop*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "stoppedKohzuWait" in state set "kohzuCtl_soft" ******/

/* Event function for state "stoppedKohzuWait" in state set "kohzuCtl_soft" */
static seqBool seqg_event_kohzuCtl_soft_0_stoppedKohzuWait(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 1147 "../kohzuCtl_soft.st"
	if (seq_delay(seqg_env, 1.))
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "stoppedKohzuWait" in state set "kohzuCtl_soft" */
static void seqg_action_kohzuCtl_soft_0_stoppedKohzuWait(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 1148 "../kohzuCtl_soft.st"
			if (kohzuCtlDebug)
				printf("kohzuCtl:stoppedKohzuWait\n");
		}
		return;
	}
}

/****** Code for state "init" in state set "updatePsuedo_soft" ******/

/* Event function for state "init" in state set "updatePsuedo_soft" */
static seqBool seqg_event_updatePsuedo_soft_1_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "updatePsuedo_soft" */
static void seqg_action_updatePsuedo_soft_1_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "update" in state set "updatePsuedo_soft" ******/

/* Event function for state "update" in state set "updatePsuedo_soft" */
static seqBool seqg_event_updatePsuedo_soft_1_update(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 1167 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, thetaMotRdbkPseudo_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 1172 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, yMotRdbk_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 1177 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, zMotRdbk_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 1182 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, thetaMotVel_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 1187 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, yMotVel_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 1192 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, zMotVel_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 5;
		return TRUE;
	}
# line 1197 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, thetaMotCmdMon_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 6;
		return TRUE;
	}
# line 1202 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, yMotCmdMon_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 7;
		return TRUE;
	}
# line 1207 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, zMotCmdMon_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 8;
		return TRUE;
	}
# line 1212 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, thetaDmov_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 9;
		return TRUE;
	}
# line 1217 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, yDmov_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 10;
		return TRUE;
	}
# line 1222 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, zDmov_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 11;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "update" in state set "updatePsuedo_soft" */
static void seqg_action_updatePsuedo_soft_1_update(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 1168 "../kohzuCtl_soft.st"
			thetaMotRdbkEcho = thetaMotRdbk;
# line 1169 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 32/*thetaMotRdbkEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 1173 "../kohzuCtl_soft.st"
			yMotRdbkEcho = yMotRdbk;
# line 1174 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 33/*yMotRdbkEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 2:
		{
# line 1178 "../kohzuCtl_soft.st"
			zMotRdbkEcho = zMotRdbk;
# line 1179 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 34/*zMotRdbkEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 3:
		{
# line 1183 "../kohzuCtl_soft.st"
			thetaMotVelEcho = thSpeed;
# line 1184 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 35/*thetaMotVelEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 4:
		{
# line 1188 "../kohzuCtl_soft.st"
			yMotVelEcho = ySpeed;
# line 1189 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 36/*yMotVelEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 5:
		{
# line 1193 "../kohzuCtl_soft.st"
			zMotVelEcho = zSpeed;
# line 1194 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 37/*zMotVelEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 6:
		{
# line 1198 "../kohzuCtl_soft.st"
			thetaMotCmdEcho = thetaMotCmdMon;
# line 1199 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 29/*thetaMotCmdEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 7:
		{
# line 1203 "../kohzuCtl_soft.st"
			yMotCmdEcho = yMotCmdMon;
# line 1204 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 30/*yMotCmdEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 8:
		{
# line 1208 "../kohzuCtl_soft.st"
			zMotCmdEcho = zMotCmdMon;
# line 1209 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 31/*zMotCmdEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 9:
		{
# line 1213 "../kohzuCtl_soft.st"
			thetaDmovEcho = thetaDmov;
# line 1214 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 38/*thetaDmovEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 10:
		{
# line 1218 "../kohzuCtl_soft.st"
			yDmovEcho = yDmov;
# line 1219 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 39/*yDmovEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 11:
		{
# line 1223 "../kohzuCtl_soft.st"
			zDmovEcho = zDmov;
# line 1224 "../kohzuCtl_soft.st"
			seq_pvPutTmo(seqg_env, 40/*zDmovEcho*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "init" in state set "updateSet" ******/

/* Event function for state "init" in state set "updateSet" */
static seqBool seqg_event_updateSet_2_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "updateSet" */
static void seqg_action_updateSet_2_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "update" in state set "updateSet" ******/

/* Event function for state "update" in state set "updateSet" */
static seqBool seqg_event_updateSet_2_update(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 1242 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, useSetMode_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 1257 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, thetaMotSet_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 1264 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, yMotSet_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 1271 "../kohzuCtl_soft.st"
	if (seq_efTestAndClear(seqg_env, zMotSet_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 3;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "update" in state set "updateSet" */
static void seqg_action_updateSet_2_update(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 1243 "../kohzuCtl_soft.st"
			if (thetaMotSet != useSetMode)
			{
# line 1244 "../kohzuCtl_soft.st"
				thetaMotSet = useSetMode;
# line 1245 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 77/*thetaMotSet*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 1247 "../kohzuCtl_soft.st"
			if (yMotSet != useSetMode)
			{
# line 1248 "../kohzuCtl_soft.st"
				yMotSet = useSetMode;
# line 1249 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 78/*yMotSet*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 1251 "../kohzuCtl_soft.st"
			if (zMotSet != useSetMode)
			{
# line 1252 "../kohzuCtl_soft.st"
				zMotSet = useSetMode;
# line 1253 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 79/*zMotSet*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	case 1:
		{
# line 1258 "../kohzuCtl_soft.st"
			if (useSetMode != thetaMotSet)
			{
# line 1259 "../kohzuCtl_soft.st"
				useSetMode = thetaMotSet;
# line 1260 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 76/*useSetMode*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	case 2:
		{
# line 1265 "../kohzuCtl_soft.st"
			if (useSetMode != yMotSet)
			{
# line 1266 "../kohzuCtl_soft.st"
				useSetMode = yMotSet;
# line 1267 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 76/*useSetMode*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	case 3:
		{
# line 1272 "../kohzuCtl_soft.st"
			if (useSetMode != zMotSet)
			{
# line 1273 "../kohzuCtl_soft.st"
				useSetMode = zMotSet;
# line 1274 "../kohzuCtl_soft.st"
				seq_pvPutTmo(seqg_env, 76/*useSetMode*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{P}{MONO}CtlDebug", (size_t)&kohzuCtlDebug, "kohzuCtlDebug", P_SHORT, 1, 28, 0, 1, 0, 0},
	{"{P}{MONO}SeqMsg1", (size_t)&seqMsg1, "seqMsg1", P_STRING, 1, 29, 0, 0, 0, 0},
	{"{P}{MONO}SeqMsg2", (size_t)&seqMsg2, "seqMsg2", P_STRING, 1, 30, 0, 0, 0, 0},
	{"{P}{MONO}Alert", (size_t)&opAlert, "opAlert", P_SHORT, 1, 31, 0, 0, 0, 0},
	{"{P}{MONO}OperAck", (size_t)&opAck, "opAck", P_SHORT, 1, 32, 0, 1, 0, 0},
	{"{P}{MONO}Put", (size_t)&putVals, "putVals", P_SHORT, 1, 33, 0, 1, 0, 0},
	{"{P}{MONO}Mode", (size_t)&autoMode, "autoMode", P_SHORT, 1, 34, 0, 1, 0, 0},
	{"{P}{MONO}Mode2", (size_t)&ccMode, "ccMode", P_SHORT, 1, 35, 0, 1, 0, 0},
	{"{P}{MONO}Moving", (size_t)&kohzuMoving, "kohzuMoving", P_SHORT, 1, 36, 0, 1, 0, 0},
	{"{P}{MONO}H", (size_t)&H, "H", P_DOUBLE, 1, 37, 1, 1, 0, 0},
	{"{P}{MONO}K", (size_t)&K, "K", P_DOUBLE, 1, 38, 2, 1, 0, 0},
	{"{P}{MONO}L", (size_t)&L, "L", P_DOUBLE, 1, 39, 3, 1, 0, 0},
	{"{P}{MONO}A", (size_t)&A, "A", P_DOUBLE, 1, 40, 4, 1, 0, 0},
	{"{P}{MONO}2dSpacing", (size_t)&D, "D", P_DOUBLE, 1, 41, 0, 0, 0, 0},
	{"{P}{MONO}E", (size_t)&E, "E", P_DOUBLE, 1, 42, 5, 1, 0, 0},
	{"{P}{MONO}E.HLM", (size_t)&EHi, "EHi", P_DOUBLE, 1, 43, 0, 0, 0, 0},
	{"{P}{MONO}E.LLM", (size_t)&ELo, "ELo", P_DOUBLE, 1, 44, 0, 0, 0, 0},
	{"{P}{MONO}ERdbk", (size_t)&ERdbk, "ERdbk", P_DOUBLE, 1, 45, 0, 0, 0, 0},
	{"{P}{MONO}Lambda", (size_t)&lambda, "lambda", P_DOUBLE, 1, 46, 6, 1, 0, 0},
	{"{P}{MONO}Lambda.HLM", (size_t)&lambdaHi, "lambdaHi", P_DOUBLE, 1, 47, 0, 0, 0, 0},
	{"{P}{MONO}Lambda.LLM", (size_t)&lambdaLo, "lambdaLo", P_DOUBLE, 1, 48, 0, 0, 0, 0},
	{"{P}{MONO}LambdaRdbk", (size_t)&lambdaRdbk, "lambdaRdbk", P_DOUBLE, 1, 49, 0, 0, 0, 0},
	{"{P}{MONO}Theta", (size_t)&theta, "theta", P_DOUBLE, 1, 50, 7, 1, 0, 0},
	{"{P}{MONO}Theta.HLM", (size_t)&thetaHi, "thetaHi", P_DOUBLE, 1, 51, 0, 0, 0, 0},
	{"{P}{MONO}Theta.LLM", (size_t)&thetaLo, "thetaLo", P_DOUBLE, 1, 52, 0, 0, 0, 0},
	{"{P}{MONO}ThetaRdbk", (size_t)&thetaRdbk, "thetaRdbk", P_DOUBLE, 1, 53, 0, 0, 0, 0},
	{"{P}{MONO}ThetaPv", (size_t)&thetaMotName, "thetaMotName", P_STRING, 1, 54, 0, 0, 0, 0},
	{"{P}{MONO}YPv", (size_t)&yMotName, "yMotName", P_STRING, 1, 55, 0, 0, 0, 0},
	{"{P}{MONO}ZPv", (size_t)&zMotName, "zMotName", P_STRING, 1, 56, 0, 0, 0, 0},
	{"{P}{MONO}ThetaCmd", (size_t)&thetaMotCmdEcho, "thetaMotCmdEcho", P_DOUBLE, 1, 57, 0, 0, 0, 0},
	{"{P}{MONO}YCmd", (size_t)&yMotCmdEcho, "yMotCmdEcho", P_DOUBLE, 1, 58, 0, 0, 0, 0},
	{"{P}{MONO}ZCmd", (size_t)&zMotCmdEcho, "zMotCmdEcho", P_DOUBLE, 1, 59, 0, 0, 0, 0},
	{"{P}{MONO}ThetaMotRdbk", (size_t)&thetaMotRdbkEcho, "thetaMotRdbkEcho", P_DOUBLE, 1, 60, 0, 0, 0, 0},
	{"{P}{MONO}YRdbk", (size_t)&yMotRdbkEcho, "yMotRdbkEcho", P_DOUBLE, 1, 61, 0, 0, 0, 0},
	{"{P}{MONO}ZRdbk", (size_t)&zMotRdbkEcho, "zMotRdbkEcho", P_DOUBLE, 1, 62, 0, 0, 0, 0},
	{"{P}{MONO}ThetaVel", (size_t)&thetaMotVelEcho, "thetaMotVelEcho", P_DOUBLE, 1, 63, 0, 0, 0, 0},
	{"{P}{MONO}YVel", (size_t)&yMotVelEcho, "yMotVelEcho", P_DOUBLE, 1, 64, 0, 0, 0, 0},
	{"{P}{MONO}ZVel", (size_t)&zMotVelEcho, "zMotVelEcho", P_DOUBLE, 1, 65, 0, 0, 0, 0},
	{"{P}{MONO}ThetaDmov", (size_t)&thetaDmovEcho, "thetaDmovEcho", P_SHORT, 1, 66, 0, 0, 0, 0},
	{"{P}{MONO}YDmov", (size_t)&yDmovEcho, "yDmovEcho", P_SHORT, 1, 67, 0, 0, 0, 0},
	{"{P}{MONO}ZDmov", (size_t)&zDmovEcho, "zDmovEcho", P_SHORT, 1, 68, 0, 0, 0, 0},
	{"{P}{M_THETA}.STOP", (size_t)&thetaMotStop, "thetaMotStop", P_SHORT, 1, 69, 0, 0, 0, 0},
	{"{P}{M_Y}.STOP", (size_t)&yStop, "yStop", P_SHORT, 1, 70, 0, 0, 0, 0},
	{"{P}{M_Z}.STOP", (size_t)&zStop, "zStop", P_SHORT, 1, 71, 0, 0, 0, 0},
	{"{P}{M_THETA}.DMOV", (size_t)&thetaDmov, "thetaDmov", P_SHORT, 1, 72, 8, 1, 0, 0},
	{"{P}{M_Y}.DMOV", (size_t)&yDmov, "yDmov", P_SHORT, 1, 73, 9, 1, 0, 0},
	{"{P}{M_Z}.DMOV", (size_t)&zDmov, "zDmov", P_SHORT, 1, 74, 10, 1, 0, 0},
	{"{P}{M_THETA}.HLS", (size_t)&thetaHls, "thetaHls", P_SHORT, 1, 75, 0, 1, 0, 0},
	{"{P}{M_THETA}.LLS", (size_t)&thetaLls, "thetaLls", P_SHORT, 1, 76, 0, 1, 0, 0},
	{"{P}{M_Y}.HLS", (size_t)&yHls, "yHls", P_SHORT, 1, 77, 0, 1, 0, 0},
	{"{P}{M_Y}.LLS", (size_t)&yLls, "yLls", P_SHORT, 1, 78, 0, 1, 0, 0},
	{"{P}{M_Z}.HLS", (size_t)&zHls, "zHls", P_SHORT, 1, 79, 0, 1, 0, 0},
	{"{P}{M_Z}.LLS", (size_t)&zLls, "zLls", P_SHORT, 1, 80, 0, 1, 0, 0},
	{"{P}{MONO}ThetaSet", (size_t)&thetaMotDesired, "thetaMotDesired", P_DOUBLE, 1, 81, 0, 1, 0, 0},
	{"{P}{MONO}YSet", (size_t)&yMotDesired, "yMotDesired", P_DOUBLE, 1, 82, 0, 1, 0, 0},
	{"{P}{MONO}YSet.DRVH", (size_t)&yMotDesiredHi, "yMotDesiredHi", P_DOUBLE, 1, 83, 0, 0, 0, 0},
	{"{P}{MONO}YSet.DRVL", (size_t)&yMotDesiredLo, "yMotDesiredLo", P_DOUBLE, 1, 84, 0, 0, 0, 0},
	{"{P}{MONO}ZSet", (size_t)&zMotDesired, "zMotDesired", P_DOUBLE, 1, 85, 0, 1, 0, 0},
	{"{P}{M_THETA}.HLM", (size_t)&thetaMotHiLim, "thetaMotHiLim", P_DOUBLE, 1, 86, 11, 1, 0, 0},
	{"{P}{M_THETA}.LLM", (size_t)&thetaMotLoLim, "thetaMotLoLim", P_DOUBLE, 1, 87, 12, 1, 0, 0},
	{"{P}{M_Y}.HLM", (size_t)&yMotHiLim, "yMotHiLim", P_DOUBLE, 1, 88, 0, 1, 0, 0},
	{"{P}{M_Y}.LLM", (size_t)&yMotLoLim, "yMotLoLim", P_DOUBLE, 1, 89, 0, 1, 0, 0},
	{"{P}{M_Z}.HLM", (size_t)&zMotHiLim, "zMotHiLim", P_DOUBLE, 1, 90, 0, 1, 0, 0},
	{"{P}{M_Z}.LLM", (size_t)&zMotLoLim, "zMotLoLim", P_DOUBLE, 1, 91, 0, 1, 0, 0},
	{"{P}{M_THETA}", (size_t)&thetaMotCmd, "thetaMotCmd", P_DOUBLE, 1, 92, 0, 0, 0, 0},
	{"{P}{M_Y}", (size_t)&yMotCmd, "yMotCmd", P_DOUBLE, 1, 93, 0, 0, 0, 0},
	{"{P}{M_Z}", (size_t)&zMotCmd, "zMotCmd", P_DOUBLE, 1, 94, 0, 0, 0, 0},
	{"{P}{M_THETA}", (size_t)&thetaMotCmdMon, "thetaMotCmdMon", P_DOUBLE, 1, 95, 13, 1, 0, 0},
	{"{P}{M_Y}", (size_t)&yMotCmdMon, "yMotCmdMon", P_DOUBLE, 1, 96, 14, 1, 0, 0},
	{"{P}{M_Z}", (size_t)&zMotCmdMon, "zMotCmdMon", P_DOUBLE, 1, 97, 15, 1, 0, 0},
	{"{P}{M_THETA}.VELO", (size_t)&thSpeed, "thSpeed", P_DOUBLE, 1, 98, 16, 1, 0, 0},
	{"{P}{M_Y}.VELO", (size_t)&ySpeed, "ySpeed", P_DOUBLE, 1, 99, 17, 1, 0, 0},
	{"{P}{M_Z}.VELO", (size_t)&zSpeed, "zSpeed", P_DOUBLE, 1, 100, 18, 1, 0, 0},
	{"{P}{M_THETA}.RBV", (size_t)&thetaMotRdbk, "thetaMotRdbk", P_DOUBLE, 1, 101, 19, 1, 0, 0},
	{"{P}{M_Y}.RBV", (size_t)&yMotRdbk, "yMotRdbk", P_DOUBLE, 1, 102, 21, 1, 0, 0},
	{"{P}{M_Z}.RBV", (size_t)&zMotRdbk, "zMotRdbk", P_DOUBLE, 1, 103, 22, 1, 0, 0},
	{"{P}{MONO}UseSet", (size_t)&useSetMode, "useSetMode", P_SHORT, 1, 104, 23, 1, 0, 0},
	{"{P}{M_THETA}.SET", (size_t)&thetaMotSet, "thetaMotSet", P_SHORT, 1, 105, 24, 1, 0, 0},
	{"{P}{M_Y}.SET", (size_t)&yMotSet, "yMotSet", P_SHORT, 1, 106, 25, 1, 0, 0},
	{"{P}{M_Z}.SET", (size_t)&zMotSet, "zMotSet", P_SHORT, 1, 107, 26, 1, 0, 0},
	{"{P}{MONO}yOffset", (size_t)&yOffset, "yOffset", P_DOUBLE, 1, 108, 27, 1, 0, 0},
	{"{P}{MONO}yOffset.DRVH", (size_t)&yOffsetHi, "yOffsetHi", P_DOUBLE, 1, 109, 0, 0, 0, 0},
	{"{P}{MONO}yOffset.DRVL", (size_t)&yOffsetLo, "yOffsetLo", P_DOUBLE, 1, 110, 0, 0, 0, 0},
};

/* Event masks for state set "kohzuCtl_soft" */
static const seqMask seqg_mask_kohzuCtl_soft_0_init[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_initSequence[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_waitForCmndEnter[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_waitForCmnd[] = {
	0x080818fe,
	0x00000003,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_dInputChanged[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_thetaLimits[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_eChanged[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_lChanged[] = {
	0x00000000,
	0x00004200,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_thChanged[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_calcMovements[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_moveKohzu[] = {
	0x00000000,
	0x00000006,
	0x00000000,
	0x00000100,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_checkDone[] = {
	0x00000000,
	0x00000000,
	0x00000700,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_updateRdbk[] = {
	0x00000000,
	0x00000008,
	0x0001ff00,
	0x00000020,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_thetaMotStopped[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_chkMotorLimits[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_chkMotorLimitsExit[] = {
	0x80000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_stopKohzu[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_kohzuCtl_soft_0_stoppedKohzuWait[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "kohzuCtl_soft" */
static seqState seqg_states_kohzuCtl_soft[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_kohzuCtl_soft_0_init,
	/* event function */    seqg_event_kohzuCtl_soft_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "initSequence",
	/* action function */   seqg_action_kohzuCtl_soft_0_initSequence,
	/* event function */    seqg_event_kohzuCtl_soft_0_initSequence,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_initSequence,
	/* state options */     (0)
	},
	{
	/* state name */        "waitForCmndEnter",
	/* action function */   seqg_action_kohzuCtl_soft_0_waitForCmndEnter,
	/* event function */    seqg_event_kohzuCtl_soft_0_waitForCmndEnter,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_waitForCmndEnter,
	/* state options */     (0)
	},
	{
	/* state name */        "waitForCmnd",
	/* action function */   seqg_action_kohzuCtl_soft_0_waitForCmnd,
	/* event function */    seqg_event_kohzuCtl_soft_0_waitForCmnd,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_waitForCmnd,
	/* state options */     (0)
	},
	{
	/* state name */        "dInputChanged",
	/* action function */   seqg_action_kohzuCtl_soft_0_dInputChanged,
	/* event function */    seqg_event_kohzuCtl_soft_0_dInputChanged,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_dInputChanged,
	/* state options */     (0)
	},
	{
	/* state name */        "thetaLimits",
	/* action function */   seqg_action_kohzuCtl_soft_0_thetaLimits,
	/* event function */    seqg_event_kohzuCtl_soft_0_thetaLimits,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_thetaLimits,
	/* state options */     (0)
	},
	{
	/* state name */        "eChanged",
	/* action function */   seqg_action_kohzuCtl_soft_0_eChanged,
	/* event function */    seqg_event_kohzuCtl_soft_0_eChanged,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_eChanged,
	/* state options */     (0)
	},
	{
	/* state name */        "lChanged",
	/* action function */   seqg_action_kohzuCtl_soft_0_lChanged,
	/* event function */    seqg_event_kohzuCtl_soft_0_lChanged,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_lChanged,
	/* state options */     (0)
	},
	{
	/* state name */        "thChanged",
	/* action function */   seqg_action_kohzuCtl_soft_0_thChanged,
	/* event function */    seqg_event_kohzuCtl_soft_0_thChanged,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_thChanged,
	/* state options */     (0)
	},
	{
	/* state name */        "calcMovements",
	/* action function */   seqg_action_kohzuCtl_soft_0_calcMovements,
	/* event function */    seqg_event_kohzuCtl_soft_0_calcMovements,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_calcMovements,
	/* state options */     (0)
	},
	{
	/* state name */        "moveKohzu",
	/* action function */   seqg_action_kohzuCtl_soft_0_moveKohzu,
	/* event function */    seqg_event_kohzuCtl_soft_0_moveKohzu,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_moveKohzu,
	/* state options */     (0)
	},
	{
	/* state name */        "checkDone",
	/* action function */   seqg_action_kohzuCtl_soft_0_checkDone,
	/* event function */    seqg_event_kohzuCtl_soft_0_checkDone,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_checkDone,
	/* state options */     (0)
	},
	{
	/* state name */        "updateRdbk",
	/* action function */   seqg_action_kohzuCtl_soft_0_updateRdbk,
	/* event function */    seqg_event_kohzuCtl_soft_0_updateRdbk,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_updateRdbk,
	/* state options */     (0)
	},
	{
	/* state name */        "thetaMotStopped",
	/* action function */   seqg_action_kohzuCtl_soft_0_thetaMotStopped,
	/* event function */    seqg_event_kohzuCtl_soft_0_thetaMotStopped,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_thetaMotStopped,
	/* state options */     (0)
	},
	{
	/* state name */        "chkMotorLimits",
	/* action function */   seqg_action_kohzuCtl_soft_0_chkMotorLimits,
	/* event function */    seqg_event_kohzuCtl_soft_0_chkMotorLimits,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_chkMotorLimits,
	/* state options */     (0)
	},
	{
	/* state name */        "chkMotorLimitsExit",
	/* action function */   seqg_action_kohzuCtl_soft_0_chkMotorLimitsExit,
	/* event function */    seqg_event_kohzuCtl_soft_0_chkMotorLimitsExit,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_chkMotorLimitsExit,
	/* state options */     (0)
	},
	{
	/* state name */        "stopKohzu",
	/* action function */   seqg_action_kohzuCtl_soft_0_stopKohzu,
	/* event function */    seqg_event_kohzuCtl_soft_0_stopKohzu,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_stopKohzu,
	/* state options */     (0)
	},
	{
	/* state name */        "stoppedKohzuWait",
	/* action function */   seqg_action_kohzuCtl_soft_0_stoppedKohzuWait,
	/* event function */    seqg_event_kohzuCtl_soft_0_stoppedKohzuWait,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_kohzuCtl_soft_0_stoppedKohzuWait,
	/* state options */     (0)
	},
};

/* Event masks for state set "updatePsuedo_soft" */
static const seqMask seqg_mask_updatePsuedo_soft_1_init[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_updatePsuedo_soft_1_update[] = {
	0x0077e700,
	0x00000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "updatePsuedo_soft" */
static seqState seqg_states_updatePsuedo_soft[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_updatePsuedo_soft_1_init,
	/* event function */    seqg_event_updatePsuedo_soft_1_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_updatePsuedo_soft_1_init,
	/* state options */     (0)
	},
	{
	/* state name */        "update",
	/* action function */   seqg_action_updatePsuedo_soft_1_update,
	/* event function */    seqg_event_updatePsuedo_soft_1_update,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_updatePsuedo_soft_1_update,
	/* state options */     (0)
	},
};

/* Event masks for state set "updateSet" */
static const seqMask seqg_mask_updateSet_2_init[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_updateSet_2_update[] = {
	0x07800000,
	0x00000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "updateSet" */
static seqState seqg_states_updateSet[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_updateSet_2_init,
	/* event function */    seqg_event_updateSet_2_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_updateSet_2_init,
	/* state options */     (0)
	},
	{
	/* state name */        "update",
	/* action function */   seqg_action_updateSet_2_update,
	/* event function */    seqg_event_updateSet_2_update,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_updateSet_2_update,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "kohzuCtl_soft",
	/* states */            seqg_states_kohzuCtl_soft,
	/* number of states */  18
	},

	{
	/* state set name */    "updatePsuedo_soft",
	/* states */            seqg_states_updatePsuedo_soft,
	/* number of states */  2
	},

	{
	/* state set name */    "updateSet",
	/* states */            seqg_states_updateSet,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram kohzuCtl_soft = {
	/* magic number */      2002005,
	/* program name */      "kohzuCtl_soft",
	/* channels */          seqg_chans,
	/* num. channels */     83,
	/* state sets */        seqg_statesets,
	/* num. state sets */   3,
	/* user var size */     0,
	/* param */             "P=xxx:, MONO=Kohzu1:, M_THETA=m9, M_Y=m10, M_Z=m11, GEOM=1",
	/* num. event flags */  27,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};
# line 1284 "../kohzuCtl_soft.st"



double kohzuCtl_soft_calc2dSpacing()
{

 double result;

 result = (2*A)/sqrt(H*H + K*K + L*L);


 opAlert = 0;
 if (((fmod(H,2)) != (fmod(K,2))) || ((fmod(H,2)) != (fmod(L,2))))
  opAlert = 1;
 avg = (H+K+L)/2.0;
 nint = (int)((avg)>0 ? (avg)+0.5 : (avg)-0.5);
 if ((fabs(avg-nint) <= .25) && (fmod(nint,2)))
  opAlert = 1;
 if (opAlert) {
  sprintf(seqMsg1, "(H,K,L) is 'forbidden' reflection");
 } else {
  sprintf(seqMsg1, "New d spacing");
 }
 return(result);
}




/* Register sequencer commands and program */
#include "epicsExport.h"
static void kohzuCtl_softRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&kohzuCtl_soft);
}
epicsExportRegistrar(kohzuCtl_softRegistrar);
