/* C code for program sncqxbpm, generated by snc from ../sncqxbpm.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 165 "../sncqxbpm.st"
static const EF_ID s_ainp_mon = 1;
# line 218 "../sncqxbpm.st"
static const EF_ID signal_mode_mon = 2;
# line 219 "../sncqxbpm.st"
static const EF_ID buflen_mon = 3;
# line 222 "../sncqxbpm.st"
static const EF_ID gain_mon = 4;
# line 223 "../sncqxbpm.st"
static const EF_ID period_s_mon = 5;
# line 280 "../sncqxbpm.st"
static const EF_ID started = 6;
# line 287 "../sncqxbpm.st"
#include <math.h>
# line 288 "../sncqxbpm.st"
#include <string.h>
# line 289 "../sncqxbpm.st"
#include <epicsThread.h>

/* Variable declarations */
# line 165 "../sncqxbpm.st"
static	string s_ainp;
# line 166 "../sncqxbpm.st"
static	string s_aout;
# line 167 "../sncqxbpm.st"
static	short s_baud;
# line 168 "../sncqxbpm.st"
static	short s_dbit;
# line 169 "../sncqxbpm.st"
static	short s_fctl;
# line 170 "../sncqxbpm.st"
static	string s_idel;
# line 171 "../sncqxbpm.st"
static	short s_ifmt;
# line 172 "../sncqxbpm.st"
static	short s_nord;
# line 173 "../sncqxbpm.st"
static	short s_nrrd;
# line 174 "../sncqxbpm.st"
static	string s_odel;
# line 175 "../sncqxbpm.st"
static	short s_ofmt;
# line 176 "../sncqxbpm.st"
static	short s_proc;
# line 177 "../sncqxbpm.st"
static	short s_prty;
# line 178 "../sncqxbpm.st"
static	short s_sbit;
# line 179 "../sncqxbpm.st"
static	short s_scan;
# line 180 "../sncqxbpm.st"
static	int s_sevr;
# line 181 "../sncqxbpm.st"
static	short s_tmod;
# line 182 "../sncqxbpm.st"
static	double s_tmot;
# line 190 "../sncqxbpm.st"
static	string port;
# line 191 "../sncqxbpm.st"
static	int bpm_address;
# line 192 "../sncqxbpm.st"
static	short init;
# line 193 "../sncqxbpm.st"
static	short enable;
# line 194 "../sncqxbpm.st"
static	int error;
# line 195 "../sncqxbpm.st"
static	string errMsg;
# line 196 "../sncqxbpm.st"
static	int debug_flag;
# line 197 "../sncqxbpm.st"
static	double pos_x;
# line 198 "../sncqxbpm.st"
static	double pos_y;
# line 199 "../sncqxbpm.st"
static	double current_total;
# line 200 "../sncqxbpm.st"
static	double current_a;
# line 201 "../sncqxbpm.st"
static	double current_b;
# line 202 "../sncqxbpm.st"
static	double current_c;
# line 203 "../sncqxbpm.st"
static	double current_d;
# line 210 "../sncqxbpm.st"
static	unsigned int raw_a;
# line 211 "../sncqxbpm.st"
static	unsigned int raw_b;
# line 212 "../sncqxbpm.st"
static	unsigned int raw_c;
# line 213 "../sncqxbpm.st"
static	unsigned int raw_d;
# line 215 "../sncqxbpm.st"
static	int current_low_raw;
# line 216 "../sncqxbpm.st"
static	short current_low;
# line 217 "../sncqxbpm.st"
static	short current_ok;
# line 218 "../sncqxbpm.st"
static	short signal_mode;
# line 219 "../sncqxbpm.st"
static	short buflen;
# line 220 "../sncqxbpm.st"
static	short buflen_lo;
# line 221 "../sncqxbpm.st"
static	short buflen_hi;
# line 222 "../sncqxbpm.st"
static	int gain;
# line 223 "../sncqxbpm.st"
static	double period_s;
# line 224 "../sncqxbpm.st"
static	double period_s_LOPR;
# line 225 "../sncqxbpm.st"
static	double period_s_HOPR;
# line 227 "../sncqxbpm.st"
static	double gx;
# line 228 "../sncqxbpm.st"
static	double gy;
# line 230 "../sncqxbpm.st"
static	short set_offsets;
# line 231 "../sncqxbpm.st"
static	short set_defaults;
# line 232 "../sncqxbpm.st"
static	double settling;
# line 242 "../sncqxbpm.st"
static	string gainStr[6];
# line 243 "../sncqxbpm.st"
static	string signal_modeStr[3];
# line 264 "../sncqxbpm.st"
static	double gainTrim[24];
# line 266 "../sncqxbpm.st"
static	int offset[24];
# line 273 "../sncqxbpm.st"
static	char scratch[256];
# line 274 "../sncqxbpm.st"
static	int i;
# line 275 "../sncqxbpm.st"
static	string bpm_command;
# line 276 "../sncqxbpm.st"
static	string bpm_response;
# line 277 "../sncqxbpm.st"
static	string SNLtaskName;
# line 278 "../sncqxbpm.st"
static	int retry;
# line 279 "../sncqxbpm.st"
static	double updateDelay;
# line 281 "../sncqxbpm.st"
static	int oldGain;
# line 282 "../sncqxbpm.st"
static	int newGain;
# line 283 "../sncqxbpm.st"
static	int channel;
# line 284 "../sncqxbpm.st"
static	double factor;
# line 285 "../sncqxbpm.st"
static	string debug_str;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "startup" in state set "sncqxbpm" ******/

/* Event function for state "startup" in state set "sncqxbpm" */
static seqBool seqg_event_sncqxbpm_0_startup(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "startup" in state set "sncqxbpm" */
static void seqg_action_sncqxbpm_0_startup(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 304 "../sncqxbpm.st"
			seq_efClear(seqg_env, started);
# line 306 "../sncqxbpm.st"
			seq_pvGetTmo(seqg_env, 0/*s_ainp*/, DEFAULT, DEFAULT_TIMEOUT);
# line 307 "../sncqxbpm.st"
			seq_pvGetTmo(seqg_env, 1/*s_aout*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 308 "../sncqxbpm.st"
				init = (1);
# line 308 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 20/*init*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 308 "../sncqxbpm.st"
			;
			{
# line 309 "../sncqxbpm.st"
				period_s_LOPR = (0.05);
# line 309 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 45/*period_s_LOPR*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 309 "../sncqxbpm.st"
			;
# line 314 "../sncqxbpm.st"
			strcpy(SNLtaskName, seq_macValueGet(seqg_env, "name"));
# line 315 "../sncqxbpm.st"
			strcpy(port, seq_macValueGet(seqg_env, "S"));
# line 316 "../sncqxbpm.st"
			seq_pvPutTmo(seqg_env, 18/*port*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 317 "../sncqxbpm.st"
				current_low = (1);
# line 317 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 37/*current_low*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 317 "../sncqxbpm.st"
			;
			{
# line 318 "../sncqxbpm.st"
				current_ok = (0);
# line 318 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 38/*current_ok*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 318 "../sncqxbpm.st"
			;
			{
# line 319 "../sncqxbpm.st"
				set_offsets = (0);
# line 319 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 49/*set_offsets*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 319 "../sncqxbpm.st"
			;
# line 320 "../sncqxbpm.st"
			updateDelay = 3;
# line 321 "../sncqxbpm.st"
			seq_efSet(seqg_env, started);
		}
		return;
	}
}

/****** Code for state "init" in state set "sncqxbpm" ******/

/* Event function for state "init" in state set "sncqxbpm" */
static seqBool seqg_event_sncqxbpm_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 327 "../sncqxbpm.st"
	if (!enable)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 330 "../sncqxbpm.st"
	if (init)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "sncqxbpm" */
static void seqg_action_sncqxbpm_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 328 "../sncqxbpm.st"
			if (debug_flag >= 0)
			{
# line 328 "../sncqxbpm.st"
				printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 328, SNLtaskName, 0);
# line 328 "../sncqxbpm.st"
				;
# line 328 "../sncqxbpm.st"
				printf("%s\n", "software disabled");
# line 328 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 328 "../sncqxbpm.st"
			;
		}
		return;
	case 1:
		{
			{
# line 334 "../sncqxbpm.st"
				init = (0);
# line 334 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 20/*init*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 334 "../sncqxbpm.st"
			;
			{
# line 338 "../sncqxbpm.st"
				s_baud = (7);
# line 338 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 2/*s_baud*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 338 "../sncqxbpm.st"
			;
			{
# line 338 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 338 "../sncqxbpm.st"
			;
			{
# line 339 "../sncqxbpm.st"
				s_dbit = (4);
# line 339 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 3/*s_dbit*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 339 "../sncqxbpm.st"
			;
			{
# line 339 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 339 "../sncqxbpm.st"
			;
			{
# line 340 "../sncqxbpm.st"
				s_prty = (1);
# line 340 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 12/*s_prty*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 340 "../sncqxbpm.st"
			;
			{
# line 340 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 340 "../sncqxbpm.st"
			;
			{
# line 341 "../sncqxbpm.st"
				s_sbit = (1);
# line 341 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 13/*s_sbit*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 341 "../sncqxbpm.st"
			;
			{
# line 341 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 341 "../sncqxbpm.st"
			;
			{
# line 342 "../sncqxbpm.st"
				s_fctl = (1);
# line 342 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 4/*s_fctl*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 342 "../sncqxbpm.st"
			;
			{
# line 342 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 342 "../sncqxbpm.st"
			;
			{
# line 343 "../sncqxbpm.st"
				s_tmot = (0.250);
# line 343 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 17/*s_tmot*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 343 "../sncqxbpm.st"
			;
			{
# line 344 "../sncqxbpm.st"
				s_ofmt = (0);
# line 344 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 10/*s_ofmt*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 344 "../sncqxbpm.st"
			;
			{
# line 345 "../sncqxbpm.st"
				s_ifmt = (0);
# line 345 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 6/*s_ifmt*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 345 "../sncqxbpm.st"
			;
			{
# line 346 "../sncqxbpm.st"
				strcpy(s_odel, "\n");
# line 346 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 9/*s_odel*/, SYNC, DEFAULT_TIMEOUT);
# line 346 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 346 "../sncqxbpm.st"
			;
			{
# line 346 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 346 "../sncqxbpm.st"
			;
			{
# line 347 "../sncqxbpm.st"
				strcpy(s_idel, "\n");
# line 347 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 5/*s_idel*/, SYNC, DEFAULT_TIMEOUT);
# line 347 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 347 "../sncqxbpm.st"
			;
			{
# line 347 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 347 "../sncqxbpm.st"
			;
			{
# line 348 "../sncqxbpm.st"
				s_nrrd = (0);
# line 348 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 8/*s_nrrd*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 348 "../sncqxbpm.st"
			;
			{
# line 349 "../sncqxbpm.st"
				s_scan = (0);
# line 349 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 14/*s_scan*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 349 "../sncqxbpm.st"
			;
# line 350 "../sncqxbpm.st"
			seq_efClear(seqg_env, s_ainp_mon);
			{
# line 364 "../sncqxbpm.st"
				sprintf(bpm_command, "*RST%d", bpm_address, 0, 0, 0);
# line 364 "../sncqxbpm.st"
				sprintf(debug_str, "BPM_COMM: <%s> (%d) <-- <%s>", s_aout, 1, bpm_command);
# line 364 "../sncqxbpm.st"
				if (debug_flag >= 15)
				{
# line 364 "../sncqxbpm.st"
					printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 364, SNLtaskName, 15);
# line 364 "../sncqxbpm.st"
					;
# line 364 "../sncqxbpm.st"
					printf("%s\n", debug_str);
# line 364 "../sncqxbpm.st"
					epicsThreadSleep(0.01);
				}
# line 364 "../sncqxbpm.st"
				;
# line 364 "../sncqxbpm.st"
				if (s_tmod != 1)
				{
# line 364 "../sncqxbpm.st"
					s_tmod = (1);
# line 364 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 16/*s_tmod*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 364 "../sncqxbpm.st"
				;
				{
# line 364 "../sncqxbpm.st"
					epicsThreadSleep(1 / 60.);
				}
# line 364 "../sncqxbpm.st"
				;
# line 364 "../sncqxbpm.st"
				if (1 == 1)
				{
# line 364 "../sncqxbpm.st"
					if (strcmp(s_aout, bpm_command))
					{
						{
# line 364 "../sncqxbpm.st"
							strcpy(s_aout, bpm_command);
# line 364 "../sncqxbpm.st"
							seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 364 "../sncqxbpm.st"
							epicsThreadSleep(0.01);
						}
# line 364 "../sncqxbpm.st"
						;
						{
# line 364 "../sncqxbpm.st"
							epicsThreadSleep(1 / 60.);
						}
# line 364 "../sncqxbpm.st"
						;
					}
					else
					{
						{
# line 364 "../sncqxbpm.st"
							s_proc = (1);
# line 364 "../sncqxbpm.st"
							seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
						}
# line 364 "../sncqxbpm.st"
						;
						{
# line 364 "../sncqxbpm.st"
							epicsThreadSleep(1 / 60.);
						}
# line 364 "../sncqxbpm.st"
						;
					}
				}
				else
				{
# line 364 "../sncqxbpm.st"
					strcpy(bpm_response, "");
# line 364 "../sncqxbpm.st"
					for (retry = 0; retry < 3; retry++)
					{
# line 364 "../sncqxbpm.st"
						if (strcmp(s_aout, bpm_command))
						{
							{
# line 364 "../sncqxbpm.st"
								strcpy(s_aout, bpm_command);
# line 364 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 364 "../sncqxbpm.st"
								epicsThreadSleep(0.01);
							}
# line 364 "../sncqxbpm.st"
							;
							{
# line 364 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 364 "../sncqxbpm.st"
							;
						}
						else
						{
							{
# line 364 "../sncqxbpm.st"
								s_proc = (1);
# line 364 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
							}
# line 364 "../sncqxbpm.st"
							;
							{
# line 364 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 364 "../sncqxbpm.st"
							;
						}
# line 364 "../sncqxbpm.st"
						for (i = 0; i < 0.25; i++)
						{
							{
# line 364 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 364 "../sncqxbpm.st"
							;
# line 364 "../sncqxbpm.st"
							if (seq_efTest(seqg_env, s_ainp_mon))
								break;
						}
# line 364 "../sncqxbpm.st"
						if (!s_sevr && seq_efTest(seqg_env, s_ainp_mon))
						{
# line 364 "../sncqxbpm.st"
							sprintf(debug_str, "BPM_COMM: <%s> ==> <%s>", s_aout, s_ainp);
# line 364 "../sncqxbpm.st"
							if (debug_flag >= 10)
							{
# line 364 "../sncqxbpm.st"
								printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 364, SNLtaskName, 10);
# line 364 "../sncqxbpm.st"
								;
# line 364 "../sncqxbpm.st"
								printf("%s\n", debug_str);
# line 364 "../sncqxbpm.st"
								epicsThreadSleep(0.01);
							}
# line 364 "../sncqxbpm.st"
							;
# line 364 "../sncqxbpm.st"
							strcpy(bpm_response, s_ainp + 1);
							break;
						}
					}
				}
			}
# line 364 "../sncqxbpm.st"
			;
			{
# line 365 "../sncqxbpm.st"
				epicsThreadSleep(6 / 60.);
			}
# line 365 "../sncqxbpm.st"
			;
# line 366 "../sncqxbpm.st"
			seq_efSet(seqg_env, gain_mon);
# line 367 "../sncqxbpm.st"
			seq_efSet(seqg_env, signal_mode_mon);
# line 368 "../sncqxbpm.st"
			seq_efSet(seqg_env, period_s_mon);
		}
		return;
	}
}

/****** Code for state "disable" in state set "sncqxbpm" ******/

/* Event function for state "disable" in state set "sncqxbpm" */
static seqBool seqg_event_sncqxbpm_0_disable(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 384 "../sncqxbpm.st"
	if (enable)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "disable" in state set "sncqxbpm" */
static void seqg_action_sncqxbpm_0_disable(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
			{
# line 385 "../sncqxbpm.st"
				init = (1);
# line 385 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 20/*init*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 385 "../sncqxbpm.st"
			;
# line 386 "../sncqxbpm.st"
			if (debug_flag >= 0)
			{
# line 386 "../sncqxbpm.st"
				printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 386, SNLtaskName, 0);
# line 386 "../sncqxbpm.st"
				;
# line 386 "../sncqxbpm.st"
				printf("%s\n", "software re-enabled");
# line 386 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 386 "../sncqxbpm.st"
			;
		}
		return;
	}
}

/****** Code for state "comm_error" in state set "sncqxbpm" ******/

/* Event function for state "comm_error" in state set "sncqxbpm" */
static seqBool seqg_event_sncqxbpm_0_comm_error(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 394 "../sncqxbpm.st"
	if (init || !s_sevr || seq_delay(seqg_env, (0.5 * 60.0)))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "comm_error" in state set "sncqxbpm" */
static void seqg_action_sncqxbpm_0_comm_error(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 395 "../sncqxbpm.st"
			sprintf(debug_str, "comm_error: init=%d  s_sevr=%d", init, s_sevr);
# line 396 "../sncqxbpm.st"
			if (debug_flag >= 20)
			{
# line 396 "../sncqxbpm.st"
				printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 396, SNLtaskName, 20);
# line 396 "../sncqxbpm.st"
				;
# line 396 "../sncqxbpm.st"
				printf("%s\n", debug_str);
# line 396 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 396 "../sncqxbpm.st"
			;
# line 397 "../sncqxbpm.st"
			s_sevr = 0;
			{
# line 398 "../sncqxbpm.st"
				init = (1);
# line 398 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 20/*init*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 398 "../sncqxbpm.st"
			;
		}
		return;
	}
}

/****** Code for state "idle" in state set "sncqxbpm" ******/

/* Event function for state "idle" in state set "sncqxbpm" */
static seqBool seqg_event_sncqxbpm_0_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 406 "../sncqxbpm.st"
	if (!enable)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 408 "../sncqxbpm.st"
	if (s_sevr)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 414 "../sncqxbpm.st"
	if (init)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 419 "../sncqxbpm.st"
	if (seq_efTestAndClear(seqg_env, gain_mon))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 432 "../sncqxbpm.st"
	if (seq_efTestAndClear(seqg_env, signal_mode_mon) || seq_efTestAndClear(seqg_env, buflen_mon))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 458 "../sncqxbpm.st"
	if (seq_efTestAndClear(seqg_env, period_s_mon))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 5;
		return TRUE;
	}
# line 466 "../sncqxbpm.st"
	if (seq_delay(seqg_env, period_s - 0.05 + updateDelay))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 6;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "sncqxbpm" */
static void seqg_action_sncqxbpm_0_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
			{
# line 409 "../sncqxbpm.st"
				error = (2);
# line 409 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 22/*error*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 409 "../sncqxbpm.st"
			;
# line 410 "../sncqxbpm.st"
			sprintf(scratch, "communications error: %d", s_sevr);
			{
# line 411 "../sncqxbpm.st"
				strcpy(errMsg, scratch);
# line 411 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 23/*errMsg*/, SYNC, DEFAULT_TIMEOUT);
# line 411 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 411 "../sncqxbpm.st"
			;
		}
		return;
	case 2:
		{
# line 415 "../sncqxbpm.st"
			if (debug_flag >= 20)
			{
# line 415 "../sncqxbpm.st"
				printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 415, SNLtaskName, 20);
# line 415 "../sncqxbpm.st"
				;
# line 415 "../sncqxbpm.st"
				printf("%s\n", "user re-initialized");
# line 415 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 415 "../sncqxbpm.st"
			;
		}
		return;
	case 3:
		{
# line 420 "../sncqxbpm.st"
			sprintf(debug_str, "gain changed to %s (%d)", gainStr[gain], gain);
# line 421 "../sncqxbpm.st"
			if (debug_flag >= 5)
			{
# line 421 "../sncqxbpm.st"
				printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 421, SNLtaskName, 5);
# line 421 "../sncqxbpm.st"
				;
# line 421 "../sncqxbpm.st"
				printf("%s\n", debug_str);
# line 421 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 421 "../sncqxbpm.st"
			;
			{
# line 422 "../sncqxbpm.st"
				sprintf(bpm_command, ":CONF%d:CURR:RANG %d", bpm_address, gain + 1, 0, 0);
# line 422 "../sncqxbpm.st"
				sprintf(debug_str, "BPM_COMM: <%s> (%d) <-- <%s>", s_aout, 1, bpm_command);
# line 422 "../sncqxbpm.st"
				if (debug_flag >= 15)
				{
# line 422 "../sncqxbpm.st"
					printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 422, SNLtaskName, 15);
# line 422 "../sncqxbpm.st"
					;
# line 422 "../sncqxbpm.st"
					printf("%s\n", debug_str);
# line 422 "../sncqxbpm.st"
					epicsThreadSleep(0.01);
				}
# line 422 "../sncqxbpm.st"
				;
# line 422 "../sncqxbpm.st"
				if (s_tmod != 1)
				{
# line 422 "../sncqxbpm.st"
					s_tmod = (1);
# line 422 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 16/*s_tmod*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 422 "../sncqxbpm.st"
				;
				{
# line 422 "../sncqxbpm.st"
					epicsThreadSleep(1 / 60.);
				}
# line 422 "../sncqxbpm.st"
				;
# line 422 "../sncqxbpm.st"
				if (1 == 1)
				{
# line 422 "../sncqxbpm.st"
					if (strcmp(s_aout, bpm_command))
					{
						{
# line 422 "../sncqxbpm.st"
							strcpy(s_aout, bpm_command);
# line 422 "../sncqxbpm.st"
							seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 422 "../sncqxbpm.st"
							epicsThreadSleep(0.01);
						}
# line 422 "../sncqxbpm.st"
						;
						{
# line 422 "../sncqxbpm.st"
							epicsThreadSleep(1 / 60.);
						}
# line 422 "../sncqxbpm.st"
						;
					}
					else
					{
						{
# line 422 "../sncqxbpm.st"
							s_proc = (1);
# line 422 "../sncqxbpm.st"
							seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
						}
# line 422 "../sncqxbpm.st"
						;
						{
# line 422 "../sncqxbpm.st"
							epicsThreadSleep(1 / 60.);
						}
# line 422 "../sncqxbpm.st"
						;
					}
				}
				else
				{
# line 422 "../sncqxbpm.st"
					strcpy(bpm_response, "");
# line 422 "../sncqxbpm.st"
					for (retry = 0; retry < 3; retry++)
					{
# line 422 "../sncqxbpm.st"
						if (strcmp(s_aout, bpm_command))
						{
							{
# line 422 "../sncqxbpm.st"
								strcpy(s_aout, bpm_command);
# line 422 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 422 "../sncqxbpm.st"
								epicsThreadSleep(0.01);
							}
# line 422 "../sncqxbpm.st"
							;
							{
# line 422 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 422 "../sncqxbpm.st"
							;
						}
						else
						{
							{
# line 422 "../sncqxbpm.st"
								s_proc = (1);
# line 422 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
							}
# line 422 "../sncqxbpm.st"
							;
							{
# line 422 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 422 "../sncqxbpm.st"
							;
						}
# line 422 "../sncqxbpm.st"
						for (i = 0; i < 0.25; i++)
						{
							{
# line 422 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 422 "../sncqxbpm.st"
							;
# line 422 "../sncqxbpm.st"
							if (seq_efTest(seqg_env, s_ainp_mon))
								break;
						}
# line 422 "../sncqxbpm.st"
						if (!s_sevr && seq_efTest(seqg_env, s_ainp_mon))
						{
# line 422 "../sncqxbpm.st"
							sprintf(debug_str, "BPM_COMM: <%s> ==> <%s>", s_aout, s_ainp);
# line 422 "../sncqxbpm.st"
							if (debug_flag >= 10)
							{
# line 422 "../sncqxbpm.st"
								printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 422, SNLtaskName, 10);
# line 422 "../sncqxbpm.st"
								;
# line 422 "../sncqxbpm.st"
								printf("%s\n", debug_str);
# line 422 "../sncqxbpm.st"
								epicsThreadSleep(0.01);
							}
# line 422 "../sncqxbpm.st"
							;
# line 422 "../sncqxbpm.st"
							strcpy(bpm_response, s_ainp + 1);
							break;
						}
					}
				}
			}
# line 422 "../sncqxbpm.st"
			;
# line 427 "../sncqxbpm.st"
			updateDelay = 3;
# line 428 "../sncqxbpm.st"
			updateDelay = 0.01;
		}
		return;
	case 4:
		{
# line 434 "../sncqxbpm.st"
			if (buflen < buflen_lo)
			{
# line 434 "../sncqxbpm.st"
				buflen = (buflen_lo);
# line 434 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 40/*buflen*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 434 "../sncqxbpm.st"
			;
# line 435 "../sncqxbpm.st"
			if (buflen > buflen_hi)
			{
# line 435 "../sncqxbpm.st"
				buflen = (buflen_hi);
# line 435 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 40/*buflen*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 435 "../sncqxbpm.st"
			;
			{
# line 436 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 436 "../sncqxbpm.st"
			;
# line 437 "../sncqxbpm.st"
			seq_efClear(seqg_env, buflen_mon);
# line 438 "../sncqxbpm.st"
			if (signal_mode == 0)
			{
# line 440 "../sncqxbpm.st"
				sprintf(debug_str, "gain changed to %s (%d)", signal_modeStr[signal_mode], signal_mode);
# line 441 "../sncqxbpm.st"
				if (debug_flag >= 5)
				{
# line 441 "../sncqxbpm.st"
					printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 441, SNLtaskName, 5);
# line 441 "../sncqxbpm.st"
					;
# line 441 "../sncqxbpm.st"
					printf("%s\n", debug_str);
# line 441 "../sncqxbpm.st"
					epicsThreadSleep(0.01);
				}
# line 441 "../sncqxbpm.st"
				;
				{
# line 442 "../sncqxbpm.st"
					sprintf(bpm_command, ":CONF%d:SINGLE", bpm_address, 0, 0, 0);
# line 442 "../sncqxbpm.st"
					sprintf(debug_str, "BPM_COMM: <%s> (%d) <-- <%s>", s_aout, 1, bpm_command);
# line 442 "../sncqxbpm.st"
					if (debug_flag >= 15)
					{
# line 442 "../sncqxbpm.st"
						printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 442, SNLtaskName, 15);
# line 442 "../sncqxbpm.st"
						;
# line 442 "../sncqxbpm.st"
						printf("%s\n", debug_str);
# line 442 "../sncqxbpm.st"
						epicsThreadSleep(0.01);
					}
# line 442 "../sncqxbpm.st"
					;
# line 442 "../sncqxbpm.st"
					if (s_tmod != 1)
					{
# line 442 "../sncqxbpm.st"
						s_tmod = (1);
# line 442 "../sncqxbpm.st"
						seq_pvPutTmo(seqg_env, 16/*s_tmod*/, SYNC, DEFAULT_TIMEOUT);
					}
# line 442 "../sncqxbpm.st"
					;
					{
# line 442 "../sncqxbpm.st"
						epicsThreadSleep(1 / 60.);
					}
# line 442 "../sncqxbpm.st"
					;
# line 442 "../sncqxbpm.st"
					if (1 == 1)
					{
# line 442 "../sncqxbpm.st"
						if (strcmp(s_aout, bpm_command))
						{
							{
# line 442 "../sncqxbpm.st"
								strcpy(s_aout, bpm_command);
# line 442 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 442 "../sncqxbpm.st"
								epicsThreadSleep(0.01);
							}
# line 442 "../sncqxbpm.st"
							;
							{
# line 442 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 442 "../sncqxbpm.st"
							;
						}
						else
						{
							{
# line 442 "../sncqxbpm.st"
								s_proc = (1);
# line 442 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
							}
# line 442 "../sncqxbpm.st"
							;
							{
# line 442 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 442 "../sncqxbpm.st"
							;
						}
					}
					else
					{
# line 442 "../sncqxbpm.st"
						strcpy(bpm_response, "");
# line 442 "../sncqxbpm.st"
						for (retry = 0; retry < 3; retry++)
						{
# line 442 "../sncqxbpm.st"
							if (strcmp(s_aout, bpm_command))
							{
								{
# line 442 "../sncqxbpm.st"
									strcpy(s_aout, bpm_command);
# line 442 "../sncqxbpm.st"
									seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 442 "../sncqxbpm.st"
									epicsThreadSleep(0.01);
								}
# line 442 "../sncqxbpm.st"
								;
								{
# line 442 "../sncqxbpm.st"
									epicsThreadSleep(1 / 60.);
								}
# line 442 "../sncqxbpm.st"
								;
							}
							else
							{
								{
# line 442 "../sncqxbpm.st"
									s_proc = (1);
# line 442 "../sncqxbpm.st"
									seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
								}
# line 442 "../sncqxbpm.st"
								;
								{
# line 442 "../sncqxbpm.st"
									epicsThreadSleep(1 / 60.);
								}
# line 442 "../sncqxbpm.st"
								;
							}
# line 442 "../sncqxbpm.st"
							for (i = 0; i < 0.25; i++)
							{
								{
# line 442 "../sncqxbpm.st"
									epicsThreadSleep(1 / 60.);
								}
# line 442 "../sncqxbpm.st"
								;
# line 442 "../sncqxbpm.st"
								if (seq_efTest(seqg_env, s_ainp_mon))
									break;
							}
# line 442 "../sncqxbpm.st"
							if (!s_sevr && seq_efTest(seqg_env, s_ainp_mon))
							{
# line 442 "../sncqxbpm.st"
								sprintf(debug_str, "BPM_COMM: <%s> ==> <%s>", s_aout, s_ainp);
# line 442 "../sncqxbpm.st"
								if (debug_flag >= 10)
								{
# line 442 "../sncqxbpm.st"
									printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 442, SNLtaskName, 10);
# line 442 "../sncqxbpm.st"
									;
# line 442 "../sncqxbpm.st"
									printf("%s\n", debug_str);
# line 442 "../sncqxbpm.st"
									epicsThreadSleep(0.01);
								}
# line 442 "../sncqxbpm.st"
								;
# line 442 "../sncqxbpm.st"
								strcpy(bpm_response, s_ainp + 1);
								break;
							}
						}
					}
				}
# line 442 "../sncqxbpm.st"
				;
			}
# line 444 "../sncqxbpm.st"
			if (signal_mode == 1)
			{
# line 446 "../sncqxbpm.st"
				sprintf(debug_str, "gain changed to %s (%d) with buffer length = %d", signal_modeStr[signal_mode], signal_mode, buflen);
# line 447 "../sncqxbpm.st"
				if (debug_flag >= 5)
				{
# line 447 "../sncqxbpm.st"
					printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 447, SNLtaskName, 5);
# line 447 "../sncqxbpm.st"
					;
# line 447 "../sncqxbpm.st"
					printf("%s\n", debug_str);
# line 447 "../sncqxbpm.st"
					epicsThreadSleep(0.01);
				}
# line 447 "../sncqxbpm.st"
				;
				{
# line 448 "../sncqxbpm.st"
					sprintf(bpm_command, ":CONF%d:AVGCURR %d", bpm_address, buflen, 0, 0);
# line 448 "../sncqxbpm.st"
					sprintf(debug_str, "BPM_COMM: <%s> (%d) <-- <%s>", s_aout, 1, bpm_command);
# line 448 "../sncqxbpm.st"
					if (debug_flag >= 15)
					{
# line 448 "../sncqxbpm.st"
						printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 448, SNLtaskName, 15);
# line 448 "../sncqxbpm.st"
						;
# line 448 "../sncqxbpm.st"
						printf("%s\n", debug_str);
# line 448 "../sncqxbpm.st"
						epicsThreadSleep(0.01);
					}
# line 448 "../sncqxbpm.st"
					;
# line 448 "../sncqxbpm.st"
					if (s_tmod != 1)
					{
# line 448 "../sncqxbpm.st"
						s_tmod = (1);
# line 448 "../sncqxbpm.st"
						seq_pvPutTmo(seqg_env, 16/*s_tmod*/, SYNC, DEFAULT_TIMEOUT);
					}
# line 448 "../sncqxbpm.st"
					;
					{
# line 448 "../sncqxbpm.st"
						epicsThreadSleep(1 / 60.);
					}
# line 448 "../sncqxbpm.st"
					;
# line 448 "../sncqxbpm.st"
					if (1 == 1)
					{
# line 448 "../sncqxbpm.st"
						if (strcmp(s_aout, bpm_command))
						{
							{
# line 448 "../sncqxbpm.st"
								strcpy(s_aout, bpm_command);
# line 448 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 448 "../sncqxbpm.st"
								epicsThreadSleep(0.01);
							}
# line 448 "../sncqxbpm.st"
							;
							{
# line 448 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 448 "../sncqxbpm.st"
							;
						}
						else
						{
							{
# line 448 "../sncqxbpm.st"
								s_proc = (1);
# line 448 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
							}
# line 448 "../sncqxbpm.st"
							;
							{
# line 448 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 448 "../sncqxbpm.st"
							;
						}
					}
					else
					{
# line 448 "../sncqxbpm.st"
						strcpy(bpm_response, "");
# line 448 "../sncqxbpm.st"
						for (retry = 0; retry < 3; retry++)
						{
# line 448 "../sncqxbpm.st"
							if (strcmp(s_aout, bpm_command))
							{
								{
# line 448 "../sncqxbpm.st"
									strcpy(s_aout, bpm_command);
# line 448 "../sncqxbpm.st"
									seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 448 "../sncqxbpm.st"
									epicsThreadSleep(0.01);
								}
# line 448 "../sncqxbpm.st"
								;
								{
# line 448 "../sncqxbpm.st"
									epicsThreadSleep(1 / 60.);
								}
# line 448 "../sncqxbpm.st"
								;
							}
							else
							{
								{
# line 448 "../sncqxbpm.st"
									s_proc = (1);
# line 448 "../sncqxbpm.st"
									seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
								}
# line 448 "../sncqxbpm.st"
								;
								{
# line 448 "../sncqxbpm.st"
									epicsThreadSleep(1 / 60.);
								}
# line 448 "../sncqxbpm.st"
								;
							}
# line 448 "../sncqxbpm.st"
							for (i = 0; i < 0.25; i++)
							{
								{
# line 448 "../sncqxbpm.st"
									epicsThreadSleep(1 / 60.);
								}
# line 448 "../sncqxbpm.st"
								;
# line 448 "../sncqxbpm.st"
								if (seq_efTest(seqg_env, s_ainp_mon))
									break;
							}
# line 448 "../sncqxbpm.st"
							if (!s_sevr && seq_efTest(seqg_env, s_ainp_mon))
							{
# line 448 "../sncqxbpm.st"
								sprintf(debug_str, "BPM_COMM: <%s> ==> <%s>", s_aout, s_ainp);
# line 448 "../sncqxbpm.st"
								if (debug_flag >= 10)
								{
# line 448 "../sncqxbpm.st"
									printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 448, SNLtaskName, 10);
# line 448 "../sncqxbpm.st"
									;
# line 448 "../sncqxbpm.st"
									printf("%s\n", debug_str);
# line 448 "../sncqxbpm.st"
									epicsThreadSleep(0.01);
								}
# line 448 "../sncqxbpm.st"
								;
# line 448 "../sncqxbpm.st"
								strcpy(bpm_response, s_ainp + 1);
								break;
							}
						}
					}
				}
# line 448 "../sncqxbpm.st"
				;
			}
# line 450 "../sncqxbpm.st"
			if (signal_mode == 2)
			{
# line 452 "../sncqxbpm.st"
				sprintf(debug_str, "gain changed to %s (%d) with buffer length = %d", signal_modeStr[signal_mode], signal_mode, buflen);
# line 453 "../sncqxbpm.st"
				if (debug_flag >= 5)
				{
# line 453 "../sncqxbpm.st"
					printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 453, SNLtaskName, 5);
# line 453 "../sncqxbpm.st"
					;
# line 453 "../sncqxbpm.st"
					printf("%s\n", debug_str);
# line 453 "../sncqxbpm.st"
					epicsThreadSleep(0.01);
				}
# line 453 "../sncqxbpm.st"
				;
				{
# line 454 "../sncqxbpm.st"
					sprintf(bpm_command, ":CONF%d:WDWCURR %d", bpm_address, buflen, 0, 0);
# line 454 "../sncqxbpm.st"
					sprintf(debug_str, "BPM_COMM: <%s> (%d) <-- <%s>", s_aout, 1, bpm_command);
# line 454 "../sncqxbpm.st"
					if (debug_flag >= 15)
					{
# line 454 "../sncqxbpm.st"
						printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 454, SNLtaskName, 15);
# line 454 "../sncqxbpm.st"
						;
# line 454 "../sncqxbpm.st"
						printf("%s\n", debug_str);
# line 454 "../sncqxbpm.st"
						epicsThreadSleep(0.01);
					}
# line 454 "../sncqxbpm.st"
					;
# line 454 "../sncqxbpm.st"
					if (s_tmod != 1)
					{
# line 454 "../sncqxbpm.st"
						s_tmod = (1);
# line 454 "../sncqxbpm.st"
						seq_pvPutTmo(seqg_env, 16/*s_tmod*/, SYNC, DEFAULT_TIMEOUT);
					}
# line 454 "../sncqxbpm.st"
					;
					{
# line 454 "../sncqxbpm.st"
						epicsThreadSleep(1 / 60.);
					}
# line 454 "../sncqxbpm.st"
					;
# line 454 "../sncqxbpm.st"
					if (1 == 1)
					{
# line 454 "../sncqxbpm.st"
						if (strcmp(s_aout, bpm_command))
						{
							{
# line 454 "../sncqxbpm.st"
								strcpy(s_aout, bpm_command);
# line 454 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 454 "../sncqxbpm.st"
								epicsThreadSleep(0.01);
							}
# line 454 "../sncqxbpm.st"
							;
							{
# line 454 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 454 "../sncqxbpm.st"
							;
						}
						else
						{
							{
# line 454 "../sncqxbpm.st"
								s_proc = (1);
# line 454 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
							}
# line 454 "../sncqxbpm.st"
							;
							{
# line 454 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 454 "../sncqxbpm.st"
							;
						}
					}
					else
					{
# line 454 "../sncqxbpm.st"
						strcpy(bpm_response, "");
# line 454 "../sncqxbpm.st"
						for (retry = 0; retry < 3; retry++)
						{
# line 454 "../sncqxbpm.st"
							if (strcmp(s_aout, bpm_command))
							{
								{
# line 454 "../sncqxbpm.st"
									strcpy(s_aout, bpm_command);
# line 454 "../sncqxbpm.st"
									seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 454 "../sncqxbpm.st"
									epicsThreadSleep(0.01);
								}
# line 454 "../sncqxbpm.st"
								;
								{
# line 454 "../sncqxbpm.st"
									epicsThreadSleep(1 / 60.);
								}
# line 454 "../sncqxbpm.st"
								;
							}
							else
							{
								{
# line 454 "../sncqxbpm.st"
									s_proc = (1);
# line 454 "../sncqxbpm.st"
									seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
								}
# line 454 "../sncqxbpm.st"
								;
								{
# line 454 "../sncqxbpm.st"
									epicsThreadSleep(1 / 60.);
								}
# line 454 "../sncqxbpm.st"
								;
							}
# line 454 "../sncqxbpm.st"
							for (i = 0; i < 0.25; i++)
							{
								{
# line 454 "../sncqxbpm.st"
									epicsThreadSleep(1 / 60.);
								}
# line 454 "../sncqxbpm.st"
								;
# line 454 "../sncqxbpm.st"
								if (seq_efTest(seqg_env, s_ainp_mon))
									break;
							}
# line 454 "../sncqxbpm.st"
							if (!s_sevr && seq_efTest(seqg_env, s_ainp_mon))
							{
# line 454 "../sncqxbpm.st"
								sprintf(debug_str, "BPM_COMM: <%s> ==> <%s>", s_aout, s_ainp);
# line 454 "../sncqxbpm.st"
								if (debug_flag >= 10)
								{
# line 454 "../sncqxbpm.st"
									printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 454, SNLtaskName, 10);
# line 454 "../sncqxbpm.st"
									;
# line 454 "../sncqxbpm.st"
									printf("%s\n", debug_str);
# line 454 "../sncqxbpm.st"
									epicsThreadSleep(0.01);
								}
# line 454 "../sncqxbpm.st"
								;
# line 454 "../sncqxbpm.st"
								strcpy(bpm_response, s_ainp + 1);
								break;
							}
						}
					}
				}
# line 454 "../sncqxbpm.st"
				;
			}
		}
		return;
	case 5:
		{
# line 459 "../sncqxbpm.st"
			if (period_s < period_s_LOPR)
			{
# line 459 "../sncqxbpm.st"
				period_s = (period_s_LOPR);
# line 459 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 44/*period_s*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 459 "../sncqxbpm.st"
			;
# line 460 "../sncqxbpm.st"
			if (period_s > period_s_HOPR)
			{
# line 460 "../sncqxbpm.st"
				period_s = (period_s_HOPR);
# line 460 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 44/*period_s*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 460 "../sncqxbpm.st"
			;
# line 461 "../sncqxbpm.st"
			sprintf(debug_str, "checking update period: %g s", period_s);
# line 462 "../sncqxbpm.st"
			if (debug_flag >= 5)
			{
# line 462 "../sncqxbpm.st"
				printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 462, SNLtaskName, 5);
# line 462 "../sncqxbpm.st"
				;
# line 462 "../sncqxbpm.st"
				printf("%s\n", debug_str);
# line 462 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 462 "../sncqxbpm.st"
			;
		}
		return;
	case 6:
		{
			{
# line 467 "../sncqxbpm.st"
				sprintf(bpm_command, ":READ%d:CURRALL?", bpm_address, 0, 0, 0);
# line 467 "../sncqxbpm.st"
				sprintf(debug_str, "BPM_COMM: <%s> (%d) <-- <%s>", s_aout, 0, bpm_command);
# line 467 "../sncqxbpm.st"
				if (debug_flag >= 15)
				{
# line 467 "../sncqxbpm.st"
					printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 467, SNLtaskName, 15);
# line 467 "../sncqxbpm.st"
					;
# line 467 "../sncqxbpm.st"
					printf("%s\n", debug_str);
# line 467 "../sncqxbpm.st"
					epicsThreadSleep(0.01);
				}
# line 467 "../sncqxbpm.st"
				;
# line 467 "../sncqxbpm.st"
				if (s_tmod != 0)
				{
# line 467 "../sncqxbpm.st"
					s_tmod = (0);
# line 467 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 16/*s_tmod*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 467 "../sncqxbpm.st"
				;
				{
# line 467 "../sncqxbpm.st"
					epicsThreadSleep(1 / 60.);
				}
# line 467 "../sncqxbpm.st"
				;
# line 467 "../sncqxbpm.st"
				if (0 == 1)
				{
# line 467 "../sncqxbpm.st"
					if (strcmp(s_aout, bpm_command))
					{
						{
# line 467 "../sncqxbpm.st"
							strcpy(s_aout, bpm_command);
# line 467 "../sncqxbpm.st"
							seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 467 "../sncqxbpm.st"
							epicsThreadSleep(0.01);
						}
# line 467 "../sncqxbpm.st"
						;
						{
# line 467 "../sncqxbpm.st"
							epicsThreadSleep(1 / 60.);
						}
# line 467 "../sncqxbpm.st"
						;
					}
					else
					{
						{
# line 467 "../sncqxbpm.st"
							s_proc = (1);
# line 467 "../sncqxbpm.st"
							seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
						}
# line 467 "../sncqxbpm.st"
						;
						{
# line 467 "../sncqxbpm.st"
							epicsThreadSleep(1 / 60.);
						}
# line 467 "../sncqxbpm.st"
						;
					}
				}
				else
				{
# line 467 "../sncqxbpm.st"
					strcpy(bpm_response, "");
# line 467 "../sncqxbpm.st"
					for (retry = 0; retry < 3; retry++)
					{
# line 467 "../sncqxbpm.st"
						if (strcmp(s_aout, bpm_command))
						{
							{
# line 467 "../sncqxbpm.st"
								strcpy(s_aout, bpm_command);
# line 467 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 1/*s_aout*/, SYNC, DEFAULT_TIMEOUT);
# line 467 "../sncqxbpm.st"
								epicsThreadSleep(0.01);
							}
# line 467 "../sncqxbpm.st"
							;
							{
# line 467 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 467 "../sncqxbpm.st"
							;
						}
						else
						{
							{
# line 467 "../sncqxbpm.st"
								s_proc = (1);
# line 467 "../sncqxbpm.st"
								seq_pvPutTmo(seqg_env, 11/*s_proc*/, SYNC, DEFAULT_TIMEOUT);
							}
# line 467 "../sncqxbpm.st"
							;
							{
# line 467 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 467 "../sncqxbpm.st"
							;
						}
# line 467 "../sncqxbpm.st"
						for (i = 0; i < 0.25; i++)
						{
							{
# line 467 "../sncqxbpm.st"
								epicsThreadSleep(1 / 60.);
							}
# line 467 "../sncqxbpm.st"
							;
# line 467 "../sncqxbpm.st"
							if (seq_efTest(seqg_env, s_ainp_mon))
								break;
						}
# line 467 "../sncqxbpm.st"
						if (!s_sevr && seq_efTest(seqg_env, s_ainp_mon))
						{
# line 467 "../sncqxbpm.st"
							sprintf(debug_str, "BPM_COMM: <%s> ==> <%s>", s_aout, s_ainp);
# line 467 "../sncqxbpm.st"
							if (debug_flag >= 10)
							{
# line 467 "../sncqxbpm.st"
								printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 467, SNLtaskName, 10);
# line 467 "../sncqxbpm.st"
								;
# line 467 "../sncqxbpm.st"
								printf("%s\n", debug_str);
# line 467 "../sncqxbpm.st"
								epicsThreadSleep(0.01);
							}
# line 467 "../sncqxbpm.st"
							;
# line 467 "../sncqxbpm.st"
							strcpy(bpm_response, s_ainp + 1);
							break;
						}
					}
				}
			}
# line 467 "../sncqxbpm.st"
			;
# line 468 "../sncqxbpm.st"
			sprintf(debug_str, "serial.SEVR: %d", s_sevr);
# line 469 "../sncqxbpm.st"
			if (debug_flag >= 5)
			{
# line 469 "../sncqxbpm.st"
				printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 469, SNLtaskName, 5);
# line 469 "../sncqxbpm.st"
				;
# line 469 "../sncqxbpm.st"
				printf("%s\n", debug_str);
# line 469 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 469 "../sncqxbpm.st"
			;
# line 470 "../sncqxbpm.st"
			if (!s_sevr)
			{
# line 471 "../sncqxbpm.st"
				sscanf(bpm_response, "%u%u%u%u", &raw_a, &raw_b, &raw_c, &raw_d);
# line 472 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 32/*raw_a*/, DEFAULT, DEFAULT_TIMEOUT);
# line 473 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 33/*raw_b*/, DEFAULT, DEFAULT_TIMEOUT);
# line 474 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 34/*raw_c*/, DEFAULT, DEFAULT_TIMEOUT);
# line 475 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 35/*raw_d*/, DEFAULT, DEFAULT_TIMEOUT);
# line 477 "../sncqxbpm.st"
				sprintf(debug_str, "bpm_command=<%s>  bpm_response=<%s>", bpm_command, bpm_response);
# line 478 "../sncqxbpm.st"
				if (debug_flag >= 12)
				{
# line 478 "../sncqxbpm.st"
					printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 478, SNLtaskName, 12);
# line 478 "../sncqxbpm.st"
					;
# line 478 "../sncqxbpm.st"
					printf("%s\n", debug_str);
# line 478 "../sncqxbpm.st"
					epicsThreadSleep(0.01);
				}
# line 478 "../sncqxbpm.st"
				;
# line 480 "../sncqxbpm.st"
				sprintf(debug_str, "raw: a=%d  b=%d  c=%d  d=%d", raw_a, raw_b, raw_c, raw_d);
# line 481 "../sncqxbpm.st"
				if (debug_flag >= 12)
				{
# line 481 "../sncqxbpm.st"
					printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 481, SNLtaskName, 12);
# line 481 "../sncqxbpm.st"
					;
# line 481 "../sncqxbpm.st"
					printf("%s\n", debug_str);
# line 481 "../sncqxbpm.st"
					epicsThreadSleep(0.01);
				}
# line 481 "../sncqxbpm.st"
				;
				{
# line 482 "../sncqxbpm.st"
					current_a = (gainTrim[((gain) * 4 + (1) - 1)] * (raw_a - offset[((gain) * 4 + (1) - 1)]));
# line 482 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 28/*current_a*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 482 "../sncqxbpm.st"
				;
				{
# line 483 "../sncqxbpm.st"
					current_b = (gainTrim[((gain) * 4 + (2) - 1)] * (raw_b - offset[((gain) * 4 + (2) - 1)]));
# line 483 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 29/*current_b*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 483 "../sncqxbpm.st"
				;
				{
# line 484 "../sncqxbpm.st"
					current_c = (gainTrim[((gain) * 4 + (3) - 1)] * (raw_c - offset[((gain) * 4 + (3) - 1)]));
# line 484 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 30/*current_c*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 484 "../sncqxbpm.st"
				;
				{
# line 485 "../sncqxbpm.st"
					current_d = (gainTrim[((gain) * 4 + (4) - 1)] * (raw_d - offset[((gain) * 4 + (4) - 1)]));
# line 485 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 31/*current_d*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 485 "../sncqxbpm.st"
				;
				{
# line 486 "../sncqxbpm.st"
					current_total = (current_a + current_b + current_c + current_d);
# line 486 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 27/*current_total*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 486 "../sncqxbpm.st"
				;
				{
# line 493 "../sncqxbpm.st"
					pos_x = (gx * (current_b - current_d) / (current_b + current_d));
# line 493 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 25/*pos_x*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 493 "../sncqxbpm.st"
				;
				{
# line 494 "../sncqxbpm.st"
					pos_y = (gy * (current_a - current_c) / (current_a + current_c));
# line 494 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 26/*pos_y*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 494 "../sncqxbpm.st"
				;
				{
# line 495 "../sncqxbpm.st"
					current_low = ((raw_a < current_low_raw) && (raw_b < current_low_raw) && (raw_c < current_low_raw) && (raw_d < current_low_raw));
# line 495 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 37/*current_low*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 501 "../sncqxbpm.st"
				;
				{
# line 502 "../sncqxbpm.st"
					current_ok = ((raw_a >= current_low_raw) && (raw_b >= current_low_raw) && (raw_c >= current_low_raw) && (raw_d >= current_low_raw));
# line 502 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 38/*current_ok*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 508 "../sncqxbpm.st"
				;
			}
		}
		return;
	}
}

/****** Code for state "startup" in state set "sncqxbpm_tools" ******/

/* Event function for state "startup" in state set "sncqxbpm_tools" */
static seqBool seqg_event_sncqxbpm_tools_1_startup(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 524 "../sncqxbpm.st"
	if (seq_efTest(seqg_env, started))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "startup" in state set "sncqxbpm_tools" */
static void seqg_action_sncqxbpm_tools_1_startup(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "idle" in state set "sncqxbpm_tools" ******/

/* Event function for state "idle" in state set "sncqxbpm_tools" */
static seqBool seqg_event_sncqxbpm_tools_1_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 530 "../sncqxbpm.st"
	if (set_offsets)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 559 "../sncqxbpm.st"
	if (set_defaults)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "sncqxbpm_tools" */
static void seqg_action_sncqxbpm_tools_1_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 531 "../sncqxbpm.st"
			oldGain = gain;
			{
# line 532 "../sncqxbpm.st"
				epicsThreadSleep(60 / 60.);
			}
# line 532 "../sncqxbpm.st"
			;
# line 533 "../sncqxbpm.st"
			for (newGain = 0; newGain < 6; newGain++)
			{
# line 534 "../sncqxbpm.st"
				if (!set_offsets)
					break;
				{
# line 535 "../sncqxbpm.st"
					gain = (newGain);
# line 535 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 43/*gain*/, SYNC, DEFAULT_TIMEOUT);
				}
# line 535 "../sncqxbpm.st"
				;
# line 536 "../sncqxbpm.st"
				if (!set_offsets)
					break;
# line 537 "../sncqxbpm.st"
				epicsThreadSleep(settling);
# line 538 "../sncqxbpm.st"
				if (!set_offsets)
					break;
# line 539 "../sncqxbpm.st"
				sprintf(debug_str, "new gain=%d", gain);
# line 540 "../sncqxbpm.st"
				if (debug_flag >= 18)
				{
# line 540 "../sncqxbpm.st"
					printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 540, SNLtaskName, 18);
# line 540 "../sncqxbpm.st"
					;
# line 540 "../sncqxbpm.st"
					printf("%s\n", debug_str);
# line 540 "../sncqxbpm.st"
					epicsThreadSleep(0.01);
				}
# line 540 "../sncqxbpm.st"
				;
				{
# line 541 "../sncqxbpm.st"
					offset[((gain) * 4 + (1) - 1)] = (raw_a);
# line 541 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 85/*offset*/ + (CH_ID)(((gain) * 4 + (1) - 1)), SYNC, DEFAULT_TIMEOUT);
				}
# line 541 "../sncqxbpm.st"
				;
				{
# line 542 "../sncqxbpm.st"
					offset[((gain) * 4 + (2) - 1)] = (raw_b);
# line 542 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 85/*offset*/ + (CH_ID)(((gain) * 4 + (2) - 1)), SYNC, DEFAULT_TIMEOUT);
				}
# line 542 "../sncqxbpm.st"
				;
				{
# line 543 "../sncqxbpm.st"
					offset[((gain) * 4 + (3) - 1)] = (raw_c);
# line 543 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 85/*offset*/ + (CH_ID)(((gain) * 4 + (3) - 1)), SYNC, DEFAULT_TIMEOUT);
				}
# line 543 "../sncqxbpm.st"
				;
				{
# line 544 "../sncqxbpm.st"
					offset[((gain) * 4 + (4) - 1)] = (raw_d);
# line 544 "../sncqxbpm.st"
					seq_pvPutTmo(seqg_env, 85/*offset*/ + (CH_ID)(((gain) * 4 + (4) - 1)), SYNC, DEFAULT_TIMEOUT);
				}
# line 544 "../sncqxbpm.st"
				;
# line 545 "../sncqxbpm.st"
				for (channel = 1; channel <= 4; channel++)
				{
# line 548 "../sncqxbpm.st"
					sprintf(debug_str, "  offset[%d]=%d", channel, offset[((gain) * 4 + (channel) - 1)]);
# line 549 "../sncqxbpm.st"
					if (debug_flag >= 19)
					{
# line 549 "../sncqxbpm.st"
						printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 549, SNLtaskName, 19);
# line 549 "../sncqxbpm.st"
						;
# line 549 "../sncqxbpm.st"
						printf("%s\n", debug_str);
# line 549 "../sncqxbpm.st"
						epicsThreadSleep(0.01);
					}
# line 549 "../sncqxbpm.st"
					;
				}
			}
			{
# line 552 "../sncqxbpm.st"
				gain = (oldGain);
# line 552 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 43/*gain*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 552 "../sncqxbpm.st"
			;
			{
# line 553 "../sncqxbpm.st"
				set_offsets = (0);
# line 553 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 49/*set_offsets*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 553 "../sncqxbpm.st"
			;
			{
# line 554 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 554 "../sncqxbpm.st"
			;
# line 555 "../sncqxbpm.st"
			sprintf(debug_str, "restored to previous gain #%d", gain);
# line 556 "../sncqxbpm.st"
			if (debug_flag >= 18)
			{
# line 556 "../sncqxbpm.st"
				printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 556, SNLtaskName, 18);
# line 556 "../sncqxbpm.st"
				;
# line 556 "../sncqxbpm.st"
				printf("%s\n", debug_str);
# line 556 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 556 "../sncqxbpm.st"
			;
		}
		return;
	case 1:
		{
# line 560 "../sncqxbpm.st"
			if (debug_flag >= 18)
			{
# line 560 "../sncqxbpm.st"
				printf("<%s,%d,%s,%d> ", "../sncqxbpm.st", 560, SNLtaskName, 18);
# line 560 "../sncqxbpm.st"
				;
# line 560 "../sncqxbpm.st"
				printf("%s\n", "restore default calibrations");
# line 560 "../sncqxbpm.st"
				epicsThreadSleep(0.01);
			}
# line 560 "../sncqxbpm.st"
			;
			{
# line 561 "../sncqxbpm.st"
				signal_mode = (2);
# line 561 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 39/*signal_mode*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 561 "../sncqxbpm.st"
			;
			{
# line 562 "../sncqxbpm.st"
				buflen = (30);
# line 562 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 40/*buflen*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 562 "../sncqxbpm.st"
			;
			{
# line 563 "../sncqxbpm.st"
				current_low_raw = (1000);
# line 563 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 36/*current_low_raw*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 563 "../sncqxbpm.st"
			;
			{
# line 564 "../sncqxbpm.st"
				period_s = (0.1);
# line 564 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 44/*period_s*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 564 "../sncqxbpm.st"
			;
			{
# line 565 "../sncqxbpm.st"
				gx = (4.5);
# line 565 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 47/*gx*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 565 "../sncqxbpm.st"
			;
			{
# line 566 "../sncqxbpm.st"
				gy = (4.5);
# line 566 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 48/*gy*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 566 "../sncqxbpm.st"
			;
			{
# line 567 "../sncqxbpm.st"
				settling = (2.5);
# line 567 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 51/*settling*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 567 "../sncqxbpm.st"
			;
# line 568 "../sncqxbpm.st"
			for (newGain = 0; newGain < 6; newGain++)
			{
# line 569 "../sncqxbpm.st"
				if (newGain == 0)
				{
# line 569 "../sncqxbpm.st"
					factor = 350e-9;
				}
# line 570 "../sncqxbpm.st"
				if (newGain == 1)
				{
# line 570 "../sncqxbpm.st"
					factor = 700e-9;
				}
# line 571 "../sncqxbpm.st"
				if (newGain == 2)
				{
# line 571 "../sncqxbpm.st"
					factor = 1400e-9;
				}
# line 572 "../sncqxbpm.st"
				if (newGain == 3)
				{
# line 572 "../sncqxbpm.st"
					factor = 7e-6;
				}
# line 573 "../sncqxbpm.st"
				if (newGain == 4)
				{
# line 573 "../sncqxbpm.st"
					factor = 70e-6;
				}
# line 574 "../sncqxbpm.st"
				if (newGain == 5)
				{
# line 574 "../sncqxbpm.st"
					factor = 700e-6;
				}
# line 575 "../sncqxbpm.st"
				factor /= 10;
# line 576 "../sncqxbpm.st"
				factor /= 1e5;
# line 577 "../sncqxbpm.st"
				for (channel = 1; channel <= 4; channel++)
				{
					{
# line 578 "../sncqxbpm.st"
						gainTrim[((newGain) * 4 + (channel) - 1)] = (factor);
# line 578 "../sncqxbpm.st"
						seq_pvPutTmo(seqg_env, 61/*gainTrim*/ + (CH_ID)(((newGain) * 4 + (channel) - 1)), SYNC, DEFAULT_TIMEOUT);
					}
# line 578 "../sncqxbpm.st"
					;
				}
			}
			{
# line 581 "../sncqxbpm.st"
				set_defaults = (0);
# line 581 "../sncqxbpm.st"
				seq_pvPutTmo(seqg_env, 50/*set_defaults*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 581 "../sncqxbpm.st"
			;
			{
# line 582 "../sncqxbpm.st"
				epicsThreadSleep(2 / 60.);
			}
# line 582 "../sncqxbpm.st"
			;
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{S}.AINP", (size_t)&s_ainp, "s_ainp", P_STRING, 1, 7, 1, 1, 0, 0},
	{"{S}.AOUT", (size_t)&s_aout, "s_aout", P_STRING, 1, 8, 0, 0, 0, 0},
	{"{S}.BAUD", (size_t)&s_baud, "s_baud", P_SHORT, 1, 9, 0, 0, 0, 0},
	{"{S}.DBIT", (size_t)&s_dbit, "s_dbit", P_SHORT, 1, 10, 0, 0, 0, 0},
	{"{S}.FCTL", (size_t)&s_fctl, "s_fctl", P_SHORT, 1, 11, 0, 0, 0, 0},
	{"{S}.IEOS", (size_t)&s_idel, "s_idel", P_STRING, 1, 12, 0, 0, 0, 0},
	{"{S}.IFMT", (size_t)&s_ifmt, "s_ifmt", P_SHORT, 1, 13, 0, 0, 0, 0},
	{"{S}.NORD", (size_t)&s_nord, "s_nord", P_SHORT, 1, 14, 0, 1, 0, 0},
	{"{S}.NRRD", (size_t)&s_nrrd, "s_nrrd", P_SHORT, 1, 15, 0, 0, 0, 0},
	{"{S}.OEOS", (size_t)&s_odel, "s_odel", P_STRING, 1, 16, 0, 0, 0, 0},
	{"{S}.OFMT", (size_t)&s_ofmt, "s_ofmt", P_SHORT, 1, 17, 0, 0, 0, 0},
	{"{S}.PROC", (size_t)&s_proc, "s_proc", P_SHORT, 1, 18, 0, 1, 0, 0},
	{"{S}.PRTY", (size_t)&s_prty, "s_prty", P_SHORT, 1, 19, 0, 0, 0, 0},
	{"{S}.SBIT", (size_t)&s_sbit, "s_sbit", P_SHORT, 1, 20, 0, 0, 0, 0},
	{"{S}.SCAN", (size_t)&s_scan, "s_scan", P_SHORT, 1, 21, 0, 0, 0, 0},
	{"{S}.SEVR", (size_t)&s_sevr, "s_sevr", P_INT, 1, 22, 0, 1, 0, 0},
	{"{S}.TMOD", (size_t)&s_tmod, "s_tmod", P_SHORT, 1, 23, 0, 0, 0, 0},
	{"{S}.TMOT", (size_t)&s_tmot, "s_tmot", P_DOUBLE, 1, 24, 0, 1, 0, 0},
	{"{P}port", (size_t)&port, "port", P_STRING, 1, 25, 0, 0, 0, 0},
	{"{P}address", (size_t)&bpm_address, "bpm_address", P_INT, 1, 26, 0, 1, 0, 0},
	{"{P}init", (size_t)&init, "init", P_SHORT, 1, 27, 0, 1, 0, 0},
	{"{P}enable", (size_t)&enable, "enable", P_SHORT, 1, 28, 0, 1, 0, 0},
	{"{P}error", (size_t)&error, "error", P_INT, 1, 29, 0, 0, 0, 0},
	{"{P}errMsg", (size_t)&errMsg, "errMsg", P_STRING, 1, 30, 0, 0, 0, 0},
	{"{P}debug", (size_t)&debug_flag, "debug_flag", P_INT, 1, 31, 0, 1, 0, 0},
	{"{P}pos:x", (size_t)&pos_x, "pos_x", P_DOUBLE, 1, 32, 0, 0, 0, 0},
	{"{P}pos:y", (size_t)&pos_y, "pos_y", P_DOUBLE, 1, 33, 0, 0, 0, 0},
	{"{P}current:total", (size_t)&current_total, "current_total", P_DOUBLE, 1, 34, 0, 0, 0, 0},
	{"{P}current:a", (size_t)&current_a, "current_a", P_DOUBLE, 1, 35, 0, 0, 0, 0},
	{"{P}current:b", (size_t)&current_b, "current_b", P_DOUBLE, 1, 36, 0, 0, 0, 0},
	{"{P}current:c", (size_t)&current_c, "current_c", P_DOUBLE, 1, 37, 0, 0, 0, 0},
	{"{P}current:d", (size_t)&current_d, "current_d", P_DOUBLE, 1, 38, 0, 0, 0, 0},
	{"{P}current:a:raw", (size_t)&raw_a, "raw_a", P_UINT, 1, 39, 0, 0, 0, 0},
	{"{P}current:b:raw", (size_t)&raw_b, "raw_b", P_UINT, 1, 40, 0, 0, 0, 0},
	{"{P}current:c:raw", (size_t)&raw_c, "raw_c", P_UINT, 1, 41, 0, 0, 0, 0},
	{"{P}current:d:raw", (size_t)&raw_d, "raw_d", P_UINT, 1, 42, 0, 0, 0, 0},
	{"{P}current:low:raw", (size_t)&current_low_raw, "current_low_raw", P_INT, 1, 43, 0, 1, 0, 0},
	{"{P}current:low", (size_t)&current_low, "current_low", P_SHORT, 1, 44, 0, 0, 0, 0},
	{"{P}current:ok", (size_t)&current_ok, "current_ok", P_SHORT, 1, 45, 0, 0, 0, 0},
	{"{P}mode", (size_t)&signal_mode, "signal_mode", P_SHORT, 1, 46, 2, 1, 0, 0},
	{"{P}buflen", (size_t)&buflen, "buflen", P_SHORT, 1, 47, 3, 1, 0, 0},
	{"{P}buflen.LOPR", (size_t)&buflen_lo, "buflen_lo", P_SHORT, 1, 48, 0, 1, 0, 0},
	{"{P}buflen.HOPR", (size_t)&buflen_hi, "buflen_hi", P_SHORT, 1, 49, 0, 1, 0, 0},
	{"{P}gain", (size_t)&gain, "gain", P_INT, 1, 50, 4, 1, 0, 0},
	{"{P}period", (size_t)&period_s, "period_s", P_DOUBLE, 1, 51, 5, 1, 0, 0},
	{"{P}period.LOPR", (size_t)&period_s_LOPR, "period_s_LOPR", P_DOUBLE, 1, 52, 0, 1, 0, 0},
	{"{P}period.HOPR", (size_t)&period_s_HOPR, "period_s_HOPR", P_DOUBLE, 1, 53, 0, 1, 0, 0},
	{"{P}GX", (size_t)&gx, "gx", P_DOUBLE, 1, 54, 0, 1, 0, 0},
	{"{P}GY", (size_t)&gy, "gy", P_DOUBLE, 1, 55, 0, 1, 0, 0},
	{"{P}set_offsets", (size_t)&set_offsets, "set_offsets", P_SHORT, 1, 56, 0, 1, 0, 0},
	{"{P}set_defaults", (size_t)&set_defaults, "set_defaults", P_SHORT, 1, 57, 0, 1, 0, 0},
	{"{P}settling", (size_t)&settling, "settling", P_DOUBLE, 1, 58, 0, 1, 0, 0},
	{"{P}gain.ZRST", (size_t)&gainStr[0], "gainStr[0]", P_STRING, 1, 59, 0, 1, 0, 0},
	{"{P}gain.ONST", (size_t)&gainStr[1], "gainStr[1]", P_STRING, 1, 60, 0, 1, 0, 0},
	{"{P}gain.TWST", (size_t)&gainStr[2], "gainStr[2]", P_STRING, 1, 61, 0, 1, 0, 0},
	{"{P}gain.THST", (size_t)&gainStr[3], "gainStr[3]", P_STRING, 1, 62, 0, 1, 0, 0},
	{"{P}gain.FRST", (size_t)&gainStr[4], "gainStr[4]", P_STRING, 1, 63, 0, 1, 0, 0},
	{"{P}gain.FVST", (size_t)&gainStr[5], "gainStr[5]", P_STRING, 1, 64, 0, 1, 0, 0},
	{"{P}mode.ZRST", (size_t)&signal_modeStr[0], "signal_modeStr[0]", P_STRING, 1, 65, 0, 1, 0, 0},
	{"{P}mode.ONST", (size_t)&signal_modeStr[1], "signal_modeStr[1]", P_STRING, 1, 66, 0, 1, 0, 0},
	{"{P}mode.TWST", (size_t)&signal_modeStr[2], "signal_modeStr[2]", P_STRING, 1, 67, 0, 1, 0, 0},
	{"{P}r1:A1", (size_t)&gainTrim[0], "gainTrim[0]", P_DOUBLE, 1, 68, 0, 1, 0, 0},
	{"{P}r1:B1", (size_t)&gainTrim[1], "gainTrim[1]", P_DOUBLE, 1, 69, 0, 1, 0, 0},
	{"{P}r1:C1", (size_t)&gainTrim[2], "gainTrim[2]", P_DOUBLE, 1, 70, 0, 1, 0, 0},
	{"{P}r1:D1", (size_t)&gainTrim[3], "gainTrim[3]", P_DOUBLE, 1, 71, 0, 1, 0, 0},
	{"{P}r2:A1", (size_t)&gainTrim[4], "gainTrim[4]", P_DOUBLE, 1, 72, 0, 1, 0, 0},
	{"{P}r2:B1", (size_t)&gainTrim[5], "gainTrim[5]", P_DOUBLE, 1, 73, 0, 1, 0, 0},
	{"{P}r2:C1", (size_t)&gainTrim[6], "gainTrim[6]", P_DOUBLE, 1, 74, 0, 1, 0, 0},
	{"{P}r2:D1", (size_t)&gainTrim[7], "gainTrim[7]", P_DOUBLE, 1, 75, 0, 1, 0, 0},
	{"{P}r3:A1", (size_t)&gainTrim[8], "gainTrim[8]", P_DOUBLE, 1, 76, 0, 1, 0, 0},
	{"{P}r3:B1", (size_t)&gainTrim[9], "gainTrim[9]", P_DOUBLE, 1, 77, 0, 1, 0, 0},
	{"{P}r3:C1", (size_t)&gainTrim[10], "gainTrim[10]", P_DOUBLE, 1, 78, 0, 1, 0, 0},
	{"{P}r3:D1", (size_t)&gainTrim[11], "gainTrim[11]", P_DOUBLE, 1, 79, 0, 1, 0, 0},
	{"{P}r4:A1", (size_t)&gainTrim[12], "gainTrim[12]", P_DOUBLE, 1, 80, 0, 1, 0, 0},
	{"{P}r4:B1", (size_t)&gainTrim[13], "gainTrim[13]", P_DOUBLE, 1, 81, 0, 1, 0, 0},
	{"{P}r4:C1", (size_t)&gainTrim[14], "gainTrim[14]", P_DOUBLE, 1, 82, 0, 1, 0, 0},
	{"{P}r4:D1", (size_t)&gainTrim[15], "gainTrim[15]", P_DOUBLE, 1, 83, 0, 1, 0, 0},
	{"{P}r5:A1", (size_t)&gainTrim[16], "gainTrim[16]", P_DOUBLE, 1, 84, 0, 1, 0, 0},
	{"{P}r5:B1", (size_t)&gainTrim[17], "gainTrim[17]", P_DOUBLE, 1, 85, 0, 1, 0, 0},
	{"{P}r5:C1", (size_t)&gainTrim[18], "gainTrim[18]", P_DOUBLE, 1, 86, 0, 1, 0, 0},
	{"{P}r5:D1", (size_t)&gainTrim[19], "gainTrim[19]", P_DOUBLE, 1, 87, 0, 1, 0, 0},
	{"{P}r6:A1", (size_t)&gainTrim[20], "gainTrim[20]", P_DOUBLE, 1, 88, 0, 1, 0, 0},
	{"{P}r6:B1", (size_t)&gainTrim[21], "gainTrim[21]", P_DOUBLE, 1, 89, 0, 1, 0, 0},
	{"{P}r6:C1", (size_t)&gainTrim[22], "gainTrim[22]", P_DOUBLE, 1, 90, 0, 1, 0, 0},
	{"{P}r6:D1", (size_t)&gainTrim[23], "gainTrim[23]", P_DOUBLE, 1, 91, 0, 1, 0, 0},
	{"{P}r1:A2", (size_t)&offset[0], "offset[0]", P_INT, 1, 92, 0, 1, 0, 0},
	{"{P}r1:B2", (size_t)&offset[1], "offset[1]", P_INT, 1, 93, 0, 1, 0, 0},
	{"{P}r1:C2", (size_t)&offset[2], "offset[2]", P_INT, 1, 94, 0, 1, 0, 0},
	{"{P}r1:D2", (size_t)&offset[3], "offset[3]", P_INT, 1, 95, 0, 1, 0, 0},
	{"{P}r2:A2", (size_t)&offset[4], "offset[4]", P_INT, 1, 96, 0, 1, 0, 0},
	{"{P}r2:B2", (size_t)&offset[5], "offset[5]", P_INT, 1, 97, 0, 1, 0, 0},
	{"{P}r2:C2", (size_t)&offset[6], "offset[6]", P_INT, 1, 98, 0, 1, 0, 0},
	{"{P}r2:D2", (size_t)&offset[7], "offset[7]", P_INT, 1, 99, 0, 1, 0, 0},
	{"{P}r3:A2", (size_t)&offset[8], "offset[8]", P_INT, 1, 100, 0, 1, 0, 0},
	{"{P}r3:B2", (size_t)&offset[9], "offset[9]", P_INT, 1, 101, 0, 1, 0, 0},
	{"{P}r3:C2", (size_t)&offset[10], "offset[10]", P_INT, 1, 102, 0, 1, 0, 0},
	{"{P}r3:D2", (size_t)&offset[11], "offset[11]", P_INT, 1, 103, 0, 1, 0, 0},
	{"{P}r4:A2", (size_t)&offset[12], "offset[12]", P_INT, 1, 104, 0, 1, 0, 0},
	{"{P}r4:B2", (size_t)&offset[13], "offset[13]", P_INT, 1, 105, 0, 1, 0, 0},
	{"{P}r4:C2", (size_t)&offset[14], "offset[14]", P_INT, 1, 106, 0, 1, 0, 0},
	{"{P}r4:D2", (size_t)&offset[15], "offset[15]", P_INT, 1, 107, 0, 1, 0, 0},
	{"{P}r5:A2", (size_t)&offset[16], "offset[16]", P_INT, 1, 108, 0, 1, 0, 0},
	{"{P}r5:B2", (size_t)&offset[17], "offset[17]", P_INT, 1, 109, 0, 1, 0, 0},
	{"{P}r5:C2", (size_t)&offset[18], "offset[18]", P_INT, 1, 110, 0, 1, 0, 0},
	{"{P}r5:D2", (size_t)&offset[19], "offset[19]", P_INT, 1, 111, 0, 1, 0, 0},
	{"{P}r6:A2", (size_t)&offset[20], "offset[20]", P_INT, 1, 112, 0, 1, 0, 0},
	{"{P}r6:B2", (size_t)&offset[21], "offset[21]", P_INT, 1, 113, 0, 1, 0, 0},
	{"{P}r6:C2", (size_t)&offset[22], "offset[22]", P_INT, 1, 114, 0, 1, 0, 0},
	{"{P}r6:D2", (size_t)&offset[23], "offset[23]", P_INT, 1, 115, 0, 1, 0, 0},
};

/* Event masks for state set "sncqxbpm" */
static const seqMask seqg_mask_sncqxbpm_0_startup[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_sncqxbpm_0_init[] = {
	0x18000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_sncqxbpm_0_disable[] = {
	0x10000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_sncqxbpm_0_comm_error[] = {
	0x08400000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_sncqxbpm_0_idle[] = {
	0x1840003c,
	0x00080000,
	0x00000000,
	0x00000000,
};

/* State table for state set "sncqxbpm" */
static seqState seqg_states_sncqxbpm[] = {
	{
	/* state name */        "startup",
	/* action function */   seqg_action_sncqxbpm_0_startup,
	/* event function */    seqg_event_sncqxbpm_0_startup,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_sncqxbpm_0_startup,
	/* state options */     (0)
	},
	{
	/* state name */        "init",
	/* action function */   seqg_action_sncqxbpm_0_init,
	/* event function */    seqg_event_sncqxbpm_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_sncqxbpm_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "disable",
	/* action function */   seqg_action_sncqxbpm_0_disable,
	/* event function */    seqg_event_sncqxbpm_0_disable,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_sncqxbpm_0_disable,
	/* state options */     (0)
	},
	{
	/* state name */        "comm_error",
	/* action function */   seqg_action_sncqxbpm_0_comm_error,
	/* event function */    seqg_event_sncqxbpm_0_comm_error,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_sncqxbpm_0_comm_error,
	/* state options */     (0)
	},
	{
	/* state name */        "idle",
	/* action function */   seqg_action_sncqxbpm_0_idle,
	/* event function */    seqg_event_sncqxbpm_0_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_sncqxbpm_0_idle,
	/* state options */     (0)
	},
};

/* Event masks for state set "sncqxbpm_tools" */
static const seqMask seqg_mask_sncqxbpm_tools_1_startup[] = {
	0x00000040,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_sncqxbpm_tools_1_idle[] = {
	0x00000000,
	0x03000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "sncqxbpm_tools" */
static seqState seqg_states_sncqxbpm_tools[] = {
	{
	/* state name */        "startup",
	/* action function */   seqg_action_sncqxbpm_tools_1_startup,
	/* event function */    seqg_event_sncqxbpm_tools_1_startup,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_sncqxbpm_tools_1_startup,
	/* state options */     (0)
	},
	{
	/* state name */        "idle",
	/* action function */   seqg_action_sncqxbpm_tools_1_idle,
	/* event function */    seqg_event_sncqxbpm_tools_1_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_sncqxbpm_tools_1_idle,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "sncqxbpm",
	/* states */            seqg_states_sncqxbpm,
	/* number of states */  5
	},

	{
	/* state set name */    "sncqxbpm_tools",
	/* states */            seqg_states_sncqxbpm_tools,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram sncqxbpm = {
	/* magic number */      2002005,
	/* program name */      "sncqxbpm",
	/* channels */          seqg_chans,
	/* num. channels */     109,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     0,
	/* param */             "name=qxbpm, P=iad:xbpm:, S=lax:serialOI:a4",
	/* num. event flags */  6,
	/* encoded options */   (0 | OPT_CONN | OPT_DEBUG | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void sncqxbpmRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&sncqxbpm);
}
epicsExportRegistrar(sncqxbpmRegistrar);
