/* C code for program filterDrive, generated by snc from ../filterDrive.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 56 "../filterDrive.st"
#include <string.h>
# line 57 "../filterDrive.st"
#include <math.h>
# line 58 "../filterDrive.st"
#include "chantler.h"
# line 108 "../filterDrive.st"
static const EF_ID EvFlgTRANSM_SETPT = 1;
# line 115 "../filterDrive.st"
static const EF_ID EvFlgFILTERMASK_SETPT = 2;
# line 131 "../filterDrive.st"
static const EF_ID needRecalc = 3;
# line 132 "../filterDrive.st"
static const EF_ID newEnergy = 4;
# line 189 "../filterDrive.st"
static const EF_ID externalIO = 5;
# line 230 "../filterDrive.st"







static char *cvtToBin(char *buff,
                      int val,
                      int nBits)
{
  int i, nxtBit, nxtChar;

  nxtChar = 0;
  for (i = 0; i < nBits; i++) {
    nxtBit = 1 << (nBits - i - 1);
    if ((i != 0) && ((i & 0x0003) == 0)) buff[nxtChar++] = '.';

    if (val & nxtBit) {
      buff[nxtChar++] = '1';
      val &= ~nxtBit;
    }else {
      buff[nxtChar++] = '0';
    }
  }
  buff[nxtChar] = '\0';
  if (val != 0) {
    for (i = 0; i < nxtChar; i++) buff[i] = '*';
  }

  return buff;
}


static double calcTrans(double keV,
                        double thickness,
                        char *species,
                        int debug)
{
  int i, j;
  double mu, frac, absLen, transm;

  for(i=0; i<NUM_SPECIES; i++) {
    if (strcmp(filtermat[i].name, species) == 0) break;
  }
  if(i >= NUM_SPECIES) {
    if(debug) printf("Filter material '%s' not found\n", species);
    return(0.);
  }
  if(debug & 4) printf("  species = '%s', index = %d\n", species, i);
  if(debug & 4) printf("  density = %.4e gm/cm3, thickness = %.4e um\n",
      matdensity[i], thickness);
  if(debug & 4) printf("  energy = %.4e\n", keV);

  for(j=0; j<filtermat[i].numEntries; j++) {
    if (keV < filtermat[i].keV[j]) break;
  }
  if((j < 1) | (j >= filtermat[i].numEntries)) {
    if(debug) printf("Energy '%f' not found in filter data\n", keV);
    return(0.);
  }




  frac = (keV - filtermat[i].keV[j-1]) / (filtermat[i].keV[j] - filtermat[i].keV[j-1]);
  mu = filtermat[i].mu[j-1] + frac * (filtermat[i].mu[j] - filtermat[i].mu[j-1]);
  absLen = 1.0/(matdensity[i]*mu);
  absLen *= 1.e4;
  transm = exp(-(thickness/absLen));

  if(debug & 8){
    printf("  E1 = %.4e keV, mu1 = %.4e\n",
        filtermat[i].keV[j-1], filtermat[i].mu[j-1]);
    printf("  E2 = %.4e keV, mu2 = %.4e\n",
        filtermat[i].keV[j], filtermat[i].mu[j]);
    printf("  frac = %.4f, mu = %.4e\n", frac, mu);
  }

  if(debug & 4){
    printf("  attenuation length ='%.4e' um, transmission=%.4e\n", absLen, transm);
  }

  return(transm);
}



/* Variable declarations */
struct seqg_vars {
# line 72 "../filterDrive.st"
	int STATUS_BUSY;
# line 77 "../filterDrive.st"
	int NFILTERS;
# line 87 "../filterDrive.st"
	int DEBUG;
# line 92 "../filterDrive.st"
	double TRANSMISSION;
# line 96 "../filterDrive.st"
	double TRANSMISSION_UP;
# line 100 "../filterDrive.st"
	double TRANSMISSION_DOWN;
# line 104 "../filterDrive.st"
	int FILTER_MASK;
# line 109 "../filterDrive.st"
	double TRANSM_SETPT;
# line 116 "../filterDrive.st"
	int FILTERMASK_SETPT;
# line 122 "../filterDrive.st"
	int TRANSM_UP;
# line 127 "../filterDrive.st"
	int TRANSM_DN;
# line 135 "../filterDrive.st"
	double ENERGY;
# line 141 "../filterDrive.st"
	string MSGE;
# line 145 "../filterDrive.st"
	double FILTER_WAIT_TIME;
# line 149 "../filterDrive.st"
	double TRANSM[32];
# line 153 "../filterDrive.st"
	double THICK[32];
# line 159 "../filterDrive.st"
	string MATER[32];
# line 165 "../filterDrive.st"
	int LOCK[32];
# line 171 "../filterDrive.st"
	int SET[32];
# line 176 "../filterDrive.st"
	int ENBL[32];
# line 182 "../filterDrive.st"
	int OUT[32];
# line 186 "../filterDrive.st"
	int OUTGET[32];
# line 193 "../filterDrive.st"
	char *name;
# line 194 "../filterDrive.st"
	char *prefix;
# line 195 "../filterDrive.st"
	char *record;
# line 196 "../filterDrive.st"
	int changeFlag;
# line 197 "../filterDrive.st"
	int doWait;
# line 198 "../filterDrive.st"
	int nFltrs;
# line 199 "../filterDrive.st"
	int nEnabled;
# line 200 "../filterDrive.st"
	int nPerms;
# line 201 "../filterDrive.st"
	int ind;
# line 202 "../filterDrive.st"
	int indNow;
# line 203 "../filterDrive.st"
	int fltrsInNow;
# line 204 "../filterDrive.st"
	double transNow;
# line 205 "../filterDrive.st"
	int indUp;
# line 206 "../filterDrive.st"
	int fltrsInUp;
# line 207 "../filterDrive.st"
	double transUp;
# line 208 "../filterDrive.st"
	int indDown;
# line 209 "../filterDrive.st"
	int fltrsInDown;
# line 210 "../filterDrive.st"
	double transDown;
# line 211 "../filterDrive.st"
	double trans;
# line 212 "../filterDrive.st"
	int indMin;
# line 213 "../filterDrive.st"
	double transMin;
# line 214 "../filterDrive.st"
	int i;
# line 215 "../filterDrive.st"
	int j;
# line 216 "../filterDrive.st"
	int k;
# line 217 "../filterDrive.st"
	int myAction;
# line 218 "../filterDrive.st"
	int fltrsReq;
# line 219 "../filterDrive.st"
	int fltrsSetpt;
# line 220 "../filterDrive.st"
	char str[64];
# line 221 "../filterDrive.st"
	double transMis[65536];
# line 222 "../filterDrive.st"
	int fltrsIn[65536];
# line 223 "../filterDrive.st"
	string buff0;
# line 224 "../filterDrive.st"
	string buff1;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "start" in state set "filterDrive" ******/

/* Event function for state "start" in state set "filterDrive" */
static seqBool seqg_event_filterDrive_0_start(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "start" in state set "filterDrive" */
static void seqg_action_filterDrive_0_start(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 330 "../filterDrive.st"
			seqg_var->changeFlag = 1;
# line 333 "../filterDrive.st"
			epicsThreadSleep(1.0);
# line 336 "../filterDrive.st"
			seqg_var->name = seq_macValueGet(seqg_env, "NAME");
# line 337 "../filterDrive.st"
			seqg_var->prefix = seq_macValueGet(seqg_env, "P");
# line 338 "../filterDrive.st"
			seqg_var->record = seq_macValueGet(seqg_env, "R");
# line 339 "../filterDrive.st"
			sscanf(seq_macValueGet(seqg_env, "NUM_FILTERS"), "%d", &seqg_var->nFltrs);
# line 342 "../filterDrive.st"
			for (seqg_var->i = 0; seqg_var->i < seqg_var->nFltrs; seqg_var->i++)
			{
# line 343 "../filterDrive.st"
				sprintf(seqg_var->str, "%s%sFi%d:Thickness", seqg_var->prefix, seqg_var->record, seqg_var->i + 1);
# line 344 "../filterDrive.st"
				seq_pvAssign(seqg_env, 46/*THICK*/ + (CH_ID)(seqg_var->i), seqg_var->str);
# line 345 "../filterDrive.st"
				sprintf(seqg_var->str, "%s%sFi%d:Material", seqg_var->prefix, seqg_var->record, seqg_var->i + 1);
# line 346 "../filterDrive.st"
				seq_pvAssign(seqg_env, 78/*MATER*/ + (CH_ID)(seqg_var->i), seqg_var->str);
# line 347 "../filterDrive.st"
				sprintf(seqg_var->str, "%s%sFi%d:Transmission", seqg_var->prefix, seqg_var->record, seqg_var->i + 1);
# line 348 "../filterDrive.st"
				seq_pvAssign(seqg_env, 14/*TRANSM*/ + (CH_ID)(seqg_var->i), seqg_var->str);
# line 349 "../filterDrive.st"
				sprintf(seqg_var->str, "%s%sFi%d:Lock", seqg_var->prefix, seqg_var->record, seqg_var->i + 1);
# line 350 "../filterDrive.st"
				seq_pvAssign(seqg_env, 110/*LOCK*/ + (CH_ID)(seqg_var->i), seqg_var->str);
# line 351 "../filterDrive.st"
				sprintf(seqg_var->str, "%s%sFi%d:Set", seqg_var->prefix, seqg_var->record, seqg_var->i + 1);
# line 352 "../filterDrive.st"
				seq_pvAssign(seqg_env, 142/*SET*/ + (CH_ID)(seqg_var->i), seqg_var->str);
# line 353 "../filterDrive.st"
				sprintf(seqg_var->str, "%s%sFi%d:Enable", seqg_var->prefix, seqg_var->record, seqg_var->i + 1);
# line 354 "../filterDrive.st"
				seq_pvAssign(seqg_env, 174/*ENBL*/ + (CH_ID)(seqg_var->i), seqg_var->str);
# line 355 "../filterDrive.st"
				sprintf(seqg_var->str, "%s%sFi%d:Set", seqg_var->prefix, seqg_var->record, seqg_var->i + 1);
# line 356 "../filterDrive.st"
				seq_pvAssign(seqg_env, 206/*OUT*/ + (CH_ID)(seqg_var->i), seqg_var->str);
# line 357 "../filterDrive.st"
				sprintf(seqg_var->str, "%s%sFi%d:OutGet", seqg_var->prefix, seqg_var->record, seqg_var->i + 1);
# line 358 "../filterDrive.st"
				seq_pvAssign(seqg_env, 238/*OUTGET*/ + (CH_ID)(seqg_var->i), seqg_var->str);
			}
# line 362 "../filterDrive.st"
			seqg_var->NFILTERS = seqg_var->nFltrs;
# line 363 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 1/*NFILTERS*/, DEFAULT, DEFAULT_TIMEOUT);
# line 365 "../filterDrive.st"
			printf("%s: SNL program started for %s%s\n", seqg_var->name, seqg_var->prefix, seqg_var->record);
# line 366 "../filterDrive.st"
			printf("%s:   # of filters = %d\n", seqg_var->name, seqg_var->nFltrs);
# line 369 "../filterDrive.st"
			epicsThreadSleep(1.0);
		}
		return;
	}
}

/****** Code for state "init" in state set "filterDrive" ******/

/* Event function for state "init" in state set "filterDrive" */
static seqBool seqg_event_filterDrive_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 378 "../filterDrive.st"
	if (seq_pvConnectCount(seqg_env) == seq_pvAssignCount(seqg_env))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "filterDrive" */
static void seqg_action_filterDrive_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 380 "../filterDrive.st"
			epicsThreadSleep(2.0);
# line 382 "../filterDrive.st"
			sprintf(seqg_var->MSGE, "Initialising ...");
# line 382 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
# line 382 "../filterDrive.st"
			strcpy(seqg_var->MSGE, "");
# line 383 "../filterDrive.st"
			seq_efClear(seqg_env, EvFlgTRANSM_SETPT);
# line 384 "../filterDrive.st"
			seqg_var->TRANSM_UP = 0;
# line 384 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 9/*TRANSM_UP*/, DEFAULT, DEFAULT_TIMEOUT);
# line 385 "../filterDrive.st"
			seqg_var->TRANSM_DN = 0;
# line 385 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 10/*TRANSM_DN*/, DEFAULT, DEFAULT_TIMEOUT);
# line 386 "../filterDrive.st"
			seq_efSet(seqg_env, needRecalc);
		}
		return;
	}
}

/****** Code for state "waiting" in state set "filterDrive" ******/

/* Event function for state "waiting" in state set "filterDrive" */
static seqBool seqg_event_filterDrive_0_waiting(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 395 "../filterDrive.st"
	if (seq_pvConnectCount(seqg_env) != seq_pvAssignCount(seqg_env))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 400 "../filterDrive.st"
	if (seq_efTestAndClear(seqg_env, newEnergy))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 405 "../filterDrive.st"
	if (seq_efTestAndClear(seqg_env, needRecalc))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 410 "../filterDrive.st"
	if (seq_efTestAndClear(seqg_env, EvFlgTRANSM_SETPT))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 416 "../filterDrive.st"
	if (seqg_var->TRANSM_UP)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 424 "../filterDrive.st"
	if (seqg_var->TRANSM_DN)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 5;
		return TRUE;
	}
# line 432 "../filterDrive.st"
	if (seq_efTestAndClear(seqg_env, EvFlgFILTERMASK_SETPT))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 6;
		return TRUE;
	}
# line 438 "../filterDrive.st"
	if (seqg_var->STATUS_BUSY)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 7;
		return TRUE;
	}
# line 444 "../filterDrive.st"
	if (seq_efTestAndClear(seqg_env, externalIO))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 8;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waiting" in state set "filterDrive" */
static void seqg_action_filterDrive_0_waiting(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 396 "../filterDrive.st"
			printf("%s: channel connection lost.\n", seqg_var->name);
		}
		return;
	case 1:
		{
# line 401 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x1)
# line 401 "../filterDrive.st"
				printf("%s: Energy change detected\n", seqg_var->name);
		}
		return;
	case 2:
		{
# line 406 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x1)
# line 406 "../filterDrive.st"
				printf("%s: Configuration change detected\n", seqg_var->name);
		}
		return;
	case 3:
		{
# line 411 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x1)
# line 411 "../filterDrive.st"
				printf("%s: transmission setpoint changed.\n", seqg_var->name);
# line 412 "../filterDrive.st"
			seqg_var->myAction = 0;
		}
		return;
	case 4:
		{
# line 417 "../filterDrive.st"
			seqg_var->TRANSM_UP = 0;
# line 418 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 9/*TRANSM_UP*/, DEFAULT, DEFAULT_TIMEOUT);
# line 419 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x1)
# line 419 "../filterDrive.st"
				printf("%s: step up.\n", seqg_var->name);
# line 420 "../filterDrive.st"
			seqg_var->myAction = 1;
		}
		return;
	case 5:
		{
# line 425 "../filterDrive.st"
			seqg_var->TRANSM_DN = 0;
# line 426 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 10/*TRANSM_DN*/, DEFAULT, DEFAULT_TIMEOUT);
# line 427 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x1)
# line 427 "../filterDrive.st"
				printf("%s: step down.\n", seqg_var->name);
# line 428 "../filterDrive.st"
			seqg_var->myAction = 2;
		}
		return;
	case 6:
		{
# line 433 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x1)
# line 433 "../filterDrive.st"
				printf("%s: filter mask setpoint changed.\n", seqg_var->name);
# line 434 "../filterDrive.st"
			seqg_var->myAction = 3;
		}
		return;
	case 7:
		{
# line 439 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x1)
# line 439 "../filterDrive.st"
				printf("%s: Busy record was set\n", seqg_var->name);
# line 440 "../filterDrive.st"
			seqg_var->changeFlag = 1;
		}
		return;
	case 8:
		{
# line 445 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x1)
# line 445 "../filterDrive.st"
				printf("%s: External IO event flag was set\n", seqg_var->name);
		}
		return;
	}
}

/****** Code for state "update_filters" in state set "filterDrive" ******/

/* Entry function for state "update_filters" in state set "filterDrive" */
static void seqg_entry_filterDrive_0_update_filters(SS_ID seqg_env)
{
# line 454 "../filterDrive.st"
	if (seqg_var->DEBUG & 0x1)
# line 454 "../filterDrive.st"
		printf("%s: entering state: update_filters\n", seqg_var->name);
# line 455 "../filterDrive.st"
	seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
# line 455 "../filterDrive.st"
	strcpy(seqg_var->MSGE, "OK");
}

/* Event function for state "update_filters" in state set "filterDrive" */
static seqBool seqg_event_filterDrive_0_update_filters(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "update_filters" in state set "filterDrive" */
static void seqg_action_filterDrive_0_update_filters(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 461 "../filterDrive.st"
			for (seqg_var->i = 0; seqg_var->i < seqg_var->nFltrs; seqg_var->i++)
			{
# line 462 "../filterDrive.st"
				seq_pvGetTmo(seqg_env, 238/*OUTGET*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 463 "../filterDrive.st"
				seq_efClear(seqg_env, externalIO);
# line 464 "../filterDrive.st"
				seq_pvGetTmo(seqg_env, 142/*SET*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 465 "../filterDrive.st"
				if (seqg_var->SET[seqg_var->i] != seqg_var->OUTGET[seqg_var->i])
				{
# line 470 "../filterDrive.st"
					seqg_var->SET[seqg_var->i] = seqg_var->OUTGET[seqg_var->i];
# line 471 "../filterDrive.st"
					seq_pvPutTmo(seqg_env, 142/*SET*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 472 "../filterDrive.st"
					sprintf(seqg_var->MSGE, "Filter state set by external agent.");
# line 473 "../filterDrive.st"
					seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 478 "../filterDrive.st"
			seqg_var->transNow = 1.0;
# line 479 "../filterDrive.st"
			seqg_var->fltrsInNow = 0;
# line 480 "../filterDrive.st"
			seqg_var->nEnabled = 0;
# line 481 "../filterDrive.st"
			for (seqg_var->i = 0; seqg_var->i < seqg_var->nFltrs; seqg_var->i++)
			{
# line 483 "../filterDrive.st"
				if (seqg_var->DEBUG & 0x4)
				{
# line 484 "../filterDrive.st"
					printf("%s: Calculating transmission for blade %d.\n", seqg_var->name, seqg_var->i);
				}
# line 486 "../filterDrive.st"
				seqg_var->TRANSM[seqg_var->i] = calcTrans(seqg_var->ENERGY, seqg_var->THICK[seqg_var->i], seqg_var->MATER[seqg_var->i], seqg_var->DEBUG);
# line 487 "../filterDrive.st"
				seq_pvPutTmo(seqg_env, 14/*TRANSM*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 490 "../filterDrive.st"
				if (seqg_var->SET[seqg_var->i] && seqg_var->ENBL[seqg_var->i])
				{
# line 491 "../filterDrive.st"
					seqg_var->fltrsInNow |= (1 << seqg_var->i);
# line 492 "../filterDrive.st"
					seqg_var->transNow *= seqg_var->TRANSM[seqg_var->i];
				}
# line 494 "../filterDrive.st"
				if ((seqg_var->LOCK[seqg_var->i] == 0) && seqg_var->ENBL[seqg_var->i])
				{
# line 495 "../filterDrive.st"
					seqg_var->nEnabled += 1;
				}
			}
# line 499 "../filterDrive.st"
			seqg_var->TRANSMISSION = seqg_var->transNow;
# line 499 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 3/*TRANSMISSION*/, DEFAULT, DEFAULT_TIMEOUT);
# line 500 "../filterDrive.st"
			seqg_var->FILTER_MASK = seqg_var->fltrsInNow;
# line 500 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 6/*FILTER_MASK*/, DEFAULT, DEFAULT_TIMEOUT);
# line 503 "../filterDrive.st"
			if (seqg_var->nEnabled > 16)
			{
# line 504 "../filterDrive.st"
				if (seqg_var->DEBUG & 0x1)
				{
# line 506 "../filterDrive.st"
					printf("%s: ERROR: Too many filters unlocked (%d/%d).\n", seqg_var->name, seqg_var->nEnabled, 16);
				}
# line 508 "../filterDrive.st"
				sprintf(seqg_var->MSGE, "ERROR: Too many unlocked (%d/%d)", seqg_var->nEnabled, 16);
# line 509 "../filterDrive.st"
				seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 515 "../filterDrive.st"
			seqg_var->nPerms = 1 << seqg_var->nEnabled;
# line 516 "../filterDrive.st"
			for (seqg_var->i = 0; seqg_var->i < seqg_var->nPerms; seqg_var->i++)
			{
# line 517 "../filterDrive.st"
				seqg_var->transMis[seqg_var->i] = 1.0;
# line 518 "../filterDrive.st"
				seqg_var->fltrsIn[seqg_var->i] = 0;
# line 519 "../filterDrive.st"
				seqg_var->k = 0;
# line 520 "../filterDrive.st"
				for (seqg_var->j = 0; seqg_var->j < seqg_var->nFltrs; seqg_var->j++)
				{
# line 521 "../filterDrive.st"
					if (seqg_var->ENBL[seqg_var->j])
					{
# line 522 "../filterDrive.st"
						if (seqg_var->LOCK[seqg_var->j] == 1)
						{
# line 523 "../filterDrive.st"
							if (seqg_var->SET[seqg_var->j])
							{
# line 525 "../filterDrive.st"
								seqg_var->transMis[seqg_var->i] *= seqg_var->TRANSM[seqg_var->j];
# line 526 "../filterDrive.st"
								seqg_var->fltrsIn[seqg_var->i] |= (1 << seqg_var->j);
							}
						}
						else
						{
# line 529 "../filterDrive.st"
							if (seqg_var->i & (1 << seqg_var->k))
							{
# line 530 "../filterDrive.st"
								seqg_var->transMis[seqg_var->i] *= seqg_var->TRANSM[seqg_var->j];
# line 531 "../filterDrive.st"
								seqg_var->fltrsIn[seqg_var->i] |= (1 << seqg_var->j);
							}
# line 533 "../filterDrive.st"
							seqg_var->k++;
						}
					}
				}
			}
# line 538 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x2)
			{
# line 540 "../filterDrive.st"
				printf("%s: <#-enabled>=%d, <#-permutations>=%d, transmission=%e\n", seqg_var->name, seqg_var->nEnabled, seqg_var->nPerms, seqg_var->transNow);
# line 541 "../filterDrive.st"
				for (seqg_var->i = 0; ((seqg_var->i < seqg_var->nPerms) && (seqg_var->i < 100)); seqg_var->i++)
				{
# line 545 "../filterDrive.st"
					printf("  %s: %s    %e\n", cvtToBin(seqg_var->buff0, seqg_var->i, seqg_var->nEnabled), cvtToBin(seqg_var->buff1, seqg_var->fltrsIn[seqg_var->i], seqg_var->nFltrs), seqg_var->transMis[seqg_var->i]);
				}
			}
# line 550 "../filterDrive.st"
			seqg_var->indNow = -1;
# line 551 "../filterDrive.st"
			for (seqg_var->ind = 0; seqg_var->ind < seqg_var->nPerms; seqg_var->ind++)
			{
# line 552 "../filterDrive.st"
				if (seqg_var->transMis[seqg_var->ind] == seqg_var->transNow)
# line 552 "../filterDrive.st"
					seqg_var->indNow = seqg_var->ind;
			}
# line 554 "../filterDrive.st"
			if (seqg_var->indNow < 0)
			{
# line 555 "../filterDrive.st"
				printf("ERROR: Could not find current filter index\n");
			}
# line 557 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x2)
			{
# line 558 "../filterDrive.st"
				printf("%s: Current index = %d\n", seqg_var->name, seqg_var->indNow);
			}
# line 562 "../filterDrive.st"
			seqg_var->indUp = -1;
# line 563 "../filterDrive.st"
			seqg_var->transUp = 10.0;
# line 564 "../filterDrive.st"
			for (seqg_var->ind = 0; seqg_var->ind < seqg_var->nPerms; seqg_var->ind++)
			{
# line 565 "../filterDrive.st"
				if ((seqg_var->transMis[seqg_var->ind] > (seqg_var->transNow * (1 + 1e-8))) & (seqg_var->transMis[seqg_var->ind] < seqg_var->transUp))
				{
# line 567 "../filterDrive.st"
					seqg_var->transUp = seqg_var->transMis[seqg_var->ind];
# line 568 "../filterDrive.st"
					seqg_var->indUp = seqg_var->ind;
				}
			}
# line 571 "../filterDrive.st"
			if (seqg_var->transUp > 1.0)
			{
# line 572 "../filterDrive.st"
				seqg_var->transUp = seqg_var->transNow;
# line 573 "../filterDrive.st"
				seqg_var->indUp = seqg_var->indNow;
			}
# line 575 "../filterDrive.st"
			seqg_var->fltrsInUp = seqg_var->fltrsIn[seqg_var->indUp];
# line 576 "../filterDrive.st"
			seqg_var->TRANSMISSION_UP = seqg_var->transUp;
# line 577 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 4/*TRANSMISSION_UP*/, DEFAULT, DEFAULT_TIMEOUT);
# line 578 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x2)
			{
# line 580 "../filterDrive.st"
				printf("%s: Filter up: index = %d, transm = %e\n", seqg_var->name, seqg_var->indUp, seqg_var->transUp);
			}
# line 584 "../filterDrive.st"
			seqg_var->indDown = -1;
# line 585 "../filterDrive.st"
			seqg_var->transDown = -1.0;
# line 586 "../filterDrive.st"
			for (seqg_var->ind = 0; seqg_var->ind < seqg_var->nPerms; seqg_var->ind++)
			{
# line 587 "../filterDrive.st"
				if ((seqg_var->transMis[seqg_var->ind] < (seqg_var->transNow * (1 - 1e-8))) & (seqg_var->transMis[seqg_var->ind] > seqg_var->transDown))
				{
# line 589 "../filterDrive.st"
					seqg_var->transDown = seqg_var->transMis[seqg_var->ind];
# line 590 "../filterDrive.st"
					seqg_var->indDown = seqg_var->ind;
				}
			}
# line 593 "../filterDrive.st"
			if (seqg_var->transDown < 0.0)
			{
# line 594 "../filterDrive.st"
				seqg_var->transDown = seqg_var->transNow;
# line 595 "../filterDrive.st"
				seqg_var->indDown = seqg_var->indNow;
			}
# line 597 "../filterDrive.st"
			seqg_var->fltrsInDown = seqg_var->fltrsIn[seqg_var->indDown];
# line 598 "../filterDrive.st"
			seqg_var->TRANSMISSION_DOWN = seqg_var->transDown;
# line 599 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 5/*TRANSMISSION_DOWN*/, DEFAULT, DEFAULT_TIMEOUT);
# line 600 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x2)
			{
# line 602 "../filterDrive.st"
				printf("%s: Filter down: index = %d, transm = %e\n", seqg_var->name, seqg_var->indDown, seqg_var->transDown);
			}
# line 606 "../filterDrive.st"
			if (seqg_var->changeFlag)
			{
# line 607 "../filterDrive.st"
				if (seqg_var->DEBUG & 0x1)
# line 607 "../filterDrive.st"
					printf("%s: clearing busy record.\n", seqg_var->name);
# line 608 "../filterDrive.st"
				seqg_var->changeFlag = 0;
# line 610 "../filterDrive.st"
				seqg_var->STATUS_BUSY = 0;
# line 611 "../filterDrive.st"
				seq_pvPutTmo(seqg_env, 0/*STATUS_BUSY*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

/****** Code for state "action" in state set "filterDrive" ******/

/* Event function for state "action" in state set "filterDrive" */
static seqBool seqg_event_filterDrive_0_action(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "action" in state set "filterDrive" */
static void seqg_action_filterDrive_0_action(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 623 "../filterDrive.st"
			strcpy(seqg_var->MSGE, "");
# line 623 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
# line 626 "../filterDrive.st"
			seqg_var->changeFlag = 1;
# line 628 "../filterDrive.st"
			if (seqg_var->DEBUG & 0x1)
			{
# line 629 "../filterDrive.st"
				sprintf(seqg_var->MSGE, "Action = %d", seqg_var->myAction);
# line 629 "../filterDrive.st"
				seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
# line 630 "../filterDrive.st"
				printf("Action = %d\n", seqg_var->myAction);
			}
# line 633 "../filterDrive.st"
			strcpy(seqg_var->MSGE, "");
# line 635 "../filterDrive.st"
			if (seqg_var->myAction == 0)
			{
# line 640 "../filterDrive.st"
				if (seqg_var->DEBUG & 0x1)
				{
# line 641 "../filterDrive.st"
					printf("%s: Required transmission = %e\n", seqg_var->name, seqg_var->TRANSM_SETPT);
				}
# line 644 "../filterDrive.st"
				seqg_var->trans = -1.0;
# line 645 "../filterDrive.st"
				seqg_var->transMin = 1.0;
# line 646 "../filterDrive.st"
				for (seqg_var->k = 0; seqg_var->k < seqg_var->nPerms; seqg_var->k++)
				{
# line 647 "../filterDrive.st"
					if ((seqg_var->transMis[seqg_var->k] <= (seqg_var->TRANSM_SETPT)) & (seqg_var->transMis[seqg_var->k] > seqg_var->trans))
					{
# line 649 "../filterDrive.st"
						seqg_var->ind = seqg_var->k;
# line 650 "../filterDrive.st"
						seqg_var->trans = seqg_var->transMis[seqg_var->k];
					}
# line 652 "../filterDrive.st"
					if (seqg_var->transMis[seqg_var->k] < seqg_var->transMin)
					{
# line 653 "../filterDrive.st"
						seqg_var->transMin = seqg_var->transMis[seqg_var->k];
# line 654 "../filterDrive.st"
						seqg_var->indMin = seqg_var->k;
					}
				}
# line 657 "../filterDrive.st"
				if (seqg_var->trans < seqg_var->transMin)
				{
# line 658 "../filterDrive.st"
					seqg_var->ind = seqg_var->indMin;
				}
# line 661 "../filterDrive.st"
				if (seqg_var->DEBUG & 0x1)
				{
# line 662 "../filterDrive.st"
					printf("%s: New filter index: %d\n", seqg_var->name, seqg_var->ind);
# line 664 "../filterDrive.st"
					printf("%s: Selected filters are: %s   Transmission = %e\n", seqg_var->name, cvtToBin(seqg_var->buff1, seqg_var->fltrsIn[seqg_var->ind], seqg_var->nFltrs), seqg_var->transMis[seqg_var->ind]);
				}
# line 667 "../filterDrive.st"
				if (seqg_var->transMis[seqg_var->ind] == seqg_var->transNow)
				{
# line 668 "../filterDrive.st"
					if (seqg_var->DEBUG & 0x1)
# line 668 "../filterDrive.st"
						printf("NO CHANGE! Current settings are best.\n");
# line 669 "../filterDrive.st"
					strcpy(seqg_var->MSGE, "OK - No change");
# line 670 "../filterDrive.st"
					seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
				}
				else
				{
# line 672 "../filterDrive.st"
					strcpy(seqg_var->MSGE, "OK");
# line 672 "../filterDrive.st"
					seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
			else
# line 675 "../filterDrive.st"
				if (seqg_var->myAction == 1)
				{
# line 679 "../filterDrive.st"
					seqg_var->ind = seqg_var->indUp;
# line 680 "../filterDrive.st"
					if (seqg_var->transUp == seqg_var->transNow)
					{
# line 681 "../filterDrive.st"
						strcpy(seqg_var->MSGE, "NO CHANGE! Step unavailable.");
# line 682 "../filterDrive.st"
						seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
# line 683 "../filterDrive.st"
						if (seqg_var->DEBUG & 0x1)
# line 683 "../filterDrive.st"
							printf("%s: No more steps up available!\n", seqg_var->name);
					}
					else
					{
# line 685 "../filterDrive.st"
						strcpy(seqg_var->MSGE, "OK");
# line 685 "../filterDrive.st"
						seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
					}
# line 687 "../filterDrive.st"
					if (seqg_var->DEBUG & 0x1)
					{
# line 689 "../filterDrive.st"
						printf("%s: Next filter pattern is %s,  Transmission = %e\n", seqg_var->name, cvtToBin(seqg_var->buff1, seqg_var->fltrsIn[seqg_var->ind], seqg_var->nFltrs), seqg_var->transMis[seqg_var->ind]);
					}
				}
				else
# line 692 "../filterDrive.st"
					if (seqg_var->myAction == 2)
					{
# line 696 "../filterDrive.st"
						seqg_var->ind = seqg_var->indDown;
# line 697 "../filterDrive.st"
						if (seqg_var->transDown == seqg_var->transNow)
						{
# line 698 "../filterDrive.st"
							strcpy(seqg_var->MSGE, "NO CHANGE! Step unavailable.");
# line 699 "../filterDrive.st"
							seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
# line 700 "../filterDrive.st"
							if (seqg_var->DEBUG & 0x1)
# line 700 "../filterDrive.st"
								printf("%s: No more steps down available!\n", seqg_var->name);
						}
						else
						{
# line 702 "../filterDrive.st"
							strcpy(seqg_var->MSGE, "OK");
# line 702 "../filterDrive.st"
							seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
						}
# line 704 "../filterDrive.st"
						if (seqg_var->DEBUG & 0x1)
						{
# line 706 "../filterDrive.st"
							printf("%s: Next filter pattern is %s,  Transmission = %e\n", seqg_var->name, cvtToBin(seqg_var->buff1, seqg_var->fltrsIn[seqg_var->ind], seqg_var->nFltrs), seqg_var->transMis[seqg_var->ind]);
						}
					}
					else
# line 709 "../filterDrive.st"
						if (seqg_var->myAction == 3)
						{
# line 712 "../filterDrive.st"
							seqg_var->fltrsSetpt = seqg_var->FILTERMASK_SETPT;
# line 715 "../filterDrive.st"
							if ((seqg_var->fltrsSetpt < 0) | (seqg_var->fltrsSetpt > ((1 << seqg_var->nFltrs) - 1)))
							{
# line 716 "../filterDrive.st"
								seqg_var->ind = seqg_var->indNow;
# line 717 "../filterDrive.st"
								strcpy(seqg_var->MSGE, "ERROR! Invalid mask.");
# line 718 "../filterDrive.st"
								seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
# line 719 "../filterDrive.st"
								if (seqg_var->DEBUG & 0x1)
								{
# line 720 "../filterDrive.st"
									printf("%s: ERROR! Invalid filter mask: %d\n", seqg_var->name, seqg_var->fltrsSetpt);
# line 722 "../filterDrive.st"
									printf("%s:   Valid masks are in the range (0 - %d)\n", seqg_var->name, ((1 << seqg_var->nFltrs) - 1));
								}
							}
							else
							{
# line 727 "../filterDrive.st"
								seqg_var->fltrsReq = 0;
# line 728 "../filterDrive.st"
								for (seqg_var->j = 0; seqg_var->j < seqg_var->nFltrs; seqg_var->j++)
								{
# line 729 "../filterDrive.st"
									if (seqg_var->ENBL[seqg_var->j])
									{
# line 730 "../filterDrive.st"
										if (seqg_var->LOCK[seqg_var->j] == 1)
										{
# line 731 "../filterDrive.st"
											if (seqg_var->SET[seqg_var->j])
											{
# line 733 "../filterDrive.st"
												seqg_var->fltrsReq |= (1 << seqg_var->j);
											}
										}
										else
										{
# line 736 "../filterDrive.st"
											seqg_var->fltrsReq |= (1 << seqg_var->j) & seqg_var->fltrsSetpt;
										}
									}
								}
# line 740 "../filterDrive.st"
								if (seqg_var->DEBUG & 0x1)
								{
# line 741 "../filterDrive.st"
									printf("%s: Required filter mask: %x\n", seqg_var->name, seqg_var->fltrsSetpt);
# line 742 "../filterDrive.st"
									printf("%s: Adjusted filter mask: %x\n", seqg_var->name, seqg_var->fltrsReq);
								}
# line 745 "../filterDrive.st"
								seqg_var->ind = -1;
# line 746 "../filterDrive.st"
								for (seqg_var->i = 0; seqg_var->i < seqg_var->nPerms; seqg_var->i++)
								{
# line 747 "../filterDrive.st"
									if (seqg_var->fltrsIn[seqg_var->i] == seqg_var->fltrsReq)
# line 747 "../filterDrive.st"
										seqg_var->ind = seqg_var->i;
								}
# line 749 "../filterDrive.st"
								if (seqg_var->ind < 0)
								{
# line 750 "../filterDrive.st"
									printf("%s: Cannot find the requested filter pattern!\n", seqg_var->name);
# line 751 "../filterDrive.st"
									strcpy(seqg_var->MSGE, "ERROR! Filter Mask not found.");
# line 752 "../filterDrive.st"
									seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
								}
								else
								{
# line 754 "../filterDrive.st"
									strcpy(seqg_var->MSGE, "OK");
# line 754 "../filterDrive.st"
									seq_pvPutTmo(seqg_env, 12/*MSGE*/, DEFAULT, DEFAULT_TIMEOUT);
								}
# line 757 "../filterDrive.st"
								if (seqg_var->DEBUG & 0x1)
								{
# line 759 "../filterDrive.st"
									printf("%s: Next filter pattern is %s,  Transmission = %e\n", seqg_var->name, cvtToBin(seqg_var->buff1, seqg_var->fltrsIn[seqg_var->ind], seqg_var->nFltrs), seqg_var->transMis[seqg_var->ind]);
								}
							}
						}
# line 765 "../filterDrive.st"
			seqg_var->TRANSM_UP = 0;
# line 765 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 9/*TRANSM_UP*/, DEFAULT, DEFAULT_TIMEOUT);
# line 766 "../filterDrive.st"
			seqg_var->TRANSM_DN = 0;
# line 766 "../filterDrive.st"
			seq_pvPutTmo(seqg_env, 10/*TRANSM_DN*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "change_filters" in state set "filterDrive" ******/

/* Event function for state "change_filters" in state set "filterDrive" */
static seqBool seqg_event_filterDrive_0_change_filters(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "change_filters" in state set "filterDrive" */
static void seqg_action_filterDrive_0_change_filters(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 774 "../filterDrive.st"
			if (seqg_var->ind >= 0)
			{
# line 777 "../filterDrive.st"
				seqg_var->doWait = 0;
# line 778 "../filterDrive.st"
				for (seqg_var->j = 0; seqg_var->j < seqg_var->nFltrs; seqg_var->j++)
				{
# line 779 "../filterDrive.st"
					if (seqg_var->ENBL[seqg_var->j])
					{
# line 780 "../filterDrive.st"
						if (seqg_var->fltrsIn[seqg_var->ind] & (1 << seqg_var->j))
						{
# line 781 "../filterDrive.st"
							if (seqg_var->SET[seqg_var->j] == 0)
# line 781 "../filterDrive.st"
								seqg_var->doWait = 1;
# line 782 "../filterDrive.st"
							seqg_var->SET[seqg_var->j] = 1;
# line 782 "../filterDrive.st"
							seq_pvPutTmo(seqg_env, 142/*SET*/ + (CH_ID)(seqg_var->j), DEFAULT, DEFAULT_TIMEOUT);
						}
					}
				}
# line 788 "../filterDrive.st"
				if (seqg_var->doWait)
				{
# line 789 "../filterDrive.st"
					seq_pvGetTmo(seqg_env, 13/*FILTER_WAIT_TIME*/, DEFAULT, DEFAULT_TIMEOUT);
# line 790 "../filterDrive.st"
					epicsThreadSleep(seqg_var->FILTER_WAIT_TIME);
				}
# line 794 "../filterDrive.st"
				seqg_var->doWait = 0;
# line 795 "../filterDrive.st"
				for (seqg_var->j = 0; seqg_var->j < seqg_var->nFltrs; seqg_var->j++)
				{
# line 796 "../filterDrive.st"
					if (seqg_var->ENBL[seqg_var->j])
					{
# line 797 "../filterDrive.st"
						if ((seqg_var->fltrsIn[seqg_var->ind] & (1 << seqg_var->j)) == 0)
						{
# line 798 "../filterDrive.st"
							if (seqg_var->SET[seqg_var->j] == 1)
# line 798 "../filterDrive.st"
								seqg_var->doWait = 1;
# line 799 "../filterDrive.st"
							seqg_var->SET[seqg_var->j] = 0;
# line 799 "../filterDrive.st"
							seq_pvPutTmo(seqg_env, 142/*SET*/ + (CH_ID)(seqg_var->j), DEFAULT, DEFAULT_TIMEOUT);
						}
					}
				}
# line 805 "../filterDrive.st"
				if (seqg_var->doWait)
				{
# line 806 "../filterDrive.st"
					seq_pvGetTmo(seqg_env, 13/*FILTER_WAIT_TIME*/, DEFAULT, DEFAULT_TIMEOUT);
# line 807 "../filterDrive.st"
					epicsThreadSleep(seqg_var->FILTER_WAIT_TIME);
				}
			}
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{P}{R}Status", offsetof(struct seqg_vars, STATUS_BUSY), "STATUS_BUSY", P_INT, 1, 6, 0, 1, 0, 0},
	{"{P}{R}NumFilters", offsetof(struct seqg_vars, NFILTERS), "NFILTERS", P_INT, 1, 7, 0, 0, 0, 0},
	{"{P}{R}Debug", offsetof(struct seqg_vars, DEBUG), "DEBUG", P_INT, 1, 8, 0, 1, 0, 0},
	{"{P}{R}Transmission", offsetof(struct seqg_vars, TRANSMISSION), "TRANSMISSION", P_DOUBLE, 1, 9, 0, 0, 0, 0},
	{"{P}{R}TransmissionUp", offsetof(struct seqg_vars, TRANSMISSION_UP), "TRANSMISSION_UP", P_DOUBLE, 1, 10, 0, 0, 0, 0},
	{"{P}{R}TransmissionDown", offsetof(struct seqg_vars, TRANSMISSION_DOWN), "TRANSMISSION_DOWN", P_DOUBLE, 1, 11, 0, 0, 0, 0},
	{"{P}{R}FilterMask", offsetof(struct seqg_vars, FILTER_MASK), "FILTER_MASK", P_INT, 1, 12, 0, 0, 0, 0},
	{"{P}{R}TransmissionSetpoint", offsetof(struct seqg_vars, TRANSM_SETPT), "TRANSM_SETPT", P_DOUBLE, 1, 13, 1, 1, 0, 0},
	{"{P}{R}FilterMaskSetpoint", offsetof(struct seqg_vars, FILTERMASK_SETPT), "FILTERMASK_SETPT", P_INT, 1, 14, 2, 1, 0, 0},
	{"{P}{R}TransmissionStepUp", offsetof(struct seqg_vars, TRANSM_UP), "TRANSM_UP", P_INT, 1, 15, 0, 1, 0, 0},
	{"{P}{R}TransmissionStepDown", offsetof(struct seqg_vars, TRANSM_DN), "TRANSM_DN", P_INT, 1, 16, 0, 1, 0, 0},
	{"{P}{R}Energy", offsetof(struct seqg_vars, ENERGY), "ENERGY", P_DOUBLE, 1, 17, 4, 1, 0, 0},
	{"{P}{R}Message", offsetof(struct seqg_vars, MSGE), "MSGE", P_STRING, 1, 18, 0, 0, 0, 0},
	{"{P}{R}WaitTime", offsetof(struct seqg_vars, FILTER_WAIT_TIME), "FILTER_WAIT_TIME", P_DOUBLE, 1, 19, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[0]), "TRANSM[0]", P_DOUBLE, 1, 20, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[1]), "TRANSM[1]", P_DOUBLE, 1, 21, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[2]), "TRANSM[2]", P_DOUBLE, 1, 22, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[3]), "TRANSM[3]", P_DOUBLE, 1, 23, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[4]), "TRANSM[4]", P_DOUBLE, 1, 24, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[5]), "TRANSM[5]", P_DOUBLE, 1, 25, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[6]), "TRANSM[6]", P_DOUBLE, 1, 26, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[7]), "TRANSM[7]", P_DOUBLE, 1, 27, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[8]), "TRANSM[8]", P_DOUBLE, 1, 28, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[9]), "TRANSM[9]", P_DOUBLE, 1, 29, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[10]), "TRANSM[10]", P_DOUBLE, 1, 30, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[11]), "TRANSM[11]", P_DOUBLE, 1, 31, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[12]), "TRANSM[12]", P_DOUBLE, 1, 32, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[13]), "TRANSM[13]", P_DOUBLE, 1, 33, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[14]), "TRANSM[14]", P_DOUBLE, 1, 34, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[15]), "TRANSM[15]", P_DOUBLE, 1, 35, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[16]), "TRANSM[16]", P_DOUBLE, 1, 36, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[17]), "TRANSM[17]", P_DOUBLE, 1, 37, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[18]), "TRANSM[18]", P_DOUBLE, 1, 38, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[19]), "TRANSM[19]", P_DOUBLE, 1, 39, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[20]), "TRANSM[20]", P_DOUBLE, 1, 40, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[21]), "TRANSM[21]", P_DOUBLE, 1, 41, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[22]), "TRANSM[22]", P_DOUBLE, 1, 42, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[23]), "TRANSM[23]", P_DOUBLE, 1, 43, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[24]), "TRANSM[24]", P_DOUBLE, 1, 44, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[25]), "TRANSM[25]", P_DOUBLE, 1, 45, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[26]), "TRANSM[26]", P_DOUBLE, 1, 46, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[27]), "TRANSM[27]", P_DOUBLE, 1, 47, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[28]), "TRANSM[28]", P_DOUBLE, 1, 48, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[29]), "TRANSM[29]", P_DOUBLE, 1, 49, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[30]), "TRANSM[30]", P_DOUBLE, 1, 50, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, TRANSM[31]), "TRANSM[31]", P_DOUBLE, 1, 51, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[0]), "THICK[0]", P_DOUBLE, 1, 52, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[1]), "THICK[1]", P_DOUBLE, 1, 53, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[2]), "THICK[2]", P_DOUBLE, 1, 54, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[3]), "THICK[3]", P_DOUBLE, 1, 55, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[4]), "THICK[4]", P_DOUBLE, 1, 56, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[5]), "THICK[5]", P_DOUBLE, 1, 57, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[6]), "THICK[6]", P_DOUBLE, 1, 58, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[7]), "THICK[7]", P_DOUBLE, 1, 59, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[8]), "THICK[8]", P_DOUBLE, 1, 60, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[9]), "THICK[9]", P_DOUBLE, 1, 61, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[10]), "THICK[10]", P_DOUBLE, 1, 62, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[11]), "THICK[11]", P_DOUBLE, 1, 63, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[12]), "THICK[12]", P_DOUBLE, 1, 64, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[13]), "THICK[13]", P_DOUBLE, 1, 65, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[14]), "THICK[14]", P_DOUBLE, 1, 66, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[15]), "THICK[15]", P_DOUBLE, 1, 67, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[16]), "THICK[16]", P_DOUBLE, 1, 68, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[17]), "THICK[17]", P_DOUBLE, 1, 69, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[18]), "THICK[18]", P_DOUBLE, 1, 70, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[19]), "THICK[19]", P_DOUBLE, 1, 71, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[20]), "THICK[20]", P_DOUBLE, 1, 72, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[21]), "THICK[21]", P_DOUBLE, 1, 73, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[22]), "THICK[22]", P_DOUBLE, 1, 74, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[23]), "THICK[23]", P_DOUBLE, 1, 75, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[24]), "THICK[24]", P_DOUBLE, 1, 76, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[25]), "THICK[25]", P_DOUBLE, 1, 77, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[26]), "THICK[26]", P_DOUBLE, 1, 78, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[27]), "THICK[27]", P_DOUBLE, 1, 79, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[28]), "THICK[28]", P_DOUBLE, 1, 80, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[29]), "THICK[29]", P_DOUBLE, 1, 81, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[30]), "THICK[30]", P_DOUBLE, 1, 82, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, THICK[31]), "THICK[31]", P_DOUBLE, 1, 83, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[0]), "MATER[0]", P_STRING, 1, 84, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[1]), "MATER[1]", P_STRING, 1, 85, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[2]), "MATER[2]", P_STRING, 1, 86, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[3]), "MATER[3]", P_STRING, 1, 87, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[4]), "MATER[4]", P_STRING, 1, 88, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[5]), "MATER[5]", P_STRING, 1, 89, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[6]), "MATER[6]", P_STRING, 1, 90, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[7]), "MATER[7]", P_STRING, 1, 91, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[8]), "MATER[8]", P_STRING, 1, 92, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[9]), "MATER[9]", P_STRING, 1, 93, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[10]), "MATER[10]", P_STRING, 1, 94, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[11]), "MATER[11]", P_STRING, 1, 95, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[12]), "MATER[12]", P_STRING, 1, 96, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[13]), "MATER[13]", P_STRING, 1, 97, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[14]), "MATER[14]", P_STRING, 1, 98, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[15]), "MATER[15]", P_STRING, 1, 99, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[16]), "MATER[16]", P_STRING, 1, 100, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[17]), "MATER[17]", P_STRING, 1, 101, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[18]), "MATER[18]", P_STRING, 1, 102, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[19]), "MATER[19]", P_STRING, 1, 103, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[20]), "MATER[20]", P_STRING, 1, 104, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[21]), "MATER[21]", P_STRING, 1, 105, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[22]), "MATER[22]", P_STRING, 1, 106, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[23]), "MATER[23]", P_STRING, 1, 107, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[24]), "MATER[24]", P_STRING, 1, 108, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[25]), "MATER[25]", P_STRING, 1, 109, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[26]), "MATER[26]", P_STRING, 1, 110, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[27]), "MATER[27]", P_STRING, 1, 111, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[28]), "MATER[28]", P_STRING, 1, 112, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[29]), "MATER[29]", P_STRING, 1, 113, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[30]), "MATER[30]", P_STRING, 1, 114, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, MATER[31]), "MATER[31]", P_STRING, 1, 115, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[0]), "LOCK[0]", P_INT, 1, 116, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[1]), "LOCK[1]", P_INT, 1, 117, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[2]), "LOCK[2]", P_INT, 1, 118, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[3]), "LOCK[3]", P_INT, 1, 119, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[4]), "LOCK[4]", P_INT, 1, 120, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[5]), "LOCK[5]", P_INT, 1, 121, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[6]), "LOCK[6]", P_INT, 1, 122, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[7]), "LOCK[7]", P_INT, 1, 123, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[8]), "LOCK[8]", P_INT, 1, 124, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[9]), "LOCK[9]", P_INT, 1, 125, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[10]), "LOCK[10]", P_INT, 1, 126, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[11]), "LOCK[11]", P_INT, 1, 127, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[12]), "LOCK[12]", P_INT, 1, 128, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[13]), "LOCK[13]", P_INT, 1, 129, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[14]), "LOCK[14]", P_INT, 1, 130, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[15]), "LOCK[15]", P_INT, 1, 131, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[16]), "LOCK[16]", P_INT, 1, 132, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[17]), "LOCK[17]", P_INT, 1, 133, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[18]), "LOCK[18]", P_INT, 1, 134, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[19]), "LOCK[19]", P_INT, 1, 135, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[20]), "LOCK[20]", P_INT, 1, 136, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[21]), "LOCK[21]", P_INT, 1, 137, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[22]), "LOCK[22]", P_INT, 1, 138, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[23]), "LOCK[23]", P_INT, 1, 139, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[24]), "LOCK[24]", P_INT, 1, 140, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[25]), "LOCK[25]", P_INT, 1, 141, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[26]), "LOCK[26]", P_INT, 1, 142, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[27]), "LOCK[27]", P_INT, 1, 143, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[28]), "LOCK[28]", P_INT, 1, 144, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[29]), "LOCK[29]", P_INT, 1, 145, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[30]), "LOCK[30]", P_INT, 1, 146, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, LOCK[31]), "LOCK[31]", P_INT, 1, 147, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[0]), "SET[0]", P_INT, 1, 148, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[1]), "SET[1]", P_INT, 1, 149, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[2]), "SET[2]", P_INT, 1, 150, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[3]), "SET[3]", P_INT, 1, 151, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[4]), "SET[4]", P_INT, 1, 152, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[5]), "SET[5]", P_INT, 1, 153, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[6]), "SET[6]", P_INT, 1, 154, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[7]), "SET[7]", P_INT, 1, 155, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[8]), "SET[8]", P_INT, 1, 156, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[9]), "SET[9]", P_INT, 1, 157, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[10]), "SET[10]", P_INT, 1, 158, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[11]), "SET[11]", P_INT, 1, 159, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[12]), "SET[12]", P_INT, 1, 160, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[13]), "SET[13]", P_INT, 1, 161, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[14]), "SET[14]", P_INT, 1, 162, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[15]), "SET[15]", P_INT, 1, 163, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[16]), "SET[16]", P_INT, 1, 164, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[17]), "SET[17]", P_INT, 1, 165, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[18]), "SET[18]", P_INT, 1, 166, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[19]), "SET[19]", P_INT, 1, 167, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[20]), "SET[20]", P_INT, 1, 168, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[21]), "SET[21]", P_INT, 1, 169, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[22]), "SET[22]", P_INT, 1, 170, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[23]), "SET[23]", P_INT, 1, 171, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[24]), "SET[24]", P_INT, 1, 172, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[25]), "SET[25]", P_INT, 1, 173, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[26]), "SET[26]", P_INT, 1, 174, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[27]), "SET[27]", P_INT, 1, 175, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[28]), "SET[28]", P_INT, 1, 176, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[29]), "SET[29]", P_INT, 1, 177, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[30]), "SET[30]", P_INT, 1, 178, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, SET[31]), "SET[31]", P_INT, 1, 179, 0, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[0]), "ENBL[0]", P_INT, 1, 180, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[1]), "ENBL[1]", P_INT, 1, 181, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[2]), "ENBL[2]", P_INT, 1, 182, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[3]), "ENBL[3]", P_INT, 1, 183, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[4]), "ENBL[4]", P_INT, 1, 184, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[5]), "ENBL[5]", P_INT, 1, 185, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[6]), "ENBL[6]", P_INT, 1, 186, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[7]), "ENBL[7]", P_INT, 1, 187, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[8]), "ENBL[8]", P_INT, 1, 188, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[9]), "ENBL[9]", P_INT, 1, 189, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[10]), "ENBL[10]", P_INT, 1, 190, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[11]), "ENBL[11]", P_INT, 1, 191, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[12]), "ENBL[12]", P_INT, 1, 192, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[13]), "ENBL[13]", P_INT, 1, 193, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[14]), "ENBL[14]", P_INT, 1, 194, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[15]), "ENBL[15]", P_INT, 1, 195, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[16]), "ENBL[16]", P_INT, 1, 196, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[17]), "ENBL[17]", P_INT, 1, 197, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[18]), "ENBL[18]", P_INT, 1, 198, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[19]), "ENBL[19]", P_INT, 1, 199, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[20]), "ENBL[20]", P_INT, 1, 200, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[21]), "ENBL[21]", P_INT, 1, 201, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[22]), "ENBL[22]", P_INT, 1, 202, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[23]), "ENBL[23]", P_INT, 1, 203, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[24]), "ENBL[24]", P_INT, 1, 204, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[25]), "ENBL[25]", P_INT, 1, 205, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[26]), "ENBL[26]", P_INT, 1, 206, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[27]), "ENBL[27]", P_INT, 1, 207, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[28]), "ENBL[28]", P_INT, 1, 208, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[29]), "ENBL[29]", P_INT, 1, 209, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[30]), "ENBL[30]", P_INT, 1, 210, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, ENBL[31]), "ENBL[31]", P_INT, 1, 211, 3, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[0]), "OUT[0]", P_INT, 1, 212, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[1]), "OUT[1]", P_INT, 1, 213, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[2]), "OUT[2]", P_INT, 1, 214, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[3]), "OUT[3]", P_INT, 1, 215, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[4]), "OUT[4]", P_INT, 1, 216, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[5]), "OUT[5]", P_INT, 1, 217, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[6]), "OUT[6]", P_INT, 1, 218, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[7]), "OUT[7]", P_INT, 1, 219, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[8]), "OUT[8]", P_INT, 1, 220, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[9]), "OUT[9]", P_INT, 1, 221, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[10]), "OUT[10]", P_INT, 1, 222, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[11]), "OUT[11]", P_INT, 1, 223, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[12]), "OUT[12]", P_INT, 1, 224, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[13]), "OUT[13]", P_INT, 1, 225, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[14]), "OUT[14]", P_INT, 1, 226, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[15]), "OUT[15]", P_INT, 1, 227, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[16]), "OUT[16]", P_INT, 1, 228, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[17]), "OUT[17]", P_INT, 1, 229, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[18]), "OUT[18]", P_INT, 1, 230, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[19]), "OUT[19]", P_INT, 1, 231, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[20]), "OUT[20]", P_INT, 1, 232, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[21]), "OUT[21]", P_INT, 1, 233, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[22]), "OUT[22]", P_INT, 1, 234, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[23]), "OUT[23]", P_INT, 1, 235, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[24]), "OUT[24]", P_INT, 1, 236, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[25]), "OUT[25]", P_INT, 1, 237, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[26]), "OUT[26]", P_INT, 1, 238, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[27]), "OUT[27]", P_INT, 1, 239, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[28]), "OUT[28]", P_INT, 1, 240, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[29]), "OUT[29]", P_INT, 1, 241, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[30]), "OUT[30]", P_INT, 1, 242, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUT[31]), "OUT[31]", P_INT, 1, 243, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[0]), "OUTGET[0]", P_INT, 1, 244, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[1]), "OUTGET[1]", P_INT, 1, 245, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[2]), "OUTGET[2]", P_INT, 1, 246, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[3]), "OUTGET[3]", P_INT, 1, 247, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[4]), "OUTGET[4]", P_INT, 1, 248, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[5]), "OUTGET[5]", P_INT, 1, 249, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[6]), "OUTGET[6]", P_INT, 1, 250, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[7]), "OUTGET[7]", P_INT, 1, 251, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[8]), "OUTGET[8]", P_INT, 1, 252, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[9]), "OUTGET[9]", P_INT, 1, 253, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[10]), "OUTGET[10]", P_INT, 1, 254, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[11]), "OUTGET[11]", P_INT, 1, 255, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[12]), "OUTGET[12]", P_INT, 1, 256, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[13]), "OUTGET[13]", P_INT, 1, 257, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[14]), "OUTGET[14]", P_INT, 1, 258, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[15]), "OUTGET[15]", P_INT, 1, 259, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[16]), "OUTGET[16]", P_INT, 1, 260, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[17]), "OUTGET[17]", P_INT, 1, 261, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[18]), "OUTGET[18]", P_INT, 1, 262, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[19]), "OUTGET[19]", P_INT, 1, 263, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[20]), "OUTGET[20]", P_INT, 1, 264, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[21]), "OUTGET[21]", P_INT, 1, 265, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[22]), "OUTGET[22]", P_INT, 1, 266, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[23]), "OUTGET[23]", P_INT, 1, 267, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[24]), "OUTGET[24]", P_INT, 1, 268, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[25]), "OUTGET[25]", P_INT, 1, 269, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[26]), "OUTGET[26]", P_INT, 1, 270, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[27]), "OUTGET[27]", P_INT, 1, 271, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[28]), "OUTGET[28]", P_INT, 1, 272, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[29]), "OUTGET[29]", P_INT, 1, 273, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[30]), "OUTGET[30]", P_INT, 1, 274, 5, 1, 0, 0},
	{"", offsetof(struct seqg_vars, OUTGET[31]), "OUTGET[31]", P_INT, 1, 275, 5, 1, 0, 0},
};

/* Event masks for state set "filterDrive" */
static const seqMask seqg_mask_filterDrive_0_start[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_filterDrive_0_init[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_filterDrive_0_waiting[] = {
	0x0001807e,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_filterDrive_0_update_filters[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_filterDrive_0_action[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_filterDrive_0_change_filters[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "filterDrive" */
static seqState seqg_states_filterDrive[] = {
	{
	/* state name */        "start",
	/* action function */   seqg_action_filterDrive_0_start,
	/* event function */    seqg_event_filterDrive_0_start,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_filterDrive_0_start,
	/* state options */     (0)
	},
	{
	/* state name */        "init",
	/* action function */   seqg_action_filterDrive_0_init,
	/* event function */    seqg_event_filterDrive_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_filterDrive_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "waiting",
	/* action function */   seqg_action_filterDrive_0_waiting,
	/* event function */    seqg_event_filterDrive_0_waiting,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_filterDrive_0_waiting,
	/* state options */     (0)
	},
	{
	/* state name */        "update_filters",
	/* action function */   seqg_action_filterDrive_0_update_filters,
	/* event function */    seqg_event_filterDrive_0_update_filters,
	/* entry function */    seqg_entry_filterDrive_0_update_filters,
	/* exit function */     0,
	/* event mask array */  seqg_mask_filterDrive_0_update_filters,
	/* state options */     (0)
	},
	{
	/* state name */        "action",
	/* action function */   seqg_action_filterDrive_0_action,
	/* event function */    seqg_event_filterDrive_0_action,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_filterDrive_0_action,
	/* state options */     (0)
	},
	{
	/* state name */        "change_filters",
	/* action function */   seqg_action_filterDrive_0_change_filters,
	/* event function */    seqg_event_filterDrive_0_change_filters,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_filterDrive_0_change_filters,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "filterDrive",
	/* states */            seqg_states_filterDrive,
	/* number of states */  6
	},
};

/* Program table (global) */
seqProgram filterDrive = {
	/* magic number */      2002005,
	/* program name */      "filterDrive",
	/* channels */          seqg_chans,
	/* num. channels */     270,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "NAME=filterDrive, P=TEST:, R=filter:, NUM_FILTERS=8",
	/* num. event flags */  5,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void filterDriveRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&filterDrive);
}
epicsExportRegistrar(filterDriveRegistrar);
