/* C code for program Io, generated by snc from ../Io.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 18 "../Io.st"
#include "epicsThread.h"
# line 52 "../Io.st"
static const EF_ID Emono_mon = 1;
# line 54 "../Io.st"
static const EF_ID cnt_mon = 2;
# line 56 "../Io.st"
static const EF_ID ticks_mon = 3;
# line 92 "../Io.st"
static const EF_ID IoDebug_mon = 4;
# line 93 "../Io.st"
static const EF_ID icChannel_mon = 5;
# line 95 "../Io.st"
static const EF_ID E_using_mon = 6;
# line 96 "../Io.st"
static const EF_ID VperA_mon = 7;
# line 97 "../Io.st"
static const EF_ID v2f_mon = 8;
# line 98 "../Io.st"
static const EF_ID xN2_mon = 9;
# line 99 "../Io.st"
static const EF_ID xAr_mon = 10;
# line 100 "../Io.st"
static const EF_ID xHe_mon = 11;
# line 101 "../Io.st"
static const EF_ID xAir_mon = 12;
# line 102 "../Io.st"
static const EF_ID xCO2_mon = 13;
# line 103 "../Io.st"
static const EF_ID activeLen_mon = 14;
# line 104 "../Io.st"
static const EF_ID deadFront_mon = 15;
# line 105 "../Io.st"
static const EF_ID deadRear_mon = 16;
# line 106 "../Io.st"
static const EF_ID kapton1_mon = 17;
# line 107 "../Io.st"
static const EF_ID kapton2_mon = 18;
# line 108 "../Io.st"
static const EF_ID HePath_mon = 19;
# line 109 "../Io.st"
static const EF_ID airPath_mon = 20;
# line 110 "../Io.st"
static const EF_ID Be_mon = 21;
# line 111 "../Io.st"
static const EF_ID dEff_mon = 22;
# line 112 "../Io.st"
static const EF_ID ArPcntr_mon = 23;
# line 119 "../Io.st"
#include <stdlib.h>
# line 120 "../Io.st"
#include <math.h>
# line 122 "../Io.st"
static void EvalFlux(double aln, double dln1, double dln2, double dHe, double dAir, double dBe, double energy);
# line 123 "../Io.st"
static double photon(double cps, double work, double VtoF, double Volt_per_A, double aln, double deadL, double Kapton, int gasId, double energy);
# line 124 "../Io.st"
static double absorb(int id, double energy);
# line 125 "../Io.st"
static double absH(double energy);
# line 126 "../Io.st"
static double absHe(double energy);
# line 127 "../Io.st"
static double absBe(double energy);
# line 128 "../Io.st"
static double absC(double energy);
# line 129 "../Io.st"
static double absN(double energy);
# line 130 "../Io.st"
static double absO(double energy);
# line 131 "../Io.st"
static double absAr(double energy);
# line 132 "../Io.st"
static double absArPhoto(double energy);

/* Variable declarations */
# line 52 "../Io.st"
static	double Emono;
# line 54 "../Io.st"
static	short cnt;
# line 55 "../Io.st"
static	double clock_rate;
# line 56 "../Io.st"
static	double ticks;
# line 57 "../Io.st"
static	double s2;
# line 58 "../Io.st"
static	double s3;
# line 59 "../Io.st"
static	double s4;
# line 60 "../Io.st"
static	double s5;
# line 61 "../Io.st"
static	double s6;
# line 62 "../Io.st"
static	double s7;
# line 63 "../Io.st"
static	double s8;
# line 64 "../Io.st"
static	double s9;
# line 65 "../Io.st"
static	double s10;
# line 66 "../Io.st"
static	double s11;
# line 67 "../Io.st"
static	double s12;
# line 68 "../Io.st"
static	double s13;
# line 69 "../Io.st"
static	double s14;
# line 70 "../Io.st"
static	double s15;
# line 72 "../Io.st"
static	string nm2;
# line 73 "../Io.st"
static	string nm3;
# line 74 "../Io.st"
static	string nm4;
# line 75 "../Io.st"
static	string nm5;
# line 76 "../Io.st"
static	string nm6;
# line 77 "../Io.st"
static	string nm7;
# line 78 "../Io.st"
static	string nm8;
# line 79 "../Io.st"
static	string nm9;
# line 80 "../Io.st"
static	string nm10;
# line 81 "../Io.st"
static	string nm11;
# line 82 "../Io.st"
static	string nm12;
# line 83 "../Io.st"
static	string nm13;
# line 84 "../Io.st"
static	string nm14;
# line 85 "../Io.st"
static	string nm15;
# line 87 "../Io.st"
static	double flux;
# line 88 "../Io.st"
static	double ionPhotons;
# line 89 "../Io.st"
static	double ionAbs;
# line 90 "../Io.st"
static	double detector;
# line 92 "../Io.st"
static	short IoDebug;
# line 93 "../Io.st"
static	short icChannel;
# line 94 "../Io.st"
static	string icName;
# line 95 "../Io.st"
static	double E_using;
# line 96 "../Io.st"
static	double VperA;
# line 97 "../Io.st"
static	double v2f;
# line 98 "../Io.st"
static	double xN2;
# line 99 "../Io.st"
static	double xAr;
# line 100 "../Io.st"
static	double xHe;
# line 101 "../Io.st"
static	double xAir;
# line 102 "../Io.st"
static	double xCO2;
# line 103 "../Io.st"
static	double activeLen;
# line 104 "../Io.st"
static	double deadFront;
# line 105 "../Io.st"
static	double deadRear;
# line 106 "../Io.st"
static	double kapton1;
# line 107 "../Io.st"
static	double kapton2;
# line 108 "../Io.st"
static	double HePath;
# line 109 "../Io.st"
static	double airPath;
# line 110 "../Io.st"
static	double Be;
# line 111 "../Io.st"
static	double dEff;
# line 112 "../Io.st"
static	short ArPcntr;
# line 114 "../Io.st"
static	char new_msg[256];
# line 115 "../Io.st"
static	double updateRate;
# line 116 "../Io.st"
static	char *SNLtaskName;
# line 117 "../Io.st"
static	short Io_debug;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "ionChamber" ******/

/* Event function for state "init" in state set "ionChamber" */
static seqBool seqg_event_ionChamber_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "ionChamber" */
static void seqg_action_ionChamber_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 149 "../Io.st"
			SNLtaskName = seq_macValueGet(seqg_env, "name");
# line 150 "../Io.st"
			Io_debug = 0;
# line 151 "../Io.st"
			if (Io_debug >= 1)
			{
# line 151 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 151, SNLtaskName, "init start");
# line 151 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 151 "../Io.st"
			;
# line 152 "../Io.st"
			IoDebug = Io_debug;
# line 153 "../Io.st"
			seq_efClear(seqg_env, IoDebug_mon);
# line 154 "../Io.st"
			updateRate = 10.0;
# line 155 "../Io.st"
			seq_pvGetTmo(seqg_env, 0/*Emono*/, DEFAULT, DEFAULT_TIMEOUT);
# line 156 "../Io.st"
			seq_pvGetTmo(seqg_env, 40/*VperA*/, DEFAULT, DEFAULT_TIMEOUT);
# line 157 "../Io.st"
			seq_pvGetTmo(seqg_env, 2/*clock_rate*/, DEFAULT, DEFAULT_TIMEOUT);
# line 158 "../Io.st"
			seq_pvGetTmo(seqg_env, 3/*ticks*/, DEFAULT, DEFAULT_TIMEOUT);
# line 159 "../Io.st"
			seq_pvGetTmo(seqg_env, 4/*s2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 160 "../Io.st"
			seq_pvGetTmo(seqg_env, 5/*s3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 161 "../Io.st"
			seq_pvGetTmo(seqg_env, 6/*s4*/, DEFAULT, DEFAULT_TIMEOUT);
# line 162 "../Io.st"
			seq_pvGetTmo(seqg_env, 7/*s5*/, DEFAULT, DEFAULT_TIMEOUT);
# line 163 "../Io.st"
			seq_pvGetTmo(seqg_env, 8/*s6*/, DEFAULT, DEFAULT_TIMEOUT);
# line 164 "../Io.st"
			seq_pvGetTmo(seqg_env, 9/*s7*/, DEFAULT, DEFAULT_TIMEOUT);
# line 165 "../Io.st"
			seq_pvGetTmo(seqg_env, 10/*s8*/, DEFAULT, DEFAULT_TIMEOUT);
# line 166 "../Io.st"
			seq_pvGetTmo(seqg_env, 11/*s9*/, DEFAULT, DEFAULT_TIMEOUT);
# line 167 "../Io.st"
			seq_pvGetTmo(seqg_env, 12/*s10*/, DEFAULT, DEFAULT_TIMEOUT);
# line 168 "../Io.st"
			seq_pvGetTmo(seqg_env, 13/*s11*/, DEFAULT, DEFAULT_TIMEOUT);
# line 169 "../Io.st"
			seq_pvGetTmo(seqg_env, 14/*s12*/, DEFAULT, DEFAULT_TIMEOUT);
# line 170 "../Io.st"
			seq_pvGetTmo(seqg_env, 15/*s13*/, DEFAULT, DEFAULT_TIMEOUT);
# line 171 "../Io.st"
			seq_pvGetTmo(seqg_env, 16/*s14*/, DEFAULT, DEFAULT_TIMEOUT);
# line 172 "../Io.st"
			seq_pvGetTmo(seqg_env, 17/*s15*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 174 "../Io.st"
				icChannel = (2);
# line 174 "../Io.st"
				seq_pvPutTmo(seqg_env, 37/*icChannel*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 175 "../Io.st"
				VperA = (100000000.);
# line 175 "../Io.st"
				seq_pvPutTmo(seqg_env, 40/*VperA*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 176 "../Io.st"
				v2f = (100000.);
# line 176 "../Io.st"
				seq_pvPutTmo(seqg_env, 41/*v2f*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 177 "../Io.st"
				xAir = (1.);
# line 177 "../Io.st"
				seq_pvPutTmo(seqg_env, 45/*xAir*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 178 "../Io.st"
				xN2 = (0.);
# line 178 "../Io.st"
				seq_pvPutTmo(seqg_env, 42/*xN2*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 179 "../Io.st"
				xAr = (0.);
# line 179 "../Io.st"
				seq_pvPutTmo(seqg_env, 43/*xAr*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 180 "../Io.st"
				xHe = (0.);
# line 180 "../Io.st"
				seq_pvPutTmo(seqg_env, 44/*xHe*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 181 "../Io.st"
				xCO2 = (0.);
# line 181 "../Io.st"
				seq_pvPutTmo(seqg_env, 46/*xCO2*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 182 "../Io.st"
				activeLen = (60.);
# line 182 "../Io.st"
				seq_pvPutTmo(seqg_env, 47/*activeLen*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 183 "../Io.st"
				deadFront = (17.5);
# line 183 "../Io.st"
				seq_pvPutTmo(seqg_env, 48/*deadFront*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 184 "../Io.st"
				deadRear = (17.5);
# line 184 "../Io.st"
				seq_pvPutTmo(seqg_env, 49/*deadRear*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 185 "../Io.st"
				kapton1 = (.001);
# line 185 "../Io.st"
				seq_pvPutTmo(seqg_env, 50/*kapton1*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 186 "../Io.st"
				kapton2 = (.001);
# line 186 "../Io.st"
				seq_pvPutTmo(seqg_env, 51/*kapton2*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 187 "../Io.st"
				HePath = (0.);
# line 187 "../Io.st"
				seq_pvPutTmo(seqg_env, 52/*HePath*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 188 "../Io.st"
				airPath = (0.);
# line 188 "../Io.st"
				seq_pvPutTmo(seqg_env, 53/*airPath*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 189 "../Io.st"
				Be = (0.);
# line 189 "../Io.st"
				seq_pvPutTmo(seqg_env, 54/*Be*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 190 "../Io.st"
				dEff = (1.);
# line 190 "../Io.st"
				seq_pvPutTmo(seqg_env, 55/*dEff*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 191 "../Io.st"
				ArPcntr = (0);
# line 191 "../Io.st"
				seq_pvPutTmo(seqg_env, 56/*ArPcntr*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 192 "../Io.st"
				flux = (0.);
# line 192 "../Io.st"
				seq_pvPutTmo(seqg_env, 32/*flux*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 193 "../Io.st"
				ionPhotons = (0.);
# line 193 "../Io.st"
				seq_pvPutTmo(seqg_env, 33/*ionPhotons*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 194 "../Io.st"
				ionAbs = (1.);
# line 194 "../Io.st"
				seq_pvPutTmo(seqg_env, 34/*ionAbs*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 195 "../Io.st"
				detector = (0.);
# line 195 "../Io.st"
				seq_pvPutTmo(seqg_env, 35/*detector*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			{
# line 197 "../Io.st"
				E_using = (Emono);
# line 197 "../Io.st"
				seq_pvPutTmo(seqg_env, 39/*E_using*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 197 "../Io.st"
			;
# line 198 "../Io.st"
			seq_efClear(seqg_env, Emono_mon);
# line 199 "../Io.st"
			seq_efClear(seqg_env, E_using_mon);
# line 200 "../Io.st"
			seq_efClear(seqg_env, VperA_mon);
# line 201 "../Io.st"
			seq_efClear(seqg_env, cnt_mon);
# line 202 "../Io.st"
			seq_efClear(seqg_env, ticks_mon);
# line 203 "../Io.st"
			seq_efClear(seqg_env, icChannel_mon);
# line 204 "../Io.st"
			seq_efClear(seqg_env, v2f_mon);
# line 205 "../Io.st"
			seq_efClear(seqg_env, xN2_mon);
# line 206 "../Io.st"
			seq_efClear(seqg_env, xAr_mon);
# line 207 "../Io.st"
			seq_efClear(seqg_env, xHe_mon);
# line 208 "../Io.st"
			seq_efClear(seqg_env, xAir_mon);
# line 209 "../Io.st"
			seq_efClear(seqg_env, xCO2_mon);
# line 210 "../Io.st"
			seq_efClear(seqg_env, activeLen_mon);
# line 211 "../Io.st"
			seq_efClear(seqg_env, deadFront_mon);
# line 212 "../Io.st"
			seq_efClear(seqg_env, deadRear_mon);
# line 213 "../Io.st"
			seq_efClear(seqg_env, kapton1_mon);
# line 214 "../Io.st"
			seq_efClear(seqg_env, kapton2_mon);
# line 215 "../Io.st"
			seq_efClear(seqg_env, HePath_mon);
# line 216 "../Io.st"
			seq_efClear(seqg_env, airPath_mon);
# line 217 "../Io.st"
			seq_efClear(seqg_env, Be_mon);
# line 218 "../Io.st"
			seq_efClear(seqg_env, dEff_mon);
# line 219 "../Io.st"
			seq_efClear(seqg_env, ArPcntr_mon);
# line 221 "../Io.st"
			if (Io_debug >= 1)
			{
# line 221 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 221, SNLtaskName, "init complete");
# line 221 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 221 "../Io.st"
			;
		}
		return;
	}
}

/****** Code for state "idle" in state set "ionChamber" ******/

/* Event function for state "idle" in state set "ionChamber" */
static seqBool seqg_event_ionChamber_0_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 227 "../Io.st"
	if (seq_efTestAndClear(seqg_env, IoDebug_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 235 "../Io.st"
	if (seq_efTestAndClear(seqg_env, E_using_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 241 "../Io.st"
	if (seq_efTestAndClear(seqg_env, Emono_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 249 "../Io.st"
	if (seq_efTestAndClear(seqg_env, VperA_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 256 "../Io.st"
	if (seq_efTestAndClear(seqg_env, ArPcntr_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 269 "../Io.st"
	if (seq_efTestAndClear(seqg_env, dEff_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 5;
		return TRUE;
	}
# line 278 "../Io.st"
	if (seq_efTestAndClear(seqg_env, icChannel_mon) || seq_efTestAndClear(seqg_env, v2f_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 6;
		return TRUE;
	}
# line 287 "../Io.st"
	if (seq_efTestAndClear(seqg_env, xN2_mon) || seq_efTestAndClear(seqg_env, xHe_mon) || seq_efTestAndClear(seqg_env, xAr_mon) || seq_efTestAndClear(seqg_env, xAir_mon) || seq_efTestAndClear(seqg_env, xCO2_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 7;
		return TRUE;
	}
# line 302 "../Io.st"
	if (seq_efTestAndClear(seqg_env, activeLen_mon) || seq_efTestAndClear(seqg_env, deadFront_mon) || seq_efTestAndClear(seqg_env, deadRear_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 8;
		return TRUE;
	}
# line 313 "../Io.st"
	if (seq_efTestAndClear(seqg_env, HePath_mon) || seq_efTestAndClear(seqg_env, airPath_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 9;
		return TRUE;
	}
# line 322 "../Io.st"
	if (seq_efTestAndClear(seqg_env, kapton1_mon) || seq_efTestAndClear(seqg_env, kapton2_mon) || seq_efTestAndClear(seqg_env, Be_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 10;
		return TRUE;
	}
# line 333 "../Io.st"
	if (seq_efTestAndClear(seqg_env, cnt_mon) || seq_efTestAndClear(seqg_env, ticks_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 11;
		return TRUE;
	}
# line 340 "../Io.st"
	if (seq_delay(seqg_env, updateRate))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 12;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "ionChamber" */
static void seqg_action_ionChamber_0_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 228 "../Io.st"
			seq_pvGetTmo(seqg_env, 36/*IoDebug*/, DEFAULT, DEFAULT_TIMEOUT);
# line 229 "../Io.st"
			Io_debug = IoDebug;
# line 230 "../Io.st"
			seq_efClear(seqg_env, IoDebug_mon);
# line 231 "../Io.st"
			sprintf(new_msg, "changed debug flag to %d", Io_debug);
# line 232 "../Io.st"
			if (Io_debug >= 1)
			{
# line 232 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 232, SNLtaskName, new_msg);
# line 232 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 232 "../Io.st"
			;
		}
		return;
	case 1:
		{
# line 236 "../Io.st"
			if (Io_debug >= 1)
			{
# line 236 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 236, SNLtaskName, "monochromator energy (pretend) changed");
# line 236 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 236 "../Io.st"
			;
# line 237 "../Io.st"
			seq_pvGetTmo(seqg_env, 39/*E_using*/, DEFAULT, DEFAULT_TIMEOUT);
# line 238 "../Io.st"
			seq_efClear(seqg_env, E_using_mon);
		}
		return;
	case 2:
		{
# line 242 "../Io.st"
			if (Io_debug >= 2)
			{
# line 242 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 242, SNLtaskName, "monochromator (actual) changed");
# line 242 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 242 "../Io.st"
			;
# line 243 "../Io.st"
			seq_pvGetTmo(seqg_env, 0/*Emono*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 244 "../Io.st"
				E_using = (Emono);
# line 244 "../Io.st"
				seq_pvPutTmo(seqg_env, 39/*E_using*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 244 "../Io.st"
			;
# line 245 "../Io.st"
			seq_efClear(seqg_env, E_using_mon);
# line 246 "../Io.st"
			seq_efClear(seqg_env, Emono_mon);
		}
		return;
	case 3:
		{
# line 250 "../Io.st"
			seq_pvGetTmo(seqg_env, 40/*VperA*/, DEFAULT, DEFAULT_TIMEOUT);
# line 251 "../Io.st"
			seq_efClear(seqg_env, VperA_mon);
# line 252 "../Io.st"
			sprintf(new_msg, "changed, Current gain to =%g", VperA);
# line 253 "../Io.st"
			if (Io_debug >= 1)
			{
# line 253 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 253, SNLtaskName, new_msg);
# line 253 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 253 "../Io.st"
			;
		}
		return;
	case 4:
		{
# line 257 "../Io.st"
			seq_pvGetTmo(seqg_env, 56/*ArPcntr*/, DEFAULT, DEFAULT_TIMEOUT);
# line 258 "../Io.st"
			seq_efClear(seqg_env, ArPcntr_mon);
# line 259 "../Io.st"
			if (ArPcntr)
			{
# line 260 "../Io.st"
				dEff = 1. - exp(-(4 * 2.54) * absArPhoto(E_using));
# line 261 "../Io.st"
				dEff *= exp(-(.005 * 2.54) * absorb(5, E_using));
# line 262 "../Io.st"
				seq_pvPutTmo(seqg_env, 55/*dEff*/, DEFAULT, DEFAULT_TIMEOUT);
# line 263 "../Io.st"
				seq_efClear(seqg_env, dEff_mon);
			}
# line 265 "../Io.st"
			sprintf(new_msg, "changed, ArPcntr=%d,  set dEff = %g", ArPcntr, dEff);
# line 266 "../Io.st"
			if (Io_debug >= 1)
			{
# line 266 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 266, SNLtaskName, new_msg);
# line 266 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 266 "../Io.st"
			;
		}
		return;
	case 5:
		{
# line 270 "../Io.st"
			seq_pvGetTmo(seqg_env, 55/*dEff*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 271 "../Io.st"
				ArPcntr = (0);
# line 271 "../Io.st"
				seq_pvPutTmo(seqg_env, 56/*ArPcntr*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 272 "../Io.st"
			seq_efClear(seqg_env, ArPcntr_mon);
# line 273 "../Io.st"
			seq_efClear(seqg_env, dEff_mon);
# line 274 "../Io.st"
			sprintf(new_msg, "changed, dEff=%g", dEff);
# line 275 "../Io.st"
			if (Io_debug >= 1)
			{
# line 275 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 275, SNLtaskName, new_msg);
# line 275 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 275 "../Io.st"
			;
		}
		return;
	case 6:
		{
# line 279 "../Io.st"
			seq_pvGetTmo(seqg_env, 37/*icChannel*/, DEFAULT, DEFAULT_TIMEOUT);
# line 280 "../Io.st"
			seq_pvGetTmo(seqg_env, 41/*v2f*/, DEFAULT, DEFAULT_TIMEOUT);
# line 281 "../Io.st"
			seq_efClear(seqg_env, icChannel_mon);
# line 282 "../Io.st"
			seq_efClear(seqg_env, v2f_mon);
# line 283 "../Io.st"
			sprintf(new_msg, "changed, icChannel=%d, v2f=%g", icChannel, v2f);
# line 284 "../Io.st"
			if (Io_debug >= 1)
			{
# line 284 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 284, SNLtaskName, new_msg);
# line 284 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 284 "../Io.st"
			;
		}
		return;
	case 7:
		{
# line 288 "../Io.st"
			seq_pvGetTmo(seqg_env, 42/*xN2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 289 "../Io.st"
			seq_pvGetTmo(seqg_env, 44/*xHe*/, DEFAULT, DEFAULT_TIMEOUT);
# line 290 "../Io.st"
			seq_pvGetTmo(seqg_env, 43/*xAr*/, DEFAULT, DEFAULT_TIMEOUT);
# line 291 "../Io.st"
			seq_pvGetTmo(seqg_env, 45/*xAir*/, DEFAULT, DEFAULT_TIMEOUT);
# line 292 "../Io.st"
			seq_pvGetTmo(seqg_env, 46/*xCO2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 293 "../Io.st"
			seq_efClear(seqg_env, xN2_mon);
# line 294 "../Io.st"
			seq_efClear(seqg_env, xHe_mon);
# line 295 "../Io.st"
			seq_efClear(seqg_env, xAr_mon);
# line 296 "../Io.st"
			seq_efClear(seqg_env, xAir_mon);
# line 297 "../Io.st"
			seq_efClear(seqg_env, xCO2_mon);
# line 298 "../Io.st"
			sprintf(new_msg, "changed, xN2=%g, xAr=%g, xHe=%g, xAir=%g, xCO2=%g", xN2, xAr, xHe, xAir, xCO2);
# line 299 "../Io.st"
			if (Io_debug >= 1)
			{
# line 299 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 299, SNLtaskName, new_msg);
# line 299 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 299 "../Io.st"
			;
		}
		return;
	case 8:
		{
# line 303 "../Io.st"
			seq_pvGetTmo(seqg_env, 47/*activeLen*/, DEFAULT, DEFAULT_TIMEOUT);
# line 304 "../Io.st"
			seq_pvGetTmo(seqg_env, 48/*deadFront*/, DEFAULT, DEFAULT_TIMEOUT);
# line 305 "../Io.st"
			seq_pvGetTmo(seqg_env, 49/*deadRear*/, DEFAULT, DEFAULT_TIMEOUT);
# line 306 "../Io.st"
			seq_efClear(seqg_env, activeLen_mon);
# line 307 "../Io.st"
			seq_efClear(seqg_env, deadFront_mon);
# line 308 "../Io.st"
			seq_efClear(seqg_env, deadRear_mon);
# line 309 "../Io.st"
			sprintf(new_msg, "changed, activeLen=%g, deadFront=%g, deadRear=%g", activeLen, deadFront, deadRear);
# line 310 "../Io.st"
			if (Io_debug >= 1)
			{
# line 310 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 310, SNLtaskName, new_msg);
# line 310 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 310 "../Io.st"
			;
		}
		return;
	case 9:
		{
# line 314 "../Io.st"
			seq_pvGetTmo(seqg_env, 52/*HePath*/, DEFAULT, DEFAULT_TIMEOUT);
# line 315 "../Io.st"
			seq_pvGetTmo(seqg_env, 53/*airPath*/, DEFAULT, DEFAULT_TIMEOUT);
# line 316 "../Io.st"
			seq_efClear(seqg_env, HePath_mon);
# line 317 "../Io.st"
			seq_efClear(seqg_env, airPath_mon);
# line 318 "../Io.st"
			sprintf(new_msg, "changed, HePath=%g, airPath=%g", HePath, airPath);
# line 319 "../Io.st"
			if (Io_debug >= 1)
			{
# line 319 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 319, SNLtaskName, new_msg);
# line 319 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 319 "../Io.st"
			;
		}
		return;
	case 10:
		{
# line 323 "../Io.st"
			seq_pvGetTmo(seqg_env, 50/*kapton1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 324 "../Io.st"
			seq_pvGetTmo(seqg_env, 51/*kapton2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 325 "../Io.st"
			seq_pvGetTmo(seqg_env, 54/*Be*/, DEFAULT, DEFAULT_TIMEOUT);
# line 326 "../Io.st"
			seq_efClear(seqg_env, kapton1_mon);
# line 327 "../Io.st"
			seq_efClear(seqg_env, kapton2_mon);
# line 328 "../Io.st"
			seq_efClear(seqg_env, Be_mon);
# line 329 "../Io.st"
			sprintf(new_msg, "changed, kapton1=%g, kapton2=%g, Be=%g", kapton1, kapton2, Be);
# line 330 "../Io.st"
			if (Io_debug >= 1)
			{
# line 330 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 330, SNLtaskName, new_msg);
# line 330 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 330 "../Io.st"
			;
		}
		return;
	case 11:
		{
# line 334 "../Io.st"
			seq_efClear(seqg_env, cnt_mon);
# line 335 "../Io.st"
			seq_efClear(seqg_env, ticks_mon);
# line 336 "../Io.st"
			sprintf(new_msg, "counter cycled");
# line 337 "../Io.st"
			if (Io_debug >= 2)
			{
# line 337 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 337, SNLtaskName, new_msg);
# line 337 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 337 "../Io.st"
			;
		}
		return;
	case 12:
		{
# line 341 "../Io.st"
			if (Io_debug >= 3)
			{
# line 341 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 341, SNLtaskName, "periodic update");
# line 341 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 341 "../Io.st"
			;
		}
		return;
	}
}

/****** Code for state "UpdateDisplay" in state set "ionChamber" ******/

/* Event function for state "UpdateDisplay" in state set "ionChamber" */
static seqBool seqg_event_ionChamber_0_UpdateDisplay(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "UpdateDisplay" in state set "ionChamber" */
static void seqg_action_ionChamber_0_UpdateDisplay(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 348 "../Io.st"
			seq_pvGetTmo(seqg_env, 39/*E_using*/, DEFAULT, DEFAULT_TIMEOUT);
# line 349 "../Io.st"
			seq_efClear(seqg_env, E_using_mon);
# line 350 "../Io.st"
			EvalFlux(activeLen, deadFront, deadRear, HePath, airPath, Be, E_using);
# line 351 "../Io.st"
			if (icChannel == 2)
			{
# line 351 "../Io.st"
				seq_pvGetTmo(seqg_env, 18/*nm2*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 351 "../Io.st"
					sprintf(icName, nm2);
# line 351 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 352 "../Io.st"
			if (icChannel == 3)
			{
# line 352 "../Io.st"
				seq_pvGetTmo(seqg_env, 19/*nm3*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 352 "../Io.st"
					sprintf(icName, nm3);
# line 352 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 353 "../Io.st"
			if (icChannel == 4)
			{
# line 353 "../Io.st"
				seq_pvGetTmo(seqg_env, 20/*nm4*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 353 "../Io.st"
					sprintf(icName, nm4);
# line 353 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 354 "../Io.st"
			if (icChannel == 5)
			{
# line 354 "../Io.st"
				seq_pvGetTmo(seqg_env, 21/*nm5*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 354 "../Io.st"
					sprintf(icName, nm5);
# line 354 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 355 "../Io.st"
			if (icChannel == 6)
			{
# line 355 "../Io.st"
				seq_pvGetTmo(seqg_env, 22/*nm6*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 355 "../Io.st"
					sprintf(icName, nm6);
# line 355 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 356 "../Io.st"
			if (icChannel == 7)
			{
# line 356 "../Io.st"
				seq_pvGetTmo(seqg_env, 23/*nm7*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 356 "../Io.st"
					sprintf(icName, nm7);
# line 356 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 357 "../Io.st"
			if (icChannel == 8)
			{
# line 357 "../Io.st"
				seq_pvGetTmo(seqg_env, 24/*nm8*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 357 "../Io.st"
					sprintf(icName, nm8);
# line 357 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 358 "../Io.st"
			if (icChannel == 9)
			{
# line 358 "../Io.st"
				seq_pvGetTmo(seqg_env, 25/*nm9*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 358 "../Io.st"
					sprintf(icName, nm9);
# line 358 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 359 "../Io.st"
			if (icChannel == 10)
			{
# line 359 "../Io.st"
				seq_pvGetTmo(seqg_env, 26/*nm10*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 359 "../Io.st"
					sprintf(icName, nm10);
# line 359 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 360 "../Io.st"
			if (icChannel == 11)
			{
# line 360 "../Io.st"
				seq_pvGetTmo(seqg_env, 27/*nm11*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 360 "../Io.st"
					sprintf(icName, nm11);
# line 360 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 361 "../Io.st"
			if (icChannel == 12)
			{
# line 361 "../Io.st"
				seq_pvGetTmo(seqg_env, 28/*nm12*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 361 "../Io.st"
					sprintf(icName, nm12);
# line 361 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 362 "../Io.st"
			if (icChannel == 13)
			{
# line 362 "../Io.st"
				seq_pvGetTmo(seqg_env, 29/*nm13*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 362 "../Io.st"
					sprintf(icName, nm13);
# line 362 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 363 "../Io.st"
			if (icChannel == 14)
			{
# line 363 "../Io.st"
				seq_pvGetTmo(seqg_env, 30/*nm14*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 363 "../Io.st"
					sprintf(icName, nm14);
# line 363 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 364 "../Io.st"
			if (icChannel == 15)
			{
# line 364 "../Io.st"
				seq_pvGetTmo(seqg_env, 31/*nm15*/, DEFAULT, DEFAULT_TIMEOUT);
				{
# line 364 "../Io.st"
					sprintf(icName, nm15);
# line 364 "../Io.st"
					seq_pvPutTmo(seqg_env, 38/*icName*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 365 "../Io.st"
			seq_pvPutTmo(seqg_env, 32/*flux*/, DEFAULT, DEFAULT_TIMEOUT);
# line 366 "../Io.st"
			seq_pvPutTmo(seqg_env, 33/*ionPhotons*/, DEFAULT, DEFAULT_TIMEOUT);
# line 367 "../Io.st"
			seq_pvPutTmo(seqg_env, 34/*ionAbs*/, DEFAULT, DEFAULT_TIMEOUT);
# line 368 "../Io.st"
			seq_pvPutTmo(seqg_env, 35/*detector*/, DEFAULT, DEFAULT_TIMEOUT);
# line 369 "../Io.st"
			sprintf(new_msg, "   in Updatedisplay, flux = %g,   detector = %g", flux, detector);
# line 370 "../Io.st"
			if (Io_debug >= 3)
			{
# line 370 "../Io.st"
				printf("<%s,%d,%s> %s\n", "../Io.st", 370, SNLtaskName, new_msg);
# line 370 "../Io.st"
				epicsThreadSleep(0.1);
			}
# line 370 "../Io.st"
			;
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{MONO}", (size_t)&Emono, "Emono", P_DOUBLE, 1, 24, 1, 1, 0, 0},
	{"{VSC}.CNT", (size_t)&cnt, "cnt", P_SHORT, 1, 25, 2, 1, 0, 0},
	{"{VSC}.FREQ", (size_t)&clock_rate, "clock_rate", P_DOUBLE, 1, 26, 0, 1, 0, 0},
	{"{VSC}.S1", (size_t)&ticks, "ticks", P_DOUBLE, 1, 27, 3, 1, 0, 0},
	{"{VSC}.S2", (size_t)&s2, "s2", P_DOUBLE, 1, 28, 0, 1, 0, 0},
	{"{VSC}.S3", (size_t)&s3, "s3", P_DOUBLE, 1, 29, 0, 1, 0, 0},
	{"{VSC}.S4", (size_t)&s4, "s4", P_DOUBLE, 1, 30, 0, 1, 0, 0},
	{"{VSC}.S5", (size_t)&s5, "s5", P_DOUBLE, 1, 31, 0, 1, 0, 0},
	{"{VSC}.S6", (size_t)&s6, "s6", P_DOUBLE, 1, 32, 0, 1, 0, 0},
	{"{VSC}.S7", (size_t)&s7, "s7", P_DOUBLE, 1, 33, 0, 1, 0, 0},
	{"{VSC}.S8", (size_t)&s8, "s8", P_DOUBLE, 1, 34, 0, 1, 0, 0},
	{"{VSC}.S9", (size_t)&s9, "s9", P_DOUBLE, 1, 35, 0, 1, 0, 0},
	{"{VSC}.S10", (size_t)&s10, "s10", P_DOUBLE, 1, 36, 0, 1, 0, 0},
	{"{VSC}.S11", (size_t)&s11, "s11", P_DOUBLE, 1, 37, 0, 1, 0, 0},
	{"{VSC}.S12", (size_t)&s12, "s12", P_DOUBLE, 1, 38, 0, 1, 0, 0},
	{"{VSC}.S13", (size_t)&s13, "s13", P_DOUBLE, 1, 39, 0, 1, 0, 0},
	{"{VSC}.S14", (size_t)&s14, "s14", P_DOUBLE, 1, 40, 0, 1, 0, 0},
	{"{VSC}.S15", (size_t)&s15, "s15", P_DOUBLE, 1, 41, 0, 1, 0, 0},
	{"{VSC}.NM2", (size_t)&nm2, "nm2", P_STRING, 1, 42, 0, 0, 0, 0},
	{"{VSC}.NM3", (size_t)&nm3, "nm3", P_STRING, 1, 43, 0, 0, 0, 0},
	{"{VSC}.NM4", (size_t)&nm4, "nm4", P_STRING, 1, 44, 0, 0, 0, 0},
	{"{VSC}.NM5", (size_t)&nm5, "nm5", P_STRING, 1, 45, 0, 0, 0, 0},
	{"{VSC}.NM6", (size_t)&nm6, "nm6", P_STRING, 1, 46, 0, 0, 0, 0},
	{"{VSC}.NM7", (size_t)&nm7, "nm7", P_STRING, 1, 47, 0, 0, 0, 0},
	{"{VSC}.NM8", (size_t)&nm8, "nm8", P_STRING, 1, 48, 0, 0, 0, 0},
	{"{VSC}.NM9", (size_t)&nm9, "nm9", P_STRING, 1, 49, 0, 0, 0, 0},
	{"{VSC}.NM10", (size_t)&nm10, "nm10", P_STRING, 1, 50, 0, 0, 0, 0},
	{"{VSC}.NM11", (size_t)&nm11, "nm11", P_STRING, 1, 51, 0, 0, 0, 0},
	{"{VSC}.NM12", (size_t)&nm12, "nm12", P_STRING, 1, 52, 0, 0, 0, 0},
	{"{VSC}.NM13", (size_t)&nm13, "nm13", P_STRING, 1, 53, 0, 0, 0, 0},
	{"{VSC}.NM14", (size_t)&nm14, "nm14", P_STRING, 1, 54, 0, 0, 0, 0},
	{"{VSC}.NM15", (size_t)&nm15, "nm15", P_STRING, 1, 55, 0, 0, 0, 0},
	{"{P}flux", (size_t)&flux, "flux", P_DOUBLE, 1, 56, 0, 0, 0, 0},
	{"{P}ionPhotons", (size_t)&ionPhotons, "ionPhotons", P_DOUBLE, 1, 57, 0, 0, 0, 0},
	{"{P}ionAbs", (size_t)&ionAbs, "ionAbs", P_DOUBLE, 1, 58, 0, 0, 0, 0},
	{"{P}detector", (size_t)&detector, "detector", P_DOUBLE, 1, 59, 0, 0, 0, 0},
	{"{P}debug", (size_t)&IoDebug, "IoDebug", P_SHORT, 1, 60, 4, 1, 0, 0},
	{"{P}scaler", (size_t)&icChannel, "icChannel", P_SHORT, 1, 61, 5, 1, 0, 0},
	{"{P}scaler.DESC", (size_t)&icName, "icName", P_STRING, 1, 62, 0, 0, 0, 0},
	{"{P}E_using", (size_t)&E_using, "E_using", P_DOUBLE, 1, 63, 6, 1, 0, 0},
	{"{P}VperA", (size_t)&VperA, "VperA", P_DOUBLE, 1, 64, 7, 1, 0, 0},
	{"{P}v2f", (size_t)&v2f, "v2f", P_DOUBLE, 1, 65, 8, 1, 0, 0},
	{"{P}xN2", (size_t)&xN2, "xN2", P_DOUBLE, 1, 66, 9, 1, 0, 0},
	{"{P}xAr", (size_t)&xAr, "xAr", P_DOUBLE, 1, 67, 10, 1, 0, 0},
	{"{P}xHe", (size_t)&xHe, "xHe", P_DOUBLE, 1, 68, 11, 1, 0, 0},
	{"{P}xAir", (size_t)&xAir, "xAir", P_DOUBLE, 1, 69, 12, 1, 0, 0},
	{"{P}xCO2", (size_t)&xCO2, "xCO2", P_DOUBLE, 1, 70, 13, 1, 0, 0},
	{"{P}activeLen", (size_t)&activeLen, "activeLen", P_DOUBLE, 1, 71, 14, 1, 0, 0},
	{"{P}deadFront", (size_t)&deadFront, "deadFront", P_DOUBLE, 1, 72, 15, 1, 0, 0},
	{"{P}deadRear", (size_t)&deadRear, "deadRear", P_DOUBLE, 1, 73, 16, 1, 0, 0},
	{"{P}kapton1", (size_t)&kapton1, "kapton1", P_DOUBLE, 1, 74, 17, 1, 0, 0},
	{"{P}kapton2", (size_t)&kapton2, "kapton2", P_DOUBLE, 1, 75, 18, 1, 0, 0},
	{"{P}HePath", (size_t)&HePath, "HePath", P_DOUBLE, 1, 76, 19, 1, 0, 0},
	{"{P}airPath", (size_t)&airPath, "airPath", P_DOUBLE, 1, 77, 20, 1, 0, 0},
	{"{P}Be", (size_t)&Be, "Be", P_DOUBLE, 1, 78, 21, 1, 0, 0},
	{"{P}efficiency", (size_t)&dEff, "dEff", P_DOUBLE, 1, 79, 22, 1, 0, 0},
	{"{P}ArPcntr", (size_t)&ArPcntr, "ArPcntr", P_SHORT, 1, 80, 23, 1, 0, 0},
};

/* Event masks for state set "ionChamber" */
static const seqMask seqg_mask_ionChamber_0_init[] = {
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ionChamber_0_idle[] = {
	0x00fffffe,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_ionChamber_0_UpdateDisplay[] = {
	0x00000000,
	0x00000000,
	0x00000000,
};

/* State table for state set "ionChamber" */
static seqState seqg_states_ionChamber[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_ionChamber_0_init,
	/* event function */    seqg_event_ionChamber_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ionChamber_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "idle",
	/* action function */   seqg_action_ionChamber_0_idle,
	/* event function */    seqg_event_ionChamber_0_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ionChamber_0_idle,
	/* state options */     (0)
	},
	{
	/* state name */        "UpdateDisplay",
	/* action function */   seqg_action_ionChamber_0_UpdateDisplay,
	/* event function */    seqg_event_ionChamber_0_UpdateDisplay,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ionChamber_0_UpdateDisplay,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "ionChamber",
	/* states */            seqg_states_ionChamber,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram Io = {
	/* magic number */      2002005,
	/* program name */      "Io",
	/* channels */          seqg_chans,
	/* num. channels */     57,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "P=7idd:Io:,MONO=7id:HHLM:energy_get,VSC=7idd:scaler1",
	/* num. event flags */  23,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};
# line 380 "../Io.st"



void EvalFlux(
double aln,
double dln1,
double dln2,
double dHe,
double dAir,
double dBe,
double energy)
{

 double AirAbs;
 double HeAbs;
 double KapAbs;
 double BeAbs;
 double fillAbsorb;
 double frontAbs;
 double cps;


 aln = aln / 10.;
 dln1 = dln1 / 10.;
 dln2 = dln2 / 10.;
 dHe = dHe / 10.;
 dAir = dAir / 10.;
 dBe = dBe * 2.54;

 switch (icChannel) {
 case 2: cps = s2; break;
 case 3: cps = s3; break;
 case 4: cps = s4; break;
 case 5: cps = s5; break;
 case 6: cps = s6; break;
 case 7: cps = s7; break;
 case 8: cps = s8; break;
 case 9: cps = s9; break;
 case 10: cps = s10; break;
 case 11: cps = s11; break;
 case 12: cps = s12; break;
 case 13: cps = s13; break;
 case 14: cps = s14; break;
 case 15: cps = s15; break;
 default:
  cps = 0;
 }
 cps /= (ticks/clock_rate);


 flux = 0.;
 flux += xHe * photon(cps,29.6, v2f,VperA,aln,dln1,kapton1,1,energy);
 flux += xN2 * photon(cps,36.3, v2f,VperA,aln,dln1,kapton1,2,energy);
 flux += xAr * photon(cps,24.4, v2f,VperA,aln,dln1,kapton1,3,energy);
 flux += xAir* photon(cps,35.36,v2f,VperA,aln,dln1,kapton1,4,energy);
 flux += xCO2* photon(cps,35.36,v2f,VperA,aln,dln1,kapton1,7,energy);


 AirAbs = exp(-dAir*absorb(4,energy));
 HeAbs = exp(-dHe * absorb(1,energy) );
 KapAbs = exp(-(kapton2+kapton1)*2.54 * absorb(6,energy) );
 BeAbs = exp(-dBe * absorb(5,energy) );
 fillAbsorb = absorb(1,energy)*xHe + absorb(2,energy)*xN2 + absorb(3,energy)*xAr + absorb(4,energy)*xAir + absorb(7,energy)*xCO2;

 ionAbs = exp(-(dln1+dln2+aln) * fillAbsorb);
 detector = flux * AirAbs * HeAbs * KapAbs * BeAbs * ionAbs * dEff;
 frontAbs = exp( -2.54*kapton1*absorb(6,energy) - dln1*fillAbsorb );
 ionPhotons = (1.- exp(-aln * fillAbsorb)) * frontAbs * flux;
}


double photon(
double cps,
double work,
double VtoF,
double Volt_per_A,
double aln,
double deadL,
double Kapton,
int gasId,
double energy)
{


 double convHe = 6.647;
 double rhoHe = 0.0001785;
 double convN = 23.26;
 double rhoN = 0.00125;
 double convAr = 66.32;
 double rhoAr = 0.001784;
 double edgeAr = 3.202;
 double sum,E1,E2,E3;
 double part1,part2,part3;
 double photo;

 static double aHe[4] = { 6.06488, -3.29055, -0.107256, 0.0144465 };
 static double aN[4] = { 11.2765, -2.65400, -0.200445, 0.0200765 };
 static double aAr1[4] = { 13.9491, -1.82276, -0.328827, 0.0274382 };
 static double aAr2[4] = { 12.2960, -2.63279, -0.073660, 0.0 };
 static double aO[4] = { 11.7130, -2.57229, -0.205893, 0.0199244 };
 static double aC[4] = { 10.6879, -2.71400, -0.200530, 0.0207248 };

 E1 = log(energy);
 E2 = E1 * E1;
 E3 = E2 * E1;
 photo = 0;


 if (gasId == 1) {
  sum = exp(aHe[0] + aHe[1]*E1 + aHe[2]*E2 + aHe[3]*E3);
  photo = sum * rhoHe / convHe;
 }
 else if (gasId == 2) {
  sum = exp(aN[0] + aN[1]*E1 + aN[2]*E2 + aN[3]*E3);
  photo = sum * rhoN / convN;
 }
 else if (gasId == 3) {
  if (E1 > edgeAr) sum = exp(aAr1[0] + aAr1[1]*E1 + aAr1[2]*E2 + aAr1[3]*E3);
  else sum = exp(aAr2[0] + aAr2[1]*E1 + aAr2[2]*E2 + aAr2[3]*E3);
  photo = sum * rhoAr / convAr;
 }
 else if (gasId == 4) {
  sum = exp(aN[0] + aN[1]*E1 + aN[2]*E2 + aN[3]*E3);
  photo = sum * 0.000922 / convN;
  sum = exp(aO[0] + aO[1]*E1 + aO[2]*E2 + aO[3]*E3);
  photo += sum * 0.000266 / convN;
  if (E1 > edgeAr) sum = exp(aAr1[0] + aAr1[1]*E1 + aAr1[2]*E2 + aAr1[3]*E3);
  else sum = exp(aAr2[0] + aAr2[1]*E1 + aAr2[2]*E2 + aAr2[3]*E3);
  photo += sum * 1.66E-5 / convAr;
 }
 else if (gasId == 7) {
  sum = exp(aC[0] + aC[1]*E1 + aC[2]*E2 + aC[3]*E3);
  photo = sum * 0.0005396 / convN;
  sum = exp(aO[0] + aO[1]*E1 + aO[2]*E2 + aO[3]*E3);
  photo += sum * 0.0014374 / convN;
 }


 part1 = cps * work / (1.602E-19 * VtoF * Volt_per_A * energy * 1000.);
 part2 = 1 - exp(-photo * aln);
 part3 = exp(absorb(gasId,energy) * deadL) * exp(absorb(6,energy) * Kapton * 2.54);

 return (part1 * part3 / part2);
}


double absorb(
int id,
double energy)
{
# 540 "../Io.st"
 double rhoH;
 double rhoHe;
 double rhoBe;
 double rhoC;
 double rhoN;
 double rhoO;
 double rhoAr;

 switch (id) {
 case 1:
  rhoHe = 0.0001785;
  return(absHe(energy)*rhoHe);
 case 5:
  rhoBe = 1.848;
  return(absBe(energy)*rhoBe);
 case 2:
  rhoN = 0.00125;
  return(absN(energy)*rhoN);
 case 4:
  rhoN = 0.000922;
  rhoO = 0.000266;
  rhoAr = 1.66E-5;
  return(absN(energy)*rhoN + absO(energy)*rhoO + absAr(energy)*rhoAr);
 case 3:
  rhoAr = 0.001784;
  return(absAr(energy)*rhoAr);
 case 6:
  rhoC = 0.981;
  rhoH = 0.037;
  rhoO = 0.297;
  rhoN = 0.105;
  return(absC(energy)*rhoC + absH(energy)*rhoH + absO(energy)*rhoO + absN(energy)*rhoN);
 case 7:
  rhoC = 0.0005396;
  rhoO = 0.0014374;
  return(absC(energy)*rhoC + absO(energy)*rhoO);
 }
 return 0;
}





double absH(
double energy)
{
 double conv;
 double E1,E2,E3;
 double photo;
 double coherent;
 double compton;
 static double a[4] = { 2.44964E+00,-3.34953E+00,-4.71370E-02, 7.09962E-03 };
 static double b[4] = {-1.19075E-01,-9.37086E-01,-2.00538E-01, 1.06587E-02 };
 static double c[4] = {-2.15772E+00, 1.32685E+00,-3.05620E-01, 1.85025E-02 };


 conv = 1.674;

 E1 = log(energy);
 E2 = E1*E1;
 E3 = E2*E1;

 photo = exp( a[0] + a[1]*E1 + a[2]*E2 + a[3]*E3);
 coherent = exp( b[0] + b[1]*E1 + b[2]*E2 + b[3]*E3);
 compton = exp( c[0] + c[1]*E1 + c[2]*E2 + c[3]*E3);
 return( (photo+coherent+compton)/conv);
}





double absHe(
double energy)
{
 double conv;
 double E1,E2,E3;
 double photo;
 double coherent;
 double compton;
 static double a[4] = { 6.06488E+00,-3.29055E+00,-1.07256E-01, 1.44465E-02 };
 static double b[4] = { 1.04768E+00,-8.51805E-02,-4.03527E-01, 2.69398E-02 };
 static double c[4] = {-2.56357E+00, 2.02536E+00,-4.48710E-01, 2.79691E-02 };


 conv = 6.647;

 E1 = log(energy);
 E2 = E1*E1;
 E3 = E2*E1;

 photo = exp( a[0] + a[1]*E1 + a[2]*E2 + a[3]*E3);
 coherent = exp( b[0] + b[1]*E1 + b[2]*E2 + b[3]*E3);
 compton = exp( c[0] + c[1]*E1 + c[2]*E2 + c[3]*E3);
 return((photo+coherent+compton)/conv);
}





double absBe(
double energy)
{
 double conv;
 double E1,E2,E3;
 double photo;
 double coherent;
 double compton;
 static double a[4] = { 9.04511E+00,-2.83487E+00,-2.10021E-01, 2.29526E-02 };
 static double b[4] = { 2.00860E+00,-4.61920E-02,-3.37018E-01, 1.86939E-02 };
 static double c[4] = {-6.90079E-01, 9.46448E-01,-1.71142E-01, 6.51413E-03 };


 conv = 14.96;

 E1 = log(energy);
 E2 = E1*E1;
 E3 = E2*E1;

 photo = exp( a[0] + a[1]*E1 + a[2]*E2 + a[3]*E3);
 coherent = exp( b[0] + b[1]*E1 + b[2]*E2 + b[3]*E3);
 compton = exp( c[0] + c[1]*E1 + c[2]*E2 + c[3]*E3);
 return((photo+coherent+compton)/conv);
}





double absC(
double energy)
{
 double conv;
 double E1,E2,E3;
 double photo;
 double coherent;
 double compton;
 static double a[4] = { 1.06879E+01,-2.71400E+00,-2.00530E-01, 2.07248E-02 };
 static double b[4] = { 3.10861E+00,-2.60580E-01,-2.71974E-01, 1.35181E-02 };
 static double c[4] = {-9.82878E-01, 1.46693E+00,-2.93743E-01, 1.56005E-02 };


 conv = 19.94;

 E1 = log(energy);
 E2 = E1*E1;
 E3 = E2*E1;

 photo = exp( a[0] + a[1]*E1 + a[2]*E2 + a[3]*E3);
 coherent = exp( b[0] + b[1]*E1 + b[2]*E2 + b[3]*E3);
 compton = exp( c[0] + c[1]*E1 + c[2]*E2 + c[3]*E3);
 return((photo+coherent+compton)/conv);
}





double absN(
double energy)
{
 double conv;
 double E1,E2,E3;
 double photo;
 double coherent;
 double compton;
 static double a[4] = { 1.12765E+01,-2.65400E+00,-2.00445E-01, 2.00765E-02 };
 static double b[4] = { 3.47760E+00,-2.15762E-01,-2.88874E-01, 1.51312E-02 };
 static double c[4] = {-1.23693E+00, 1.74510E+00,-3.54660E-01, 1.98705E-02 };


 conv = 23.26;

 E1 = log(energy);
 E2 = E1*E1;
 E3 = E2*E1;

 photo = exp( a[0] + a[1]*E1 + a[2]*E2 + a[3]*E3);
 coherent = exp( b[0] + b[1]*E1 + b[2]*E2 + b[3]*E3);
 compton = exp( c[0] + c[1]*E1 + c[2]*E2 + c[3]*E3);
 return((photo+coherent+compton)/conv);
}





double absO(
double energy)
{
 double conv;
 double E1,E2,E3;
 double photo;
 double coherent;
 double compton;
 static double a[4] = { 1.17130E+01,-2.57229E+00,-2.05893E-01, 1.99244E-02 };
 static double b[4] = { 3.77239E+00,-1.48539E-01,-3.07124E-01, 1.67303E-02 };
 static double c[4] = {-1.73679E+00, 2.17686E+00,-4.49050E-01, 2.64733E-02 };


 conv = 26.57;

 E1 = log(energy);
 E2 = E1*E1;
 E3 = E2*E1;

 photo = exp( a[0] + a[1]*E1 + a[2]*E2 + a[3]*E3);
 coherent = exp( b[0] + b[1]*E1 + b[2]*E2 + b[3]*E3);
 compton = exp( c[0] + c[1]*E1 + c[2]*E2 + c[3]*E3);
 return((photo+coherent+compton)/conv);
}





double absAr(
double energy)
{
 double conv;
 double E1,E2,E3;
 double photo;
 double coherent;
 double compton;
 double edge;
 static double a1[4] = { 1.39491E+01,-1.82276E+00,-3.28827E-01, 2.74382E-02 };
 static double a2[4] = { 1.22960E+01,-2.63279E+00,-7.36600E-02, 0.};
 static double b[4] = { 5.21079E+00, 1.35618E-01,-3.47214E-01, 1.84333E-02 };
 static double c[4] = {-6.82105E-01, 1.74279E+00,-3.17646E-01, 1.56467E-02 };


 conv = 66.32;
 edge = 3.202;

 E1 = log(energy);
 E2 = E1*E1;
 E3 = E2*E1;

 if (energy>edge) photo = exp( a1[0] + a1[1]*E1 + a1[2]*E2 + a1[3]*E3);
 else photo = exp( a2[0] + a2[1]*E1 + a2[2]*E2 + a2[3]*E3);
 coherent = exp( b[0] + b[1]*E1 + b[2]*E2 + b[3]*E3);
 compton = exp( c[0] + c[1]*E1 + c[2]*E2 + c[3]*E3);
 return((photo+coherent+compton)/conv);
}


double absArPhoto(
double energy)
{
 double conv;
 double E1,E2,E3;
 double photo;
 double rho;
 double edge;
 static double aAr1[4] = {13.9491, -1.82276, -0.328827, 0.0274382 };
 static double aAr2[4] = {12.2960, -2.63279, -0.073660, 0.0 };

 conv = 66.32;
 rho = 0.001784;
 edge = 3.202;

 E1 = log(energy);
 E2 = E1*E1;
 E3 = E2*E1;

 if (energy>edge) photo = exp( aAr1[0] + aAr1[1]*E1 + aAr1[2]*E2 + aAr1[3]*E3);
 else photo = exp( aAr2[0] + aAr2[1]*E1 + aAr2[2]*E2 + aAr2[3]*E3);

 return (photo / conv * rho);
}




/* Register sequencer commands and program */
#include "epicsExport.h"
static void IoRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&Io);
}
epicsExportRegistrar(IoRegistrar);
