/* C code for program scanProgress, generated by snc from ../scanProg.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 33 "../scanProg.st"
#include <string.h>
# line 34 "../scanProg.st"
#include <epicsThread.h>
# line 35 "../scanProg.st"
#include <epicsTime.h>
# line 36 "../scanProg.st"
#include <string.h>
# line 37 "../scanProg.st"
#include <time.h>
# line 56 "../scanProg.st"
static const EF_ID scanProgressDebug_mon = 1;
# line 72 "../scanProg.st"
static const EF_ID hangWaitSec_mon = 2;
# line 85 "../scanProg.st"
static const EF_ID pause1_mon = 3;
# line 86 "../scanProg.st"
static const EF_ID pause2_mon = 4;
# line 87 "../scanProg.st"
static const EF_ID pause3_mon = 5;
# line 88 "../scanProg.st"
static const EF_ID pause4_mon = 6;
# line 89 "../scanProg.st"
static const EF_ID busy1_mon = 7;
# line 90 "../scanProg.st"
static const EF_ID busy2_mon = 8;
# line 91 "../scanProg.st"
static const EF_ID busy3_mon = 9;
# line 92 "../scanProg.st"
static const EF_ID busy4_mon = 10;
# line 113 "../scanProg.st"
static void clocks2str(long isec, char *str);
# line 114 "../scanProg.st"
static void formatTimeStr(char *tStr, int tStrLen, time_t final, int full);
# line 115 "../scanProg.st"
static long calc_cpt(void);
# line 116 "../scanProg.st"
static int allStopped(void);

/* Variable declarations */
# line 56 "../scanProg.st"
static	short scanProgressDebug;
# line 57 "../scanProg.st"
static	double fractionDone;
# line 58 "../scanProg.st"
static	double percentDone;
# line 59 "../scanProg.st"
static	string startingTimeStr;
# line 60 "../scanProg.st"
static	string endingTimeStr;
# line 61 "../scanProg.st"
static	string remainingTimeStr;
# line 62 "../scanProg.st"
static	string pauseTimeStr;
# line 63 "../scanProg.st"
static	string totalElapsedTimeStr;
# line 64 "../scanProg.st"
static	string totalActiveTimeStr;
# line 65 "../scanProg.st"
static	int pauseSec;
# line 66 "../scanProg.st"
static	int remainingSec;
# line 67 "../scanProg.st"
static	int npts;
# line 68 "../scanProg.st"
static	int cpt;
# line 69 "../scanProg.st"
static	short running;
# line 70 "../scanProg.st"
static	short paused;
# line 71 "../scanProg.st"
static	int Npauses;
# line 72 "../scanProg.st"
static	int hangWaitSec;
# line 73 "../scanProg.st"
static	int hungSec;
# line 74 "../scanProg.st"
static	string hungTimeStr;
# line 75 "../scanProg.st"
static	double version;
# line 77 "../scanProg.st"
static	int npts1;
# line 78 "../scanProg.st"
static	int npts2;
# line 79 "../scanProg.st"
static	int npts3;
# line 80 "../scanProg.st"
static	int npts4;
# line 81 "../scanProg.st"
static	int cpt1;
# line 82 "../scanProg.st"
static	int cpt2;
# line 83 "../scanProg.st"
static	int cpt3;
# line 84 "../scanProg.st"
static	int cpt4;
# line 85 "../scanProg.st"
static	short pause1;
# line 86 "../scanProg.st"
static	short pause2;
# line 87 "../scanProg.st"
static	short pause3;
# line 88 "../scanProg.st"
static	short pause4;
# line 89 "../scanProg.st"
static	short busy1;
# line 90 "../scanProg.st"
static	short busy2;
# line 91 "../scanProg.st"
static	short busy3;
# line 92 "../scanProg.st"
static	short busy4;
# line 95 "../scanProg.st"
static	char *SNLtaskName;
# line 96 "../scanProg.st"
static	char new_msg[256];
# line 99 "../scanProg.st"
static	long predictEnd;
# line 100 "../scanProg.st"
static	long startTime;
# line 101 "../scanProg.st"
static	long pauseStart;
# line 102 "../scanProg.st"
static	long now;
# line 103 "../scanProg.st"
static	long cptAtLastOK;
# line 104 "../scanProg.st"
static	long timeOfLastOK;
# line 105 "../scanProg.st"
static	char tStr[100];
# line 106 "../scanProg.st"
static	char tStr1[100];
# line 107 "../scanProg.st"
static	int beginPause;
# line 108 "../scanProg.st"
static	int almostPaused;
# line 109 "../scanProg.st"
static	int stopped;
# line 110 "../scanProg.st"
static	int aPause;
# line 111 "../scanProg.st"
static	int scanDim;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "scanProgress" ******/

/* Event function for state "init" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "scanProgress" */
static void seqg_action_scanProgress_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 125 "../scanProg.st"
			SNLtaskName = seq_macValueGet(seqg_env, "name");
# line 126 "../scanProg.st"
			scanDim = 1;
# line 127 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 0/*scanProgressDebug*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 128 "../scanProg.st"
				version = (2.3);
# line 128 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 19/*version*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 129 "../scanProg.st"
				fractionDone = (0.0);
# line 129 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 1/*fractionDone*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 130 "../scanProg.st"
				percentDone = (0.0);
# line 130 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 2/*percentDone*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 131 "../scanProg.st"
				strcpy(endingTimeStr, "");
# line 131 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 131 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 132 "../scanProg.st"
				strcpy(remainingTimeStr, "");
# line 132 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 5/*remainingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 132 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 133 "../scanProg.st"
				strcpy(pauseTimeStr, "");
# line 133 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 6/*pauseTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 133 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 134 "../scanProg.st"
				strcpy(startingTimeStr, "");
# line 134 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 3/*startingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 134 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 135 "../scanProg.st"
				strcpy(totalElapsedTimeStr, "");
# line 135 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 135 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 136 "../scanProg.st"
				strcpy(totalActiveTimeStr, "");
# line 136 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 136 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 137 "../scanProg.st"
				strcpy(hungTimeStr, "");
# line 137 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 18/*hungTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 137 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 138 "../scanProg.st"
				hungSec = (0);
# line 138 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 17/*hungSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 139 "../scanProg.st"
				pauseSec = (0);
# line 139 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 9/*pauseSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 140 "../scanProg.st"
				remainingSec = (0);
# line 140 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 10/*remainingSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 141 "../scanProg.st"
				npts = (0);
# line 141 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 11/*npts*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 142 "../scanProg.st"
				cpt = (0);
# line 142 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 12/*cpt*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 143 "../scanProg.st"
				Npauses = (0);
# line 143 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 15/*Npauses*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 144 "../scanProg.st"
				running = (0);
# line 144 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 13/*running*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 145 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 16/*hangWaitSec*/, DEFAULT, DEFAULT_TIMEOUT);
# line 146 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 32/*busy1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 147 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 33/*busy2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 148 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 34/*busy3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 149 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 35/*busy4*/, DEFAULT, DEFAULT_TIMEOUT);
# line 150 "../scanProg.st"
			beginPause = 0;
# line 151 "../scanProg.st"
			cptAtLastOK = 0;
# line 152 "../scanProg.st"
			seq_efClear(seqg_env, scanProgressDebug_mon);
# line 153 "../scanProg.st"
			seq_efClear(seqg_env, hangWaitSec_mon);
# line 154 "../scanProg.st"
			if (scanProgressDebug >= 1)
			{
# line 154 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 154, SNLtaskName, 1);
# line 154 "../scanProg.st"
				;
# line 154 "../scanProg.st"
				printf("%s\n", "init complete in state init");
# line 154 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 154 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "idle" in state set "scanProgress" ******/

/* Event function for state "idle" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 160 "../scanProg.st"
	if (seq_efTest(seqg_env, scanProgressDebug_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 166 "../scanProg.st"
	if (seq_efTest(seqg_env, hangWaitSec_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 172 "../scanProg.st"
	if (busy1 || busy2 || busy3 || busy4)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "scanProgress" */
static void seqg_action_scanProgress_0_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 161 "../scanProg.st"
			sprintf(new_msg, "changed debug flag to %d", scanProgressDebug);
# line 162 "../scanProg.st"
			if (scanProgressDebug >= 1)
			{
# line 162 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 162, SNLtaskName, 1);
# line 162 "../scanProg.st"
				;
# line 162 "../scanProg.st"
				printf("%s\n", new_msg);
# line 162 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 162 "../scanProg.st"
			;
# line 163 "../scanProg.st"
			seq_efClear(seqg_env, scanProgressDebug_mon);
		}
		return;
	case 1:
		{
# line 167 "../scanProg.st"
			sprintf(new_msg, "changed requred time for a hang to %d (sec)", hangWaitSec);
# line 168 "../scanProg.st"
			if (scanProgressDebug >= 1)
			{
# line 168 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 168, SNLtaskName, 1);
# line 168 "../scanProg.st"
				;
# line 168 "../scanProg.st"
				printf("%s\n", new_msg);
# line 168 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 168 "../scanProg.st"
			;
# line 169 "../scanProg.st"
			seq_efClear(seqg_env, hangWaitSec_mon);
		}
		return;
	case 2:
		{
# line 173 "../scanProg.st"
			if (scanProgressDebug >= 1)
			{
# line 173 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 173, SNLtaskName, 1);
# line 173 "../scanProg.st"
				;
# line 173 "../scanProg.st"
				printf("%s\n", "scan started");
# line 173 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 173 "../scanProg.st"
			;
# line 174 "../scanProg.st"
			if (busy4)
# line 174 "../scanProg.st"
				scanDim = 4;
			else
# line 175 "../scanProg.st"
				if (busy3)
# line 175 "../scanProg.st"
					scanDim = 3;
				else
# line 176 "../scanProg.st"
					if (busy2)
# line 176 "../scanProg.st"
						scanDim = 2;
					else
# line 177 "../scanProg.st"
						scanDim = 1;
# line 178 "../scanProg.st"
			sprintf(new_msg, "got scanDim = %d", scanDim);
# line 179 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 179 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 179, SNLtaskName, 2);
# line 179 "../scanProg.st"
				;
# line 179 "../scanProg.st"
				printf("%s\n", new_msg);
# line 179 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 179 "../scanProg.st"
			;
			startTime = time(0L);
			formatTimeStr(startingTimeStr,40,startTime,1);
# line 182 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 3/*startingTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 183 "../scanProg.st"
				Npauses = (0);
# line 183 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 15/*Npauses*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 184 "../scanProg.st"
				pauseSec = (0);
# line 184 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 9/*pauseSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 185 "../scanProg.st"
				fractionDone = (0.0);
# line 185 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 1/*fractionDone*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 186 "../scanProg.st"
				percentDone = (0.0);
# line 186 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 2/*percentDone*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 187 "../scanProg.st"
				running = (1);
# line 187 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 13/*running*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 188 "../scanProg.st"
				strcpy(totalElapsedTimeStr, "00:00:00");
# line 188 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 188 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 189 "../scanProg.st"
				strcpy(totalActiveTimeStr, "00:00:00");
# line 189 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 189 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 190 "../scanProg.st"
				strcpy(pauseTimeStr, "00:00:00");
# line 190 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 6/*pauseTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 190 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 191 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 20/*npts1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 192 "../scanProg.st"
			npts = npts1;
# line 193 "../scanProg.st"
			if (scanDim >= 2)
			{
# line 194 "../scanProg.st"
				seq_pvGetTmo(seqg_env, 21/*npts2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 195 "../scanProg.st"
				npts *= npts2;
# line 196 "../scanProg.st"
				if (scanDim >= 3)
				{
# line 197 "../scanProg.st"
					seq_pvGetTmo(seqg_env, 22/*npts3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 198 "../scanProg.st"
					npts *= npts3;
# line 199 "../scanProg.st"
					if (scanDim >= 4)
					{
# line 200 "../scanProg.st"
						seq_pvGetTmo(seqg_env, 23/*npts4*/, DEFAULT, DEFAULT_TIMEOUT);
# line 201 "../scanProg.st"
						npts *= npts4;
					}
				}
			}
# line 205 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 11/*npts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 207 "../scanProg.st"
			cptAtLastOK = 0;
# line 208 "../scanProg.st"
			timeOfLastOK = startTime;
			{
# line 209 "../scanProg.st"
				hungSec = (0);
# line 209 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 17/*hungSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 210 "../scanProg.st"
				strcpy(hungTimeStr, "");
# line 210 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 18/*hungTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 210 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
		}
		return;
	}
}

/****** Code for state "duringScan" in state set "scanProgress" ******/

/* Event function for state "duringScan" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_duringScan(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 216 "../scanProg.st"
	if (!(busy1 || busy2 || busy3 || busy4))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 220 "../scanProg.st"
	if (paused)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 225 "../scanProg.st"
	if (seq_delay(seqg_env, 2.))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "duringScan" in state set "scanProgress" */
static void seqg_action_scanProgress_0_duringScan(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 217 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 217 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 217, SNLtaskName, 2);
# line 217 "../scanProg.st"
				;
# line 217 "../scanProg.st"
				printf("%s\n", "in duringScan, scan is done, goto scanFinish");
# line 217 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 217 "../scanProg.st"
			;
		}
		return;
	case 1:
		{
# line 221 "../scanProg.st"
			beginPause = 1;
# line 222 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 222 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 222, SNLtaskName, 2);
# line 222 "../scanProg.st"
				;
# line 222 "../scanProg.st"
				printf("%s\n", "in duringScan, scan is paused, goto duringScanPause");
# line 222 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 222 "../scanProg.st"
			;
		}
		return;
	case 2:
		{
# line 226 "../scanProg.st"
			if (scanProgressDebug >= 3)
			{
# line 226 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 226, SNLtaskName, 3);
# line 226 "../scanProg.st"
				;
# line 226 "../scanProg.st"
				printf("%s\n", "in duringScan, do a regular update to progress");
# line 226 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 226 "../scanProg.st"
			;
# line 227 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 24/*cpt1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 228 "../scanProg.st"
			if (scanDim >= 2)
			{
# line 229 "../scanProg.st"
				seq_pvGetTmo(seqg_env, 25/*cpt2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 230 "../scanProg.st"
				if (scanDim >= 3)
				{
# line 231 "../scanProg.st"
					seq_pvGetTmo(seqg_env, 26/*cpt3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 232 "../scanProg.st"
					if (scanDim >= 4)
					{
# line 233 "../scanProg.st"
						seq_pvGetTmo(seqg_env, 27/*cpt4*/, DEFAULT, DEFAULT_TIMEOUT);
					}
				}
			}
# line 237 "../scanProg.st"
			cpt = calc_cpt();
# line 238 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 12/*cpt*/, DEFAULT, DEFAULT_TIMEOUT);
			fractionDone = (double)cpt/(double)npts;
# line 240 "../scanProg.st"
			sprintf(new_msg, "scanDim = %d,  completed = {%d/%d,  %d/%d,  %d/%d,  %d/%d}, fractionDone = %g", scanDim, cpt1, npts1, cpt2, npts2, cpt3, npts3, cpt4, npts4, fractionDone);
# line 241 "../scanProg.st"
			if (scanProgressDebug >= 4)
			{
# line 241 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 241, SNLtaskName, 4);
# line 241 "../scanProg.st"
				;
# line 241 "../scanProg.st"
				printf("%s\n", new_msg);
# line 241 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 241 "../scanProg.st"
			;
# line 242 "../scanProg.st"
			if (fractionDone > 1.0)
# line 242 "../scanProg.st"
				fractionDone = 1.0;
			else
# line 243 "../scanProg.st"
				if (fractionDone <= 0.0)
# line 243 "../scanProg.st"
					fractionDone = 0.0;
			now = time(0L);
# line 245 "../scanProg.st"
			if (fractionDone > 0.0)
			{
				/* C code definitions */
# line 246 "../scanProg.st"
				remainingSec = (1.0-fractionDone)/fractionDone * (double)(now-startTime-pauseSec);
# line 247 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 10/*remainingSec*/, DEFAULT, DEFAULT_TIMEOUT);
# line 248 "../scanProg.st"
				predictEnd = now + remainingSec;
				clocks2str(remainingSec,tStr);
				{
# line 250 "../scanProg.st"
					strcpy(remainingTimeStr, tStr);
# line 250 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 5/*remainingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 250 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				clocks2str(now-startTime,tStr);
				{
# line 252 "../scanProg.st"
					strcpy(totalElapsedTimeStr, tStr);
# line 252 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 252 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				clocks2str(now-startTime-pauseSec,tStr);
				{
# line 254 "../scanProg.st"
					strcpy(totalActiveTimeStr, tStr);
# line 254 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 254 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				formatTimeStr(endingTimeStr,40,predictEnd,0);
# line 256 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
# line 257 "../scanProg.st"
				sprintf(new_msg, "   now = %ld sec,   remaining = %d,  predictEnd = %ld", now, remainingSec, predictEnd);
# line 258 "../scanProg.st"
				if (scanProgressDebug >= 5)
				{
# line 258 "../scanProg.st"
					printf("<%s,%d,%s,%d> ", "../scanProg.st", 258, SNLtaskName, 5);
# line 258 "../scanProg.st"
					;
# line 258 "../scanProg.st"
					printf("%s\n", new_msg);
# line 258 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
# line 258 "../scanProg.st"
				;
# line 259 "../scanProg.st"
				sprintf(new_msg, "   remainingTimeStr = '%s',   endingTimeStr = '%s'", remainingTimeStr, endingTimeStr);
# line 260 "../scanProg.st"
				if (scanProgressDebug >= 5)
				{
# line 260 "../scanProg.st"
					printf("<%s,%d,%s,%d> ", "../scanProg.st", 260, SNLtaskName, 5);
# line 260 "../scanProg.st"
					;
# line 260 "../scanProg.st"
					printf("%s\n", new_msg);
# line 260 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
# line 260 "../scanProg.st"
				;
			}
			else
			{
				{
# line 263 "../scanProg.st"
					strcpy(remainingTimeStr, "");
# line 263 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 5/*remainingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 263 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				{
# line 264 "../scanProg.st"
					strcpy(totalActiveTimeStr, "");
# line 264 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 264 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				{
# line 265 "../scanProg.st"
					strcpy(endingTimeStr, "");
# line 265 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 265 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				{
# line 266 "../scanProg.st"
					strcpy(totalElapsedTimeStr, "");
# line 266 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 266 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				{
# line 267 "../scanProg.st"
					remainingSec = (0);
# line 267 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 10/*remainingSec*/, SYNC, DEFAULT_TIMEOUT);
				}
			}
# line 269 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 1/*fractionDone*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 270 "../scanProg.st"
				percentDone = (100.0 * fractionDone);
# line 270 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 2/*percentDone*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 272 "../scanProg.st"
			if (cpt != cptAtLastOK)
			{
# line 273 "../scanProg.st"
				cptAtLastOK = cpt;
# line 274 "../scanProg.st"
				timeOfLastOK = now;
				{
# line 275 "../scanProg.st"
					hungSec = (0);
# line 275 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 17/*hungSec*/, SYNC, DEFAULT_TIMEOUT);
				}
				{
# line 276 "../scanProg.st"
					strcpy(hungTimeStr, "");
# line 276 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 18/*hungTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 276 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
			}
			else
# line 278 "../scanProg.st"
				if ((now - timeOfLastOK) > hangWaitSec)
				{
# line 279 "../scanProg.st"
					hungSec = now - timeOfLastOK;
# line 280 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 17/*hungSec*/, DEFAULT, DEFAULT_TIMEOUT);
					clocks2str(hungSec,tStr);
					{
# line 282 "../scanProg.st"
						strcpy(hungTimeStr, tStr);
# line 282 "../scanProg.st"
						seq_pvPutTmo(seqg_env, 18/*hungTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 282 "../scanProg.st"
						epicsThreadSleep(0.01);
					}
				}
		}
		return;
	}
}

/****** Code for state "duringScanPause" in state set "scanProgress" ******/

/* Event function for state "duringScanPause" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_duringScanPause(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 290 "../scanProg.st"
	if (!(busy1 || busy2 || busy3 || busy4))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 294 "../scanProg.st"
	if (beginPause)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 304 "../scanProg.st"
	if (!paused)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 314 "../scanProg.st"
	if (seq_delay(seqg_env, 2.))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 3;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "duringScanPause" in state set "scanProgress" */
static void seqg_action_scanProgress_0_duringScanPause(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 291 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 291 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 291, SNLtaskName, 2);
# line 291 "../scanProg.st"
				;
# line 291 "../scanProg.st"
				printf("%s\n", "in duringScanPause, scan is done, goto scanFinish");
# line 291 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 291 "../scanProg.st"
			;
		}
		return;
	case 1:
		{
# line 295 "../scanProg.st"
			beginPause = 0;
			pauseStart = time(0L);
			{
# line 297 "../scanProg.st"
				Npauses = (Npauses + 1);
# line 297 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 15/*Npauses*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 298 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 298 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 298, SNLtaskName, 2);
# line 298 "../scanProg.st"
				;
# line 298 "../scanProg.st"
				printf("%s\n", "in duringScanPause, started a scan pause");
# line 298 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 298 "../scanProg.st"
			;
# line 299 "../scanProg.st"
			timeOfLastOK = pauseStart;
			{
# line 300 "../scanProg.st"
				hungSec = (0);
# line 300 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 17/*hungSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 301 "../scanProg.st"
				strcpy(hungTimeStr, "");
# line 301 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 18/*hungTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 301 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
		}
		return;
	case 2:
		{
			/* C code definitions */
# line 305 "../scanProg.st"
			now = time(0L);
# line 306 "../scanProg.st"
			pauseSec += now - pauseStart;
# line 307 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 9/*pauseSec*/, DEFAULT, DEFAULT_TIMEOUT);
			clocks2str(pauseSec,tStr);
			{
# line 309 "../scanProg.st"
				strcpy(pauseTimeStr, tStr);
# line 309 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 6/*pauseTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 309 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 310 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 310 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 310, SNLtaskName, 2);
# line 310 "../scanProg.st"
				;
# line 310 "../scanProg.st"
				printf("%s\n", "in duringScanPause, scan pause rescinded");
# line 310 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 310 "../scanProg.st"
			;
# line 311 "../scanProg.st"
			timeOfLastOK = now;
		}
		return;
	case 3:
		{
			/* C code definitions */
# line 315 "../scanProg.st"
			now = time(0L);
# line 316 "../scanProg.st"
			clocks2str(now-pauseStart,tStr);
# line 317 "../scanProg.st"
			clocks2str(now-pauseStart+pauseSec,tStr1);
# line 318 "../scanProg.st"
			sprintf(pauseTimeStr, "current %s,  total %s", tStr, tStr1);
# line 319 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 6/*pauseTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
			clocks2str(now-startTime,tStr);
			{
# line 321 "../scanProg.st"
				strcpy(totalElapsedTimeStr, tStr);
# line 321 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 321 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 322 "../scanProg.st"
			if (fractionDone > 0.0)
			{
				/* C code definitions */
# line 323 "../scanProg.st"
				remainingSec = (1.0-fractionDone)/fractionDone * (double)(now-startTime-pauseSec);
# line 324 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 10/*remainingSec*/, DEFAULT, DEFAULT_TIMEOUT);
# line 325 "../scanProg.st"
				predictEnd = now + remainingSec;
				formatTimeStr(endingTimeStr,40,predictEnd,0);
# line 327 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 329 "../scanProg.st"
			sprintf(new_msg, "   periodic check in duringScanPause, time paused; '%s', ", pauseTimeStr);
# line 330 "../scanProg.st"
			if (scanProgressDebug >= 5)
			{
# line 330 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 330, SNLtaskName, 5);
# line 330 "../scanProg.st"
				;
# line 330 "../scanProg.st"
				printf("%s\n", new_msg);
# line 330 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 330 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "scanFinish" in state set "scanProgress" ******/

/* Event function for state "scanFinish" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_scanFinish(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 336 "../scanProg.st"
	if (1)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "scanFinish" in state set "scanProgress" */
static void seqg_action_scanProgress_0_scanFinish(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
			/* C code definitions */
# line 337 "../scanProg.st"
			now = time(0L);
			{
# line 338 "../scanProg.st"
				strcpy(remainingTimeStr, "00:00:00");
# line 338 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 5/*remainingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 338 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			clocks2str(now-startTime-pauseSec,tStr);
			{
# line 340 "../scanProg.st"
				strcpy(totalActiveTimeStr, tStr);
# line 340 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 340 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			clocks2str(now-startTime,tStr);
			{
# line 342 "../scanProg.st"
				strcpy(totalElapsedTimeStr, tStr);
# line 342 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 342 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			formatTimeStr(endingTimeStr,40,now,1);
# line 344 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 345 "../scanProg.st"
				running = (0);
# line 345 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 13/*running*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 346 "../scanProg.st"
				remainingSec = (0);
# line 346 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 10/*remainingSec*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 349 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 24/*cpt1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 350 "../scanProg.st"
			if (scanDim >= 2)
			{
# line 351 "../scanProg.st"
				seq_pvGetTmo(seqg_env, 25/*cpt2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 352 "../scanProg.st"
				if (scanDim >= 3)
				{
# line 353 "../scanProg.st"
					seq_pvGetTmo(seqg_env, 26/*cpt3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 354 "../scanProg.st"
					if (scanDim >= 4)
					{
# line 355 "../scanProg.st"
						seq_pvGetTmo(seqg_env, 27/*cpt4*/, DEFAULT, DEFAULT_TIMEOUT);
					}
				}
			}
# line 359 "../scanProg.st"
			cpt = calc_cpt();
# line 360 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 12/*cpt*/, DEFAULT, DEFAULT_TIMEOUT);
			fractionDone = (double)cpt/(double)npts;
# line 362 "../scanProg.st"
			if (fractionDone > 1.0)
# line 362 "../scanProg.st"
				fractionDone = 1.0;
# line 363 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 1/*fractionDone*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 364 "../scanProg.st"
				percentDone = (100.0 * fractionDone);
# line 364 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 2/*percentDone*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 365 "../scanProg.st"
				hungSec = (0);
# line 365 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 17/*hungSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 366 "../scanProg.st"
				strcpy(hungTimeStr, "");
# line 366 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 18/*hungTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 366 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 367 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 367 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 367, SNLtaskName, 2);
# line 367 "../scanProg.st"
				;
# line 367 "../scanProg.st"
				printf("%s\n", "no scan is busy in duringScan, back to idle");
# line 367 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 367 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "initPause" in state set "scanPauseUpdate" ******/

/* Event function for state "initPause" in state set "scanPauseUpdate" */
static seqBool seqg_event_scanPauseUpdate_1_initPause(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "initPause" in state set "scanPauseUpdate" */
static void seqg_action_scanPauseUpdate_1_initPause(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
			{
# line 381 "../scanProg.st"
				paused = (0);
# line 381 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 14/*paused*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 382 "../scanProg.st"
			almostPaused = 0;
# line 383 "../scanProg.st"
			epicsThreadSleep(1.0);
# line 384 "../scanProg.st"
			seq_efSet(seqg_env, pause1_mon);
# line 385 "../scanProg.st"
			if (scanProgressDebug >= 1)
			{
# line 385 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 385, SNLtaskName, 1);
# line 385 "../scanProg.st"
				;
# line 385 "../scanProg.st"
				printf("%s\n", "completed state initPause");
# line 385 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 385 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "idlePause" in state set "scanPauseUpdate" ******/

/* Event function for state "idlePause" in state set "scanPauseUpdate" */
static seqBool seqg_event_scanPauseUpdate_1_idlePause(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 391 "../scanProg.st"
	if (seq_efTest(seqg_env, pause1_mon) || seq_efTest(seqg_env, pause2_mon) || seq_efTest(seqg_env, pause3_mon) || seq_efTest(seqg_env, pause4_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 402 "../scanProg.st"
	if (almostPaused && (seq_efTest(seqg_env, busy1_mon) || seq_efTest(seqg_env, busy2_mon) || seq_efTest(seqg_env, busy3_mon) || seq_efTest(seqg_env, busy4_mon)))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 411 "../scanProg.st"
	if (seq_delay(seqg_env, 20.))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idlePause" in state set "scanPauseUpdate" */
static void seqg_action_scanPauseUpdate_1_idlePause(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 392 "../scanProg.st"
			sprintf(new_msg, "at top of state idlePause, monitors are : =%d,  %d,  %d,  %d", pause1_mon, pause2_mon, pause3_mon, pause4_mon);
# line 393 "../scanProg.st"
			if (scanProgressDebug >= 7)
			{
# line 393 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 393, SNLtaskName, 7);
# line 393 "../scanProg.st"
				;
# line 393 "../scanProg.st"
				printf("%s\n", new_msg);
# line 393 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 393 "../scanProg.st"
			;
# line 395 "../scanProg.st"
			seq_efClear(seqg_env, pause1_mon);
# line 396 "../scanProg.st"
			seq_efClear(seqg_env, pause2_mon);
# line 397 "../scanProg.st"
			seq_efClear(seqg_env, pause3_mon);
# line 398 "../scanProg.st"
			seq_efClear(seqg_env, pause4_mon);
		}
		return;
	case 1:
		{
# line 403 "../scanProg.st"
			sprintf(new_msg, "paused but waiting for busy, busy flags are:  busy1=%d, busy2=%d, busy3=%d, busy4=%d", busy1, busy2, busy3, busy4);
# line 404 "../scanProg.st"
			if (scanProgressDebug >= 6)
			{
# line 404 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 404, SNLtaskName, 6);
# line 404 "../scanProg.st"
				;
# line 404 "../scanProg.st"
				printf("%s\n", new_msg);
# line 404 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 404 "../scanProg.st"
			;
# line 405 "../scanProg.st"
			seq_efClear(seqg_env, busy1_mon);
# line 406 "../scanProg.st"
			seq_efClear(seqg_env, busy2_mon);
# line 407 "../scanProg.st"
			seq_efClear(seqg_env, busy3_mon);
# line 408 "../scanProg.st"
			seq_efClear(seqg_env, busy4_mon);
		}
		return;
	case 2:
		{
# line 412 "../scanProg.st"
			if (scanProgressDebug >= 7)
			{
# line 412 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 412, SNLtaskName, 7);
# line 412 "../scanProg.st"
				;
# line 412 "../scanProg.st"
				printf("%s\n", "delay(UPDATE_DELAY_LONG) in scanPauseUpdate");
# line 412 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 412 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "checkAndSetPause" in state set "scanPauseUpdate" ******/

/* Event function for state "checkAndSetPause" in state set "scanPauseUpdate" */
static seqBool seqg_event_scanPauseUpdate_1_checkAndSetPause(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 418 "../scanProg.st"
	if (1)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "checkAndSetPause" in state set "scanPauseUpdate" */
static void seqg_action_scanPauseUpdate_1_checkAndSetPause(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 419 "../scanProg.st"
			sprintf(new_msg, "paused flags are pause1=%d, pause2=%d, pause3=%d, pause4=%d", pause1, pause2, pause3, pause4);
# line 420 "../scanProg.st"
			if (scanProgressDebug >= 8)
			{
# line 420 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 420, SNLtaskName, 8);
# line 420 "../scanProg.st"
				;
# line 420 "../scanProg.st"
				printf("%s\n", new_msg);
# line 420 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 420 "../scanProg.st"
			;
# line 421 "../scanProg.st"
			aPause = pause1;
# line 422 "../scanProg.st"
			if (scanDim > 1)
			{
# line 423 "../scanProg.st"
				aPause = aPause || pause2;
# line 424 "../scanProg.st"
				if (scanDim > 2)
				{
# line 425 "../scanProg.st"
					aPause = aPause || pause3;
# line 426 "../scanProg.st"
					if (scanDim > 3)
					{
# line 427 "../scanProg.st"
						aPause = aPause || pause4;
					}
				}
			}
# line 431 "../scanProg.st"
			stopped = allStopped();
# line 432 "../scanProg.st"
			almostPaused = aPause && !stopped;
# line 433 "../scanProg.st"
			paused = aPause && stopped;
# line 434 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 14/*paused*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{P}debug", (size_t)&scanProgressDebug, "scanProgressDebug", P_SHORT, 1, 11, 1, 1, 0, 0},
	{"{P}fractionDone", (size_t)&fractionDone, "fractionDone", P_DOUBLE, 1, 12, 0, 0, 0, 0},
	{"{P}percentDone", (size_t)&percentDone, "percentDone", P_DOUBLE, 1, 13, 0, 0, 0, 0},
	{"{P}startingTimeStr", (size_t)&startingTimeStr, "startingTimeStr", P_STRING, 1, 14, 0, 0, 0, 0},
	{"{P}endingTimeStr", (size_t)&endingTimeStr, "endingTimeStr", P_STRING, 1, 15, 0, 0, 0, 0},
	{"{P}remainingTimeStr", (size_t)&remainingTimeStr, "remainingTimeStr", P_STRING, 1, 16, 0, 0, 0, 0},
	{"{P}pauseTimeStr", (size_t)&pauseTimeStr, "pauseTimeStr", P_STRING, 1, 17, 0, 0, 0, 0},
	{"{P}totalElapsedTimeStr", (size_t)&totalElapsedTimeStr, "totalElapsedTimeStr", P_STRING, 1, 18, 0, 0, 0, 0},
	{"{P}totalActiveTimeStr", (size_t)&totalActiveTimeStr, "totalActiveTimeStr", P_STRING, 1, 19, 0, 0, 0, 0},
	{"{P}pauseSec", (size_t)&pauseSec, "pauseSec", P_INT, 1, 20, 0, 0, 0, 0},
	{"{P}remainingSec", (size_t)&remainingSec, "remainingSec", P_INT, 1, 21, 0, 0, 0, 0},
	{"{P}Ntotal", (size_t)&npts, "npts", P_INT, 1, 22, 0, 0, 0, 0},
	{"{P}Nfinished", (size_t)&cpt, "cpt", P_INT, 1, 23, 0, 0, 0, 0},
	{"{P}running", (size_t)&running, "running", P_SHORT, 1, 24, 0, 0, 0, 0},
	{"{P}paused", (size_t)&paused, "paused", P_SHORT, 1, 25, 0, 0, 0, 0},
	{"{P}Npauses", (size_t)&Npauses, "Npauses", P_INT, 1, 26, 0, 0, 0, 0},
	{"{P}hangWaitSec", (size_t)&hangWaitSec, "hangWaitSec", P_INT, 1, 27, 2, 1, 0, 0},
	{"{P}hungSec", (size_t)&hungSec, "hungSec", P_INT, 1, 28, 0, 0, 0, 0},
	{"{P}hungTimeStr", (size_t)&hungTimeStr, "hungTimeStr", P_STRING, 1, 29, 0, 0, 0, 0},
	{"{P}version", (size_t)&version, "version", P_DOUBLE, 1, 30, 0, 0, 0, 0},
	{"{S}scan1.NPTS", (size_t)&npts1, "npts1", P_INT, 1, 31, 0, 0, 0, 0},
	{"{S}scan2.NPTS", (size_t)&npts2, "npts2", P_INT, 1, 32, 0, 0, 0, 0},
	{"{S}scan3.NPTS", (size_t)&npts3, "npts3", P_INT, 1, 33, 0, 0, 0, 0},
	{"{S}scan4.NPTS", (size_t)&npts4, "npts4", P_INT, 1, 34, 0, 0, 0, 0},
	{"{S}scan1.CPT", (size_t)&cpt1, "cpt1", P_INT, 1, 35, 0, 0, 0, 0},
	{"{S}scan2.CPT", (size_t)&cpt2, "cpt2", P_INT, 1, 36, 0, 0, 0, 0},
	{"{S}scan3.CPT", (size_t)&cpt3, "cpt3", P_INT, 1, 37, 0, 0, 0, 0},
	{"{S}scan4.CPT", (size_t)&cpt4, "cpt4", P_INT, 1, 38, 0, 0, 0, 0},
	{"{S}scan1.PAUS", (size_t)&pause1, "pause1", P_SHORT, 1, 39, 3, 1, 0, 0},
	{"{S}scan2.PAUS", (size_t)&pause2, "pause2", P_SHORT, 1, 40, 4, 1, 0, 0},
	{"{S}scan3.PAUS", (size_t)&pause3, "pause3", P_SHORT, 1, 41, 5, 1, 0, 0},
	{"{S}scan4.PAUS", (size_t)&pause4, "pause4", P_SHORT, 1, 42, 6, 1, 0, 0},
	{"{S}scan1.BUSY", (size_t)&busy1, "busy1", P_SHORT, 1, 43, 7, 1, 0, 0},
	{"{S}scan2.BUSY", (size_t)&busy2, "busy2", P_SHORT, 1, 44, 8, 1, 0, 0},
	{"{S}scan3.BUSY", (size_t)&busy3, "busy3", P_SHORT, 1, 45, 9, 1, 0, 0},
	{"{S}scan4.BUSY", (size_t)&busy4, "busy4", P_SHORT, 1, 46, 10, 1, 0, 0},
};

/* Event masks for state set "scanProgress" */
static const seqMask seqg_mask_scanProgress_0_init[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_scanProgress_0_idle[] = {
	0x00000006,
	0x00007800,
};
static const seqMask seqg_mask_scanProgress_0_duringScan[] = {
	0x02000000,
	0x00007800,
};
static const seqMask seqg_mask_scanProgress_0_duringScanPause[] = {
	0x02000000,
	0x00007800,
};
static const seqMask seqg_mask_scanProgress_0_scanFinish[] = {
	0x00000000,
	0x00000000,
};

/* State table for state set "scanProgress" */
static seqState seqg_states_scanProgress[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_scanProgress_0_init,
	/* event function */    seqg_event_scanProgress_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "idle",
	/* action function */   seqg_action_scanProgress_0_idle,
	/* event function */    seqg_event_scanProgress_0_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_idle,
	/* state options */     (0)
	},
	{
	/* state name */        "duringScan",
	/* action function */   seqg_action_scanProgress_0_duringScan,
	/* event function */    seqg_event_scanProgress_0_duringScan,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_duringScan,
	/* state options */     (0)
	},
	{
	/* state name */        "duringScanPause",
	/* action function */   seqg_action_scanProgress_0_duringScanPause,
	/* event function */    seqg_event_scanProgress_0_duringScanPause,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_duringScanPause,
	/* state options */     (0)
	},
	{
	/* state name */        "scanFinish",
	/* action function */   seqg_action_scanProgress_0_scanFinish,
	/* event function */    seqg_event_scanProgress_0_scanFinish,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_scanFinish,
	/* state options */     (0)
	},
};

/* Event masks for state set "scanPauseUpdate" */
static const seqMask seqg_mask_scanPauseUpdate_1_initPause[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_scanPauseUpdate_1_idlePause[] = {
	0x000007f8,
	0x00000000,
};
static const seqMask seqg_mask_scanPauseUpdate_1_checkAndSetPause[] = {
	0x00000000,
	0x00000000,
};

/* State table for state set "scanPauseUpdate" */
static seqState seqg_states_scanPauseUpdate[] = {
	{
	/* state name */        "initPause",
	/* action function */   seqg_action_scanPauseUpdate_1_initPause,
	/* event function */    seqg_event_scanPauseUpdate_1_initPause,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanPauseUpdate_1_initPause,
	/* state options */     (0)
	},
	{
	/* state name */        "idlePause",
	/* action function */   seqg_action_scanPauseUpdate_1_idlePause,
	/* event function */    seqg_event_scanPauseUpdate_1_idlePause,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanPauseUpdate_1_idlePause,
	/* state options */     (0)
	},
	{
	/* state name */        "checkAndSetPause",
	/* action function */   seqg_action_scanPauseUpdate_1_checkAndSetPause,
	/* event function */    seqg_event_scanPauseUpdate_1_checkAndSetPause,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanPauseUpdate_1_checkAndSetPause,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "scanProgress",
	/* states */            seqg_states_scanProgress,
	/* number of states */  5
	},

	{
	/* state set name */    "scanPauseUpdate",
	/* states */            seqg_states_scanPauseUpdate,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram scanProgress = {
	/* magic number */      2002005,
	/* program name */      "scanProgress",
	/* channels */          seqg_chans,
	/* num. channels */     36,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     0,
	/* param */             "S=34ide:, P=34ide:scanProgress:",
	/* num. event flags */  10,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};
# line 441 "../scanProg.st"


static long calc_cpt(void)
{
 long lcpt;
 long nBelow;

 lcpt = cpt1;
 if (scanDim<2) return lcpt;

 nBelow = npts1;
 lcpt += cpt2 * nBelow;
 if (scanDim<3) return lcpt;

 nBelow *= npts2;
 lcpt += cpt3 * nBelow;
 if (scanDim<4) return lcpt;

 nBelow *= npts3;
 lcpt += cpt4*nBelow;
 return lcpt;
}




static void clocks2str(long isec, char *str)
{
 int hh,mm,ss;
 int sign=1;
 if (isec>32000000) {
  strcpy(str,"infinite");
  return;
 }
 else if (isec<-32000000) {
  strcpy(str,"-infinite");
  return;
 }
 else if (isec<0) {
  isec *= -1;
  sign = -1;
 }
 ss = isec % 60;
 isec /= 60;
 mm = isec % 60;
 hh = sign * isec / 60;
 sprintf(str,"%02d:%02d:%02d",hh,mm,ss);
 return;
}



static void formatTimeStr(
char *tStr,
int tStrLen,
time_t final,
int full)
{
 time_t now;
 struct tm *tm1;
 int isToday=0;
 int isTomorrow=0;
 int isYesterday=0;
 int hh,mm,ss;
 time_t final_t = (time_t)final;

 if (!full) {
  tm1 = localtime(&final_t);
  hh = tm1->tm_hour;
  mm = tm1->tm_min;
  ss = tm1->tm_sec;

  now = time(0L);
  tm1 = localtime(&now);
  tm1->tm_hour = hh;
  tm1->tm_min = mm;
  tm1->tm_sec = ss;
  isToday = (final_t==mktime(tm1));
  if (!isToday) {
   tm1->tm_mday++;
   isTomorrow = (final_t==mktime(tm1));
  }
  if (!isToday && !isTomorrow) {
   tm1->tm_mday -= 2;
   isYesterday = (final_t==mktime(tm1));
  }
 }

 tm1 = localtime(&final_t);
 if (isToday) strftime(tStr,tStrLen, "%H:%M:%S Today (%A)",tm1);
 else if (isTomorrow) strftime(tStr,tStrLen, "%H:%M:%S Tomorrow (%A)",tm1);
 else if (isYesterday) strftime(tStr,tStrLen, "%H:%M:%S Yesterday (%A)",tm1);
 else strftime(tStr,tStrLen, "%H:%M:%S  (%a) %b %d, %Y",tm1);
 return;
}


static int allStopped(void)
{
 int stopCount;

 stopCount = (pause1 || !busy1) ? 1 : 0;
 stopCount += (scanDim<2) || (pause2 || !busy2) ? 2 : 0;
 stopCount += (scanDim<3) || (pause3 || !busy3) ? 4 : 0;
 stopCount += (scanDim<4) || (pause4 || !busy4) ? 8 : 0;
 return (stopCount==15);
}



/* Register sequencer commands and program */
#include "epicsExport.h"
static void scanProgressRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&scanProgress);
}
epicsExportRegistrar(scanProgressRegistrar);
