/* C code for program Keithley65xxEM, generated by snc from ../Keithley65xxEM.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 27 "../Keithley65xxEM.st"
#include "stdlib.h"
# line 28 "../Keithley65xxEM.st"
#include "string.h"
# line 49 "../Keithley65xxEM.st"
static const EF_ID ch_mode_mon = 1;
# line 95 "../Keithley65xxEM.st"
static const EF_ID ch_mode_sel_mon = 2;
# line 106 "../Keithley65xxEM.st"
static const EF_ID dmm_chan_mon = 3;
# line 121 "../Keithley65xxEM.st"
static const EF_ID read_complete_mon = 4;
# line 131 "../Keithley65xxEM.st"
static const EF_ID init_dmm_mon = 5;

/* Variable declarations */
struct seqg_vars {
# line 30 "../Keithley65xxEM.st"
	int i;
# line 31 "../Keithley65xxEM.st"
	int scan_chan;
# line 32 "../Keithley65xxEM.st"
	int previous_mode;
# line 33 "../Keithley65xxEM.st"
	int previous_chan;
# line 35 "../Keithley65xxEM.st"
	int ch_mode[10];
# line 52 "../Keithley65xxEM.st"
	int ch_on_off[10];
# line 66 "../Keithley65xxEM.st"
	int ch_raw[10];
# line 81 "../Keithley65xxEM.st"
	int dmm_modes[4];
# line 92 "../Keithley65xxEM.st"
	int ch_mode_sel;
# line 99 "../Keithley65xxEM.st"
	int done_read;
# line 103 "../Keithley65xxEM.st"
	int dmm_chan;
# line 109 "../Keithley65xxEM.st"
	int dmm_delay_read;
# line 112 "../Keithley65xxEM.st"
	int dmm_read;
# line 115 "../Keithley65xxEM.st"
	int Dmm_raw;
# line 118 "../Keithley65xxEM.st"
	int read_complete;
# line 124 "../Keithley65xxEM.st"
	int single_multi;
# line 128 "../Keithley65xxEM.st"
	int init_dmm;
# line 134 "../Keithley65xxEM.st"
	int do_init;
# line 137 "../Keithley65xxEM.st"
	string ch_close;
# line 138 "../Keithley65xxEM.st"
	string model;
# line 139 "../Keithley65xxEM.st"
	int channels;
# line 140 "../Keithley65xxEM.st"
	string dmm_units;
# line 141 "../Keithley65xxEM.st"
	string ch_units;
# line 143 "../Keithley65xxEM.st"
	char *unit_strings[4];
# line 144 "../Keithley65xxEM.st"
	char *P;
# line 145 "../Keithley65xxEM.st"
	char *Dmm;
# line 146 "../Keithley65xxEM.st"
	string pvname;
# line 147 "../Keithley65xxEM.st"
	string close_format;
# line 148 "../Keithley65xxEM.st"
	int mode;
# line 149 "../Keithley65xxEM.st"
	int chan;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "mode_change" ******/

/* Event function for state "init" in state set "mode_change" */
static seqBool seqg_event_mode_change_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "mode_change" */
static void seqg_action_mode_change_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 156 "../Keithley65xxEM.st"
			seq_efSet(seqg_env, ch_mode_mon);
# line 157 "../Keithley65xxEM.st"
			seq_efSet(seqg_env, ch_mode_sel_mon);
# line 158 "../Keithley65xxEM.st"
			seq_efSet(seqg_env, dmm_chan_mon);
# line 159 "../Keithley65xxEM.st"
			seqg_var->unit_strings[0] = "VOLT";
# line 160 "../Keithley65xxEM.st"
			seqg_var->unit_strings[1] = "AMP";
# line 161 "../Keithley65xxEM.st"
			seqg_var->unit_strings[2] = "OHM";
# line 162 "../Keithley65xxEM.st"
			seqg_var->unit_strings[3] = "COULOMB";
# line 163 "../Keithley65xxEM.st"
			seqg_var->P = seq_macValueGet(seqg_env, "P");
# line 164 "../Keithley65xxEM.st"
			seqg_var->Dmm = seq_macValueGet(seqg_env, "Dmm");
# line 165 "../Keithley65xxEM.st"
			strcpy(seqg_var->model, seq_macValueGet(seqg_env, "model"));
# line 166 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 45/*model*/, DEFAULT, DEFAULT_TIMEOUT);
# line 167 "../Keithley65xxEM.st"
			seqg_var->channels = atoi(seq_macValueGet(seqg_env, "channels"));
# line 168 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 46/*channels*/, DEFAULT, DEFAULT_TIMEOUT);
# line 169 "../Keithley65xxEM.st"
			if (strcmp(seqg_var->model, "6517A") == 0)
			{
# line 170 "../Keithley65xxEM.st"
				strcpy(seqg_var->close_format, "rout:clos (@%d)");
			}
			else
			{
# line 172 "../Keithley65xxEM.st"
				strcpy(seqg_var->close_format, "rout:clos (@%d)");
			}
		}
		return;
	}
}

/****** Code for state "monitor_mode_changes" in state set "mode_change" ******/

/* Event function for state "monitor_mode_changes" in state set "mode_change" */
static seqBool seqg_event_mode_change_0_monitor_mode_changes(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 177 "../Keithley65xxEM.st"
	if (seq_efTestAndClear(seqg_env, ch_mode_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 193 "../Keithley65xxEM.st"
	if (seq_efTestAndClear(seqg_env, ch_mode_sel_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 206 "../Keithley65xxEM.st"
	if (seq_efTestAndClear(seqg_env, dmm_chan_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 212 "../Keithley65xxEM.st"
	if (seq_efTestAndClear(seqg_env, init_dmm_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 3;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "monitor_mode_changes" in state set "mode_change" */
static void seqg_action_mode_change_0_monitor_mode_changes(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 178 "../Keithley65xxEM.st"
			for (seqg_var->i = 0; seqg_var->i < seqg_var->channels; seqg_var->i++)
			{
# line 185 "../Keithley65xxEM.st"
				seqg_var->mode = seqg_var->ch_mode[seqg_var->i];
# line 186 "../Keithley65xxEM.st"
				sprintf(seqg_var->ch_units, "%s", seqg_var->unit_strings[seqg_var->mode]);
# line 187 "../Keithley65xxEM.st"
				sprintf(seqg_var->pvname, "%s%sch%d_units.VAL", seqg_var->P, seqg_var->Dmm, seqg_var->i + 1);
# line 188 "../Keithley65xxEM.st"
				seq_pvAssign(seqg_env, 48/*ch_units*/, seqg_var->pvname);
# line 189 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 48/*ch_units*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	case 1:
		{
# line 194 "../Keithley65xxEM.st"
			sprintf(seqg_var->dmm_units, "%s", seqg_var->unit_strings[seqg_var->ch_mode_sel]);
# line 195 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 47/*dmm_units*/, DEFAULT, DEFAULT_TIMEOUT);
# line 196 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 30/*dmm_modes*/ + (CH_ID)(seqg_var->ch_mode_sel), DEFAULT, DEFAULT_TIMEOUT);
# line 197 "../Keithley65xxEM.st"
			seqg_var->previous_mode = seqg_var->ch_mode_sel;
# line 199 "../Keithley65xxEM.st"
			if (seqg_var->ch_mode_sel == 3)
			{
# line 200 "../Keithley65xxEM.st"
				sprintf(seqg_var->ch_close, "rout:open:all");
# line 201 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 44/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 202 "../Keithley65xxEM.st"
				seqg_var->previous_chan = -1;
			}
		}
		return;
	case 2:
		{
# line 207 "../Keithley65xxEM.st"
			sprintf(seqg_var->ch_close, seqg_var->close_format, seqg_var->dmm_chan + 1);
# line 208 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 44/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 209 "../Keithley65xxEM.st"
			seqg_var->previous_chan = seqg_var->dmm_chan;
		}
		return;
	case 3:
		{
# line 213 "../Keithley65xxEM.st"
			if (seqg_var->init_dmm == 1)
			{
# line 214 "../Keithley65xxEM.st"
				seqg_var->scan_chan = 0;
# line 215 "../Keithley65xxEM.st"
				seqg_var->previous_mode = -1;
# line 216 "../Keithley65xxEM.st"
				seqg_var->previous_chan = -1;
# line 217 "../Keithley65xxEM.st"
				seqg_var->init_dmm = 0;
# line 218 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 42/*init_dmm*/, DEFAULT, DEFAULT_TIMEOUT);
# line 219 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 43/*do_init*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

/****** Code for state "init" in state set "read_meter" ******/

/* Event function for state "init" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "read_meter" */
static void seqg_action_read_meter_1_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 228 "../Keithley65xxEM.st"
			seqg_var->scan_chan = 0;
# line 229 "../Keithley65xxEM.st"
			seqg_var->previous_mode = -1;
# line 230 "../Keithley65xxEM.st"
			seqg_var->previous_chan = -1;
# line 231 "../Keithley65xxEM.st"
			seq_efClear(seqg_env, read_complete_mon);
# line 232 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 43/*do_init*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "wait_read" in state set "read_meter" ******/

/* Event function for state "wait_read" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_wait_read(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 236 "../Keithley65xxEM.st"
	if (seqg_var->done_read == 1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait_read" in state set "read_meter" */
static void seqg_action_read_meter_1_wait_read(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "read_channel" in state set "read_meter" ******/

/* Event function for state "read_channel" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_read_channel(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 240 "../Keithley65xxEM.st"
	if (seqg_var->single_multi == 0)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 267 "../Keithley65xxEM.st"
	if ((seqg_var->single_multi != 0) && (seqg_var->ch_on_off[seqg_var->scan_chan] == 0))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 289 "../Keithley65xxEM.st"
	if ((seqg_var->single_multi != 0) && (seqg_var->ch_on_off[seqg_var->scan_chan] != 0))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "read_channel" in state set "read_meter" */
static void seqg_action_read_meter_1_read_channel(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 241 "../Keithley65xxEM.st"
			if (seqg_var->ch_mode_sel != seqg_var->previous_mode)
			{
# line 242 "../Keithley65xxEM.st"
				sprintf(seqg_var->dmm_units, "%s", seqg_var->unit_strings[seqg_var->ch_mode_sel]);
# line 243 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 47/*dmm_units*/, DEFAULT, DEFAULT_TIMEOUT);
# line 244 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 30/*dmm_modes*/ + (CH_ID)(seqg_var->ch_mode_sel), DEFAULT, DEFAULT_TIMEOUT);
			}
# line 247 "../Keithley65xxEM.st"
			seqg_var->chan = seqg_var->dmm_chan;
# line 248 "../Keithley65xxEM.st"
			if (seqg_var->chan != seqg_var->previous_chan)
			{
# line 249 "../Keithley65xxEM.st"
				sprintf(seqg_var->ch_close, seqg_var->close_format, seqg_var->chan + 1);
# line 250 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 44/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 251 "../Keithley65xxEM.st"
				seqg_var->previous_chan = seqg_var->chan;
			}
# line 253 "../Keithley65xxEM.st"
			seqg_var->previous_mode = seqg_var->ch_mode_sel;
# line 254 "../Keithley65xxEM.st"
			seqg_var->read_complete = 0;
# line 255 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 40/*read_complete*/, DEFAULT, DEFAULT_TIMEOUT);
# line 256 "../Keithley65xxEM.st"
			seq_efClear(seqg_env, read_complete_mon);
# line 257 "../Keithley65xxEM.st"
			if (seqg_var->ch_mode_sel != seqg_var->previous_mode)
			{
# line 259 "../Keithley65xxEM.st"
				seqg_var->previous_mode = seqg_var->ch_mode_sel;
# line 260 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 37/*dmm_delay_read*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			else
# line 263 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 38/*dmm_read*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 268 "../Keithley65xxEM.st"
			seqg_var->mode = seqg_var->ch_mode[seqg_var->scan_chan];
# line 269 "../Keithley65xxEM.st"
			if (seqg_var->mode != seqg_var->previous_mode)
			{
# line 270 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 30/*dmm_modes*/ + (CH_ID)(seqg_var->mode), DEFAULT, DEFAULT_TIMEOUT);
			}
# line 272 "../Keithley65xxEM.st"
			if (seqg_var->scan_chan != seqg_var->previous_chan)
			{
# line 273 "../Keithley65xxEM.st"
				sprintf(seqg_var->ch_close, seqg_var->close_format, seqg_var->scan_chan + 1);
# line 274 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 44/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 275 "../Keithley65xxEM.st"
				seqg_var->previous_chan = seqg_var->scan_chan;
			}
# line 277 "../Keithley65xxEM.st"
			seqg_var->read_complete = 0;
# line 278 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 40/*read_complete*/, DEFAULT, DEFAULT_TIMEOUT);
# line 279 "../Keithley65xxEM.st"
			seq_efClear(seqg_env, read_complete_mon);
# line 280 "../Keithley65xxEM.st"
			if (seqg_var->mode != seqg_var->previous_mode)
			{
# line 282 "../Keithley65xxEM.st"
				seqg_var->previous_mode = seqg_var->mode;
# line 283 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 37/*dmm_delay_read*/, DEFAULT, DEFAULT_TIMEOUT);
			}
			else
# line 286 "../Keithley65xxEM.st"
				seq_pvPutTmo(seqg_env, 38/*dmm_read*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "single_read_response" in state set "read_meter" ******/

/* Event function for state "single_read_response" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_single_read_response(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 293 "../Keithley65xxEM.st"
	if (seq_efTestAndClear(seqg_env, read_complete_mon) && seqg_var->read_complete)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "single_read_response" in state set "read_meter" */
static void seqg_action_read_meter_1_single_read_response(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 294 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 39/*Dmm_raw*/, DEFAULT, DEFAULT_TIMEOUT);
# line 295 "../Keithley65xxEM.st"
			seqg_var->done_read = 0;
# line 296 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 35/*done_read*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "multi_read_response" in state set "read_meter" ******/

/* Event function for state "multi_read_response" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_multi_read_response(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 300 "../Keithley65xxEM.st"
	if (seq_efTestAndClear(seqg_env, read_complete_mon) && seqg_var->read_complete)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "multi_read_response" in state set "read_meter" */
static void seqg_action_read_meter_1_multi_read_response(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 301 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 20/*ch_raw*/ + (CH_ID)(seqg_var->scan_chan), DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "next_channel" in state set "read_meter" ******/

/* Event function for state "next_channel" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_next_channel(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 305 "../Keithley65xxEM.st"
	if (seqg_var->scan_chan < (seqg_var->channels - 1))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 308 "../Keithley65xxEM.st"
	if (seqg_var->scan_chan >= (seqg_var->channels - 1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "next_channel" in state set "read_meter" */
static void seqg_action_read_meter_1_next_channel(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 306 "../Keithley65xxEM.st"
			seqg_var->scan_chan++;
		}
		return;
	case 1:
		{
# line 309 "../Keithley65xxEM.st"
			seqg_var->scan_chan = 0;
# line 310 "../Keithley65xxEM.st"
			seqg_var->done_read = 0;
# line 311 "../Keithley65xxEM.st"
			seq_pvPutTmo(seqg_env, 35/*done_read*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{P}{Dmm}ch1_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[0]), "ch_mode[0]", P_INT, 1, 6, 1, 1, 0, 0},
	{"{P}{Dmm}ch2_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[1]), "ch_mode[1]", P_INT, 1, 7, 1, 1, 0, 0},
	{"{P}{Dmm}ch3_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[2]), "ch_mode[2]", P_INT, 1, 8, 1, 1, 0, 0},
	{"{P}{Dmm}ch4_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[3]), "ch_mode[3]", P_INT, 1, 9, 1, 1, 0, 0},
	{"{P}{Dmm}ch5_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[4]), "ch_mode[4]", P_INT, 1, 10, 1, 1, 0, 0},
	{"{P}{Dmm}ch6_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[5]), "ch_mode[5]", P_INT, 1, 11, 1, 1, 0, 0},
	{"{P}{Dmm}ch7_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[6]), "ch_mode[6]", P_INT, 1, 12, 1, 1, 0, 0},
	{"{P}{Dmm}ch8_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[7]), "ch_mode[7]", P_INT, 1, 13, 1, 1, 0, 0},
	{"{P}{Dmm}ch9_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[8]), "ch_mode[8]", P_INT, 1, 14, 1, 1, 0, 0},
	{"{P}{Dmm}ch10_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[9]), "ch_mode[9]", P_INT, 1, 15, 1, 1, 0, 0},
	{"{P}{Dmm}Ch1_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[0]), "ch_on_off[0]", P_INT, 1, 16, 0, 1, 0, 0},
	{"{P}{Dmm}Ch2_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[1]), "ch_on_off[1]", P_INT, 1, 17, 0, 1, 0, 0},
	{"{P}{Dmm}Ch3_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[2]), "ch_on_off[2]", P_INT, 1, 18, 0, 1, 0, 0},
	{"{P}{Dmm}Ch4_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[3]), "ch_on_off[3]", P_INT, 1, 19, 0, 1, 0, 0},
	{"{P}{Dmm}Ch5_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[4]), "ch_on_off[4]", P_INT, 1, 20, 0, 1, 0, 0},
	{"{P}{Dmm}Ch6_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[5]), "ch_on_off[5]", P_INT, 1, 21, 0, 1, 0, 0},
	{"{P}{Dmm}Ch7_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[6]), "ch_on_off[6]", P_INT, 1, 22, 0, 1, 0, 0},
	{"{P}{Dmm}Ch8_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[7]), "ch_on_off[7]", P_INT, 1, 23, 0, 1, 0, 0},
	{"{P}{Dmm}Ch9_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[8]), "ch_on_off[8]", P_INT, 1, 24, 0, 1, 0, 0},
	{"{P}{Dmm}Ch10_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[9]), "ch_on_off[9]", P_INT, 1, 25, 0, 1, 0, 0},
	{"{P}{Dmm}Ch1_raw.PROC", offsetof(struct seqg_vars, ch_raw[0]), "ch_raw[0]", P_INT, 1, 26, 0, 0, 0, 0},
	{"{P}{Dmm}Ch2_raw.PROC", offsetof(struct seqg_vars, ch_raw[1]), "ch_raw[1]", P_INT, 1, 27, 0, 0, 0, 0},
	{"{P}{Dmm}Ch3_raw.PROC", offsetof(struct seqg_vars, ch_raw[2]), "ch_raw[2]", P_INT, 1, 28, 0, 0, 0, 0},
	{"{P}{Dmm}Ch4_raw.PROC", offsetof(struct seqg_vars, ch_raw[3]), "ch_raw[3]", P_INT, 1, 29, 0, 0, 0, 0},
	{"{P}{Dmm}Ch5_raw.PROC", offsetof(struct seqg_vars, ch_raw[4]), "ch_raw[4]", P_INT, 1, 30, 0, 0, 0, 0},
	{"{P}{Dmm}Ch6_raw.PROC", offsetof(struct seqg_vars, ch_raw[5]), "ch_raw[5]", P_INT, 1, 31, 0, 0, 0, 0},
	{"{P}{Dmm}Ch7_raw.PROC", offsetof(struct seqg_vars, ch_raw[6]), "ch_raw[6]", P_INT, 1, 32, 0, 0, 0, 0},
	{"{P}{Dmm}Ch8_raw.PROC", offsetof(struct seqg_vars, ch_raw[7]), "ch_raw[7]", P_INT, 1, 33, 0, 0, 0, 0},
	{"{P}{Dmm}Ch9_raw.PROC", offsetof(struct seqg_vars, ch_raw[8]), "ch_raw[8]", P_INT, 1, 34, 0, 0, 0, 0},
	{"{P}{Dmm}Ch10_raw.PROC", offsetof(struct seqg_vars, ch_raw[9]), "ch_raw[9]", P_INT, 1, 35, 0, 0, 0, 0},
	{"{P}{Dmm}conf_dcv.PROC", offsetof(struct seqg_vars, dmm_modes[0]), "dmm_modes[0]", P_INT, 1, 36, 0, 0, 0, 0},
	{"{P}{Dmm}conf_dci.PROC", offsetof(struct seqg_vars, dmm_modes[1]), "dmm_modes[1]", P_INT, 1, 37, 0, 0, 0, 0},
	{"{P}{Dmm}conf_ohm.PROC", offsetof(struct seqg_vars, dmm_modes[2]), "dmm_modes[2]", P_INT, 1, 38, 0, 0, 0, 0},
	{"{P}{Dmm}conf_coul.PROC", offsetof(struct seqg_vars, dmm_modes[3]), "dmm_modes[3]", P_INT, 1, 39, 0, 0, 0, 0},
	{"{P}{Dmm}ch_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode_sel), "ch_mode_sel", P_INT, 1, 40, 2, 1, 0, 0},
	{"{P}{Dmm}done_read.VAL", offsetof(struct seqg_vars, done_read), "done_read", P_INT, 1, 41, 0, 1, 0, 0},
	{"{P}{Dmm}dmm_chan.VAL", offsetof(struct seqg_vars, dmm_chan), "dmm_chan", P_INT, 1, 42, 3, 1, 0, 0},
	{"{P}{Dmm}dmm_delay_read.PROC", offsetof(struct seqg_vars, dmm_delay_read), "dmm_delay_read", P_INT, 1, 43, 0, 0, 0, 0},
	{"{P}{Dmm}dmm_read.PROC", offsetof(struct seqg_vars, dmm_read), "dmm_read", P_INT, 1, 44, 0, 0, 0, 0},
	{"{P}{Dmm}Dmm_raw.PROC", offsetof(struct seqg_vars, Dmm_raw), "Dmm_raw", P_INT, 1, 45, 0, 0, 0, 0},
	{"{P}{Dmm}read_complete.VAL", offsetof(struct seqg_vars, read_complete), "read_complete", P_INT, 1, 46, 4, 1, 0, 0},
	{"{P}{Dmm}single_multi.VAL", offsetof(struct seqg_vars, single_multi), "single_multi", P_INT, 1, 47, 0, 1, 0, 0},
	{"{P}{Dmm}init_dmm.VAL", offsetof(struct seqg_vars, init_dmm), "init_dmm", P_INT, 1, 48, 5, 1, 0, 0},
	{"{P}{Dmm}init_string.PROC", offsetof(struct seqg_vars, do_init), "do_init", P_INT, 1, 49, 0, 0, 0, 0},
	{"{P}{Dmm}ch_close.VAL", offsetof(struct seqg_vars, ch_close), "ch_close", P_STRING, 1, 50, 0, 0, 0, 0},
	{"{P}{Dmm}model.VAL", offsetof(struct seqg_vars, model), "model", P_STRING, 1, 51, 0, 0, 0, 0},
	{"{P}{Dmm}channels.VAL", offsetof(struct seqg_vars, channels), "channels", P_INT, 1, 52, 0, 0, 0, 0},
	{"{P}{Dmm}units.VAL", offsetof(struct seqg_vars, dmm_units), "dmm_units", P_STRING, 1, 53, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ch_units), "ch_units", P_STRING, 1, 54, 0, 0, 0, 0},
};

/* Event masks for state set "mode_change" */
static const seqMask seqg_mask_mode_change_0_init[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_mode_change_0_monitor_mode_changes[] = {
	0x0000002e,
	0x00000000,
};

/* State table for state set "mode_change" */
static seqState seqg_states_mode_change[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_mode_change_0_init,
	/* event function */    seqg_event_mode_change_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_mode_change_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "monitor_mode_changes",
	/* action function */   seqg_action_mode_change_0_monitor_mode_changes,
	/* event function */    seqg_event_mode_change_0_monitor_mode_changes,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_mode_change_0_monitor_mode_changes,
	/* state options */     (0)
	},
};

/* Event masks for state set "read_meter" */
static const seqMask seqg_mask_read_meter_1_init[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_read_meter_1_wait_read[] = {
	0x00000000,
	0x00000200,
};
static const seqMask seqg_mask_read_meter_1_read_channel[] = {
	0x03ff0000,
	0x00008000,
};
static const seqMask seqg_mask_read_meter_1_single_read_response[] = {
	0x00000010,
	0x00004000,
};
static const seqMask seqg_mask_read_meter_1_multi_read_response[] = {
	0x00000010,
	0x00004000,
};
static const seqMask seqg_mask_read_meter_1_next_channel[] = {
	0x00000000,
	0x00100000,
};

/* State table for state set "read_meter" */
static seqState seqg_states_read_meter[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_read_meter_1_init,
	/* event function */    seqg_event_read_meter_1_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_init,
	/* state options */     (0)
	},
	{
	/* state name */        "wait_read",
	/* action function */   seqg_action_read_meter_1_wait_read,
	/* event function */    seqg_event_read_meter_1_wait_read,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_wait_read,
	/* state options */     (0)
	},
	{
	/* state name */        "read_channel",
	/* action function */   seqg_action_read_meter_1_read_channel,
	/* event function */    seqg_event_read_meter_1_read_channel,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_read_channel,
	/* state options */     (0)
	},
	{
	/* state name */        "single_read_response",
	/* action function */   seqg_action_read_meter_1_single_read_response,
	/* event function */    seqg_event_read_meter_1_single_read_response,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_single_read_response,
	/* state options */     (0)
	},
	{
	/* state name */        "multi_read_response",
	/* action function */   seqg_action_read_meter_1_multi_read_response,
	/* event function */    seqg_event_read_meter_1_multi_read_response,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_multi_read_response,
	/* state options */     (0)
	},
	{
	/* state name */        "next_channel",
	/* action function */   seqg_action_read_meter_1_next_channel,
	/* event function */    seqg_event_read_meter_1_next_channel,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_next_channel,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "mode_change",
	/* states */            seqg_states_mode_change,
	/* number of states */  2
	},

	{
	/* state set name */    "read_meter",
	/* states */            seqg_states_read_meter,
	/* number of states */  6
	},
};

/* Program table (global) */
seqProgram Keithley65xxEM = {
	/* magic number */      2002005,
	/* program name */      "Keithley65xxEM",
	/* channels */          seqg_chans,
	/* num. channels */     49,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "P=13LAB:, Dmm=EM1, channels=10, model=6517A",
	/* num. event flags */  5,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void Keithley65xxEMRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&Keithley65xxEM);
}
epicsExportRegistrar(Keithley65xxEMRegistrar);
