/* C code for program Federal, generated by snc from ../Federal.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 14 "../Federal.st"
#include <stdlib.h>
# line 15 "../Federal.st"
#include <stdio.h>
# line 16 "../Federal.st"
#include <string.h>
# line 17 "../Federal.st"
#include <math.h>
# line 18 "../Federal.st"
#include <epicsThread.h>

/* Variable declarations */
# line 20 "../Federal.st"
static	int i;
# line 22 "../Federal.st"
static	int FederalDebug;
# line 26 "../Federal.st"
static	int run;
# line 30 "../Federal.st"
static	int num_probes;
# line 34 "../Federal.st"
static	int probe_num;
# line 37 "../Federal.st"
static	float position;
# line 40 "../Federal.st"
static	int proc;
# line 43 "../Federal.st"
static	string readback;
# line 46 "../Federal.st"
static	double probe_[10];


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
	{
# line 40 "../Federal.st"
	static int seqg_initvar_proc = 1;
	memcpy(&proc, &seqg_initvar_proc, sizeof(seqg_initvar_proc));
	}
}

/****** Code for state "get_readings" in state set "Federal_scan" ******/

/* Event function for state "get_readings" in state set "Federal_scan" */
static seqBool seqg_event_Federal_scan_0_get_readings(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 60 "../Federal.st"
	if (run)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "get_readings" in state set "Federal_scan" */
static void seqg_action_Federal_scan_0_get_readings(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 61 "../Federal.st"
			for (i = 0; i < num_probes; i++)
			{
# line 63 "../Federal.st"
				if (!run)
					break;
# line 64 "../Federal.st"
				seq_pvPutTmo(seqg_env, 5/*proc*/, DEFAULT, DEFAULT_TIMEOUT);
# line 65 "../Federal.st"
				epicsThreadSleep(.33);
# line 66 "../Federal.st"
				seq_pvGetTmo(seqg_env, 6/*readback*/, DEFAULT, DEFAULT_TIMEOUT);
# line 67 "../Federal.st"
				seq_pvGetTmo(seqg_env, 4/*position*/, DEFAULT, DEFAULT_TIMEOUT);
# line 68 "../Federal.st"
				seq_pvGetTmo(seqg_env, 3/*probe_num*/, DEFAULT, DEFAULT_TIMEOUT);
# line 69 "../Federal.st"
				if (FederalDebug)
				{
# line 71 "../Federal.st"
					printf("\nFederal.st:  ascii input: %s\n", readback);
# line 72 "../Federal.st"
					printf("Federal.st:  probe number: %d\n", probe_num);
# line 73 "../Federal.st"
					printf("Federal.st:  position: %3.4f\n", position);
				}
# line 75 "../Federal.st"
				if (probe_num > num_probes)
					break;
# line 76 "../Federal.st"
				probe_num--;
# line 77 "../Federal.st"
				probe_[probe_num] = position;
# line 78 "../Federal.st"
				seq_pvPutTmo(seqg_env, 7/*probe_*/ + (CH_ID)(probe_num), DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

/****** Code for state "wait" in state set "Federal_scan" ******/

/* Event function for state "wait" in state set "Federal_scan" */
static seqBool seqg_event_Federal_scan_0_wait(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 83 "../Federal.st"
	if (seq_delay(seqg_env, 0.5))
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait" in state set "Federal_scan" */
static void seqg_action_Federal_scan_0_wait(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{P}Fed:{S}:debug", (size_t)&FederalDebug, "FederalDebug", P_INT, 1, 1, 0, 1, 0, 0},
	{"{P}Fed:{S}:run", (size_t)&run, "run", P_INT, 1, 2, 0, 1, 0, 0},
	{"{P}Fed:{S}:num_probes", (size_t)&num_probes, "num_probes", P_INT, 1, 3, 0, 1, 0, 0},
	{"{P}Fed:{S}:probe", (size_t)&probe_num, "probe_num", P_INT, 1, 4, 0, 0, 0, 0},
	{"{P}Fed:{S}:position", (size_t)&position, "position", P_FLOAT, 1, 5, 0, 0, 0, 0},
	{"{P}Fed:{S}:serial.PROC", (size_t)&proc, "proc", P_INT, 1, 6, 0, 0, 0, 0},
	{"{P}Fed:{S}:serial.AINP", (size_t)&readback, "readback", P_STRING, 1, 7, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_1", (size_t)&probe_[0], "probe_[0]", P_DOUBLE, 1, 8, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_2", (size_t)&probe_[1], "probe_[1]", P_DOUBLE, 1, 9, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_3", (size_t)&probe_[2], "probe_[2]", P_DOUBLE, 1, 10, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_4", (size_t)&probe_[3], "probe_[3]", P_DOUBLE, 1, 11, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_5", (size_t)&probe_[4], "probe_[4]", P_DOUBLE, 1, 12, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_6", (size_t)&probe_[5], "probe_[5]", P_DOUBLE, 1, 13, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_7", (size_t)&probe_[6], "probe_[6]", P_DOUBLE, 1, 14, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_8", (size_t)&probe_[7], "probe_[7]", P_DOUBLE, 1, 15, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_9", (size_t)&probe_[8], "probe_[8]", P_DOUBLE, 1, 16, 0, 0, 0, 0},
	{"{P}Fed:{S}:probe_10", (size_t)&probe_[9], "probe_[9]", P_DOUBLE, 1, 17, 0, 0, 0, 0},
};

/* Event masks for state set "Federal_scan" */
static const seqMask seqg_mask_Federal_scan_0_get_readings[] = {
	0x00000004,
};
static const seqMask seqg_mask_Federal_scan_0_wait[] = {
	0x00000000,
};

/* State table for state set "Federal_scan" */
static seqState seqg_states_Federal_scan[] = {
	{
	/* state name */        "get_readings",
	/* action function */   seqg_action_Federal_scan_0_get_readings,
	/* event function */    seqg_event_Federal_scan_0_get_readings,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_Federal_scan_0_get_readings,
	/* state options */     (0)
	},
	{
	/* state name */        "wait",
	/* action function */   seqg_action_Federal_scan_0_wait,
	/* event function */    seqg_event_Federal_scan_0_wait,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_Federal_scan_0_wait,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "Federal_scan",
	/* states */            seqg_states_Federal_scan,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram Federal = {
	/* magic number */      2002005,
	/* program name */      "Federal",
	/* channels */          seqg_chans,
	/* num. channels */     17,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void FederalRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&Federal);
}
epicsExportRegistrar(FederalRegistrar);
