/* C code for program Keithley2kDMM_mf40, generated by snc from ../Keithley2kDMM_mf40.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 42 "../Keithley2kDMM_mf40.st"
#include "stdlib.h"
# line 43 "../Keithley2kDMM_mf40.st"
#include "string.h"
# line 94 "../Keithley2kDMM_mf40.st"
static const EF_ID ch_mode_mon = 1;
# line 203 "../Keithley2kDMM_mf40.st"
static const EF_ID ch_mode_sel_mon = 2;
# line 214 "../Keithley2kDMM_mf40.st"
static const EF_ID dmm_chan_mon = 3;
# line 220 "../Keithley2kDMM_mf40.st"
static const EF_ID dmm_chan2_mon = 4;
# line 226 "../Keithley2kDMM_mf40.st"
static const EF_ID dmm_chan3_mon = 5;
# line 232 "../Keithley2kDMM_mf40.st"
static const EF_ID dmm_chan4_mon = 6;
# line 251 "../Keithley2kDMM_mf40.st"
static const EF_ID read_complete_mon = 7;
# line 261 "../Keithley2kDMM_mf40.st"
static const EF_ID init_dmm_mon = 8;

/* Variable declarations */
struct seqg_vars {
# line 45 "../Keithley2kDMM_mf40.st"
	int i;
# line 46 "../Keithley2kDMM_mf40.st"
	int scan_chan;
# line 47 "../Keithley2kDMM_mf40.st"
	int previous_mode;
# line 48 "../Keithley2kDMM_mf40.st"
	int previous_chan;
# line 50 "../Keithley2kDMM_mf40.st"
	int ch_mode[40];
# line 97 "../Keithley2kDMM_mf40.st"
	int ch_on_off[40];
# line 141 "../Keithley2kDMM_mf40.st"
	int ch_raw[40];
# line 187 "../Keithley2kDMM_mf40.st"
	int dmm_modes[10];
# line 200 "../Keithley2kDMM_mf40.st"
	int ch_mode_sel;
# line 207 "../Keithley2kDMM_mf40.st"
	int done_read;
# line 211 "../Keithley2kDMM_mf40.st"
	int dmm_chan;
# line 217 "../Keithley2kDMM_mf40.st"
	int dmm_chan2;
# line 223 "../Keithley2kDMM_mf40.st"
	int dmm_chan3;
# line 229 "../Keithley2kDMM_mf40.st"
	int dmm_chan4;
# line 235 "../Keithley2kDMM_mf40.st"
	int dmm_ch_range;
# line 239 "../Keithley2kDMM_mf40.st"
	int dmm_delay_read;
# line 242 "../Keithley2kDMM_mf40.st"
	int dmm_read;
# line 245 "../Keithley2kDMM_mf40.st"
	int Dmm_raw;
# line 248 "../Keithley2kDMM_mf40.st"
	int read_complete;
# line 254 "../Keithley2kDMM_mf40.st"
	int single_multi;
# line 258 "../Keithley2kDMM_mf40.st"
	int init_dmm;
# line 264 "../Keithley2kDMM_mf40.st"
	int do_init;
# line 267 "../Keithley2kDMM_mf40.st"
	string ch_close;
# line 268 "../Keithley2kDMM_mf40.st"
	string model;
# line 269 "../Keithley2kDMM_mf40.st"
	int channels;
# line 270 "../Keithley2kDMM_mf40.st"
	string dmm_units;
# line 271 "../Keithley2kDMM_mf40.st"
	string ch_units;
# line 273 "../Keithley2kDMM_mf40.st"
	char *unit_strings[10];
# line 274 "../Keithley2kDMM_mf40.st"
	char *P;
# line 275 "../Keithley2kDMM_mf40.st"
	char *Dmm;
# line 276 "../Keithley2kDMM_mf40.st"
	string pvname;
# line 277 "../Keithley2kDMM_mf40.st"
	string close_format;
# line 278 "../Keithley2kDMM_mf40.st"
	int mode;
# line 279 "../Keithley2kDMM_mf40.st"
	int chan;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "mode_change" ******/

/* Event function for state "init" in state set "mode_change" */
static seqBool seqg_event_mode_change_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "mode_change" */
static void seqg_action_mode_change_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 286 "../Keithley2kDMM_mf40.st"
			seq_efSet(seqg_env, ch_mode_mon);
# line 287 "../Keithley2kDMM_mf40.st"
			seq_efSet(seqg_env, ch_mode_sel_mon);
# line 288 "../Keithley2kDMM_mf40.st"
			seq_efSet(seqg_env, dmm_chan_mon);
# line 289 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[0] = "VDC";
# line 290 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[1] = "VAC";
# line 291 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[2] = "OHM";
# line 292 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[3] = "OHM";
# line 293 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[4] = "HZ";
# line 294 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[5] = "DegC";
# line 295 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[6] = "DegC";
# line 296 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[7] = "DegC";
# line 297 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[8] = "ADC";
# line 298 "../Keithley2kDMM_mf40.st"
			seqg_var->unit_strings[9] = "AAC";
# line 299 "../Keithley2kDMM_mf40.st"
			seqg_var->P = seq_macValueGet(seqg_env, "P");
# line 300 "../Keithley2kDMM_mf40.st"
			seqg_var->Dmm = seq_macValueGet(seqg_env, "Dmm");
# line 301 "../Keithley2kDMM_mf40.st"
			strcpy(seqg_var->model, seq_macValueGet(seqg_env, "model"));
# line 302 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 145/*model*/, DEFAULT, DEFAULT_TIMEOUT);
# line 303 "../Keithley2kDMM_mf40.st"
			seqg_var->channels = atoi(seq_macValueGet(seqg_env, "channels"));
# line 304 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 146/*channels*/, DEFAULT, DEFAULT_TIMEOUT);
# line 305 "../Keithley2kDMM_mf40.st"
			if (strcmp(seqg_var->model, "2000") == 0)
			{
# line 306 "../Keithley2kDMM_mf40.st"
				strcpy(seqg_var->close_format, "rout:clos (@%d)");
			}
			else
			{
# line 308 "../Keithley2kDMM_mf40.st"
				strcpy(seqg_var->close_format, "rout:clos (@1%2.2d)");
			}
		}
		return;
	}
}

/****** Code for state "monitor_mode_changes" in state set "mode_change" ******/

/* Event function for state "monitor_mode_changes" in state set "mode_change" */
static seqBool seqg_event_mode_change_0_monitor_mode_changes(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 313 "../Keithley2kDMM_mf40.st"
	if (seq_efTestAndClear(seqg_env, ch_mode_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 337 "../Keithley2kDMM_mf40.st"
	if (seq_efTestAndClear(seqg_env, ch_mode_sel_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 350 "../Keithley2kDMM_mf40.st"
	if (seq_efTestAndClear(seqg_env, dmm_chan_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 356 "../Keithley2kDMM_mf40.st"
	if (seq_efTestAndClear(seqg_env, dmm_chan2_mon) && (seqg_var->channels > 10))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 3;
		return TRUE;
	}
# line 363 "../Keithley2kDMM_mf40.st"
	if (seq_efTestAndClear(seqg_env, dmm_chan3_mon) && (seqg_var->channels > 20))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 4;
		return TRUE;
	}
# line 370 "../Keithley2kDMM_mf40.st"
	if (seq_efTestAndClear(seqg_env, dmm_chan4_mon) && (seqg_var->channels > 30))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 5;
		return TRUE;
	}
# line 376 "../Keithley2kDMM_mf40.st"
	if (seq_efTestAndClear(seqg_env, init_dmm_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 6;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "monitor_mode_changes" in state set "mode_change" */
static void seqg_action_mode_change_0_monitor_mode_changes(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 314 "../Keithley2kDMM_mf40.st"
			for (seqg_var->i = 0; seqg_var->i < seqg_var->channels; seqg_var->i++)
			{
# line 321 "../Keithley2kDMM_mf40.st"
				seqg_var->mode = seqg_var->ch_mode[seqg_var->i];
# line 330 "../Keithley2kDMM_mf40.st"
				sprintf(seqg_var->ch_units, "%s", seqg_var->unit_strings[seqg_var->mode]);
# line 331 "../Keithley2kDMM_mf40.st"
				sprintf(seqg_var->pvname, "%s%sch%d_units.VAL", seqg_var->P, seqg_var->Dmm, seqg_var->i + 1);
# line 332 "../Keithley2kDMM_mf40.st"
				seq_pvAssign(seqg_env, 148/*ch_units*/, seqg_var->pvname);
# line 333 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 148/*ch_units*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	case 1:
		{
# line 338 "../Keithley2kDMM_mf40.st"
			sprintf(seqg_var->dmm_units, "%s", seqg_var->unit_strings[seqg_var->ch_mode_sel]);
# line 339 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 147/*dmm_units*/, DEFAULT, DEFAULT_TIMEOUT);
# line 340 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 120/*dmm_modes*/ + (CH_ID)(seqg_var->ch_mode_sel), DEFAULT, DEFAULT_TIMEOUT);
# line 341 "../Keithley2kDMM_mf40.st"
			seqg_var->previous_mode = seqg_var->ch_mode_sel;
# line 343 "../Keithley2kDMM_mf40.st"
			if (seqg_var->ch_mode_sel == 3)
			{
# line 344 "../Keithley2kDMM_mf40.st"
				sprintf(seqg_var->ch_close, "rout:open:all");
# line 345 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 144/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 346 "../Keithley2kDMM_mf40.st"
				seqg_var->previous_chan = -1;
			}
		}
		return;
	case 2:
		{
# line 351 "../Keithley2kDMM_mf40.st"
			sprintf(seqg_var->ch_close, seqg_var->close_format, seqg_var->dmm_chan + 1);
# line 352 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 144/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 353 "../Keithley2kDMM_mf40.st"
			seqg_var->previous_chan = seqg_var->dmm_chan;
		}
		return;
	case 3:
		{
# line 357 "../Keithley2kDMM_mf40.st"
			sprintf(seqg_var->ch_close, seqg_var->close_format, seqg_var->dmm_chan2 + 11);
# line 358 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 144/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 359 "../Keithley2kDMM_mf40.st"
			seqg_var->previous_chan = seqg_var->dmm_chan2 + 10;
		}
		return;
	case 4:
		{
# line 364 "../Keithley2kDMM_mf40.st"
			sprintf(seqg_var->ch_close, seqg_var->close_format, seqg_var->dmm_chan3 + 21);
# line 365 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 144/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 366 "../Keithley2kDMM_mf40.st"
			seqg_var->previous_chan = seqg_var->dmm_chan3 + 20;
		}
		return;
	case 5:
		{
# line 371 "../Keithley2kDMM_mf40.st"
			sprintf(seqg_var->ch_close, seqg_var->close_format, seqg_var->dmm_chan4 + 31);
# line 372 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 144/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 373 "../Keithley2kDMM_mf40.st"
			seqg_var->previous_chan = seqg_var->dmm_chan4 + 30;
		}
		return;
	case 6:
		{
# line 377 "../Keithley2kDMM_mf40.st"
			if (seqg_var->init_dmm == 1)
			{
# line 378 "../Keithley2kDMM_mf40.st"
				seqg_var->scan_chan = 0;
# line 379 "../Keithley2kDMM_mf40.st"
				seqg_var->previous_mode = -1;
# line 380 "../Keithley2kDMM_mf40.st"
				seqg_var->previous_chan = -1;
# line 381 "../Keithley2kDMM_mf40.st"
				seqg_var->init_dmm = 0;
# line 382 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 142/*init_dmm*/, DEFAULT, DEFAULT_TIMEOUT);
# line 383 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 143/*do_init*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

/****** Code for state "init" in state set "read_meter" ******/

/* Event function for state "init" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "read_meter" */
static void seqg_action_read_meter_1_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 392 "../Keithley2kDMM_mf40.st"
			seqg_var->scan_chan = 0;
# line 393 "../Keithley2kDMM_mf40.st"
			seqg_var->previous_mode = -1;
# line 394 "../Keithley2kDMM_mf40.st"
			seqg_var->previous_chan = -1;
# line 395 "../Keithley2kDMM_mf40.st"
			seq_efClear(seqg_env, read_complete_mon);
# line 396 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 143/*do_init*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "wait_read" in state set "read_meter" ******/

/* Event function for state "wait_read" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_wait_read(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 400 "../Keithley2kDMM_mf40.st"
	if (seqg_var->done_read == 1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait_read" in state set "read_meter" */
static void seqg_action_read_meter_1_wait_read(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "read_channel" in state set "read_meter" ******/

/* Event function for state "read_channel" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_read_channel(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 404 "../Keithley2kDMM_mf40.st"
	if (seqg_var->single_multi == 0)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 427 "../Keithley2kDMM_mf40.st"
	if ((seqg_var->single_multi != 0) && (seqg_var->ch_on_off[seqg_var->scan_chan] == 0))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 458 "../Keithley2kDMM_mf40.st"
	if ((seqg_var->single_multi != 0) && (seqg_var->ch_on_off[seqg_var->scan_chan] != 0))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "read_channel" in state set "read_meter" */
static void seqg_action_read_meter_1_read_channel(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 405 "../Keithley2kDMM_mf40.st"
			if (seqg_var->ch_mode_sel != seqg_var->previous_mode)
			{
# line 406 "../Keithley2kDMM_mf40.st"
				sprintf(seqg_var->dmm_units, "%s", seqg_var->unit_strings[seqg_var->ch_mode_sel]);
# line 407 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 147/*dmm_units*/, DEFAULT, DEFAULT_TIMEOUT);
# line 408 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 120/*dmm_modes*/ + (CH_ID)(seqg_var->ch_mode_sel), DEFAULT, DEFAULT_TIMEOUT);
			}
# line 411 "../Keithley2kDMM_mf40.st"
			seqg_var->chan = seqg_var->dmm_chan;
# line 412 "../Keithley2kDMM_mf40.st"
			if (seqg_var->dmm_ch_range == 1)
# line 412 "../Keithley2kDMM_mf40.st"
				seqg_var->chan = seqg_var->dmm_chan2 + 10;
			else
# line 413 "../Keithley2kDMM_mf40.st"
				if (seqg_var->dmm_ch_range == 2)
# line 413 "../Keithley2kDMM_mf40.st"
					seqg_var->chan = seqg_var->dmm_chan3 + 20;
				else
# line 414 "../Keithley2kDMM_mf40.st"
					if (seqg_var->dmm_ch_range == 3)
# line 414 "../Keithley2kDMM_mf40.st"
						seqg_var->chan = seqg_var->dmm_chan4 + 30;
# line 415 "../Keithley2kDMM_mf40.st"
			if (seqg_var->chan != seqg_var->previous_chan)
			{
# line 416 "../Keithley2kDMM_mf40.st"
				sprintf(seqg_var->ch_close, seqg_var->close_format, seqg_var->chan + 1);
# line 417 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 144/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 418 "../Keithley2kDMM_mf40.st"
				seqg_var->previous_chan = seqg_var->chan;
			}
# line 420 "../Keithley2kDMM_mf40.st"
			seqg_var->previous_mode = seqg_var->ch_mode_sel;
# line 421 "../Keithley2kDMM_mf40.st"
			seqg_var->read_complete = 0;
# line 422 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 140/*read_complete*/, DEFAULT, DEFAULT_TIMEOUT);
# line 423 "../Keithley2kDMM_mf40.st"
			seq_efClear(seqg_env, read_complete_mon);
# line 424 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 138/*dmm_read*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 428 "../Keithley2kDMM_mf40.st"
			seqg_var->mode = seqg_var->ch_mode[seqg_var->scan_chan];
# line 437 "../Keithley2kDMM_mf40.st"
			if (seqg_var->mode != seqg_var->previous_mode)
			{
# line 438 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 120/*dmm_modes*/ + (CH_ID)(seqg_var->mode), DEFAULT, DEFAULT_TIMEOUT);
# line 439 "../Keithley2kDMM_mf40.st"
				seqg_var->previous_mode = seqg_var->mode;
			}
# line 441 "../Keithley2kDMM_mf40.st"
			if (seqg_var->scan_chan != seqg_var->previous_chan)
			{
# line 442 "../Keithley2kDMM_mf40.st"
				sprintf(seqg_var->ch_close, seqg_var->close_format, seqg_var->scan_chan + 1);
# line 443 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 144/*ch_close*/, DEFAULT, DEFAULT_TIMEOUT);
# line 444 "../Keithley2kDMM_mf40.st"
				seqg_var->previous_chan = seqg_var->scan_chan;
			}
# line 446 "../Keithley2kDMM_mf40.st"
			seqg_var->read_complete = 0;
# line 447 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 140/*read_complete*/, DEFAULT, DEFAULT_TIMEOUT);
# line 448 "../Keithley2kDMM_mf40.st"
			seq_efClear(seqg_env, read_complete_mon);
# line 452 "../Keithley2kDMM_mf40.st"
			if (seqg_var->mode == 1)
# line 453 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 137/*dmm_delay_read*/, DEFAULT, DEFAULT_TIMEOUT);
			else
# line 455 "../Keithley2kDMM_mf40.st"
				seq_pvPutTmo(seqg_env, 138/*dmm_read*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 2:
		{
		}
		return;
	}
}

/****** Code for state "single_read_response" in state set "read_meter" ******/

/* Event function for state "single_read_response" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_single_read_response(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 462 "../Keithley2kDMM_mf40.st"
	if (seq_efTestAndClear(seqg_env, read_complete_mon) && seqg_var->read_complete)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "single_read_response" in state set "read_meter" */
static void seqg_action_read_meter_1_single_read_response(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 463 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 139/*Dmm_raw*/, DEFAULT, DEFAULT_TIMEOUT);
# line 464 "../Keithley2kDMM_mf40.st"
			seqg_var->done_read = 0;
# line 465 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 131/*done_read*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "multi_read_response" in state set "read_meter" ******/

/* Event function for state "multi_read_response" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_multi_read_response(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 469 "../Keithley2kDMM_mf40.st"
	if (seq_efTestAndClear(seqg_env, read_complete_mon) && seqg_var->read_complete)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "multi_read_response" in state set "read_meter" */
static void seqg_action_read_meter_1_multi_read_response(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 470 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 80/*ch_raw*/ + (CH_ID)(seqg_var->scan_chan), DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "next_channel" in state set "read_meter" ******/

/* Event function for state "next_channel" in state set "read_meter" */
static seqBool seqg_event_read_meter_1_next_channel(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 474 "../Keithley2kDMM_mf40.st"
	if (seqg_var->scan_chan < (seqg_var->channels - 1))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 477 "../Keithley2kDMM_mf40.st"
	if (seqg_var->scan_chan >= (seqg_var->channels - 1))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "next_channel" in state set "read_meter" */
static void seqg_action_read_meter_1_next_channel(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 475 "../Keithley2kDMM_mf40.st"
			seqg_var->scan_chan++;
		}
		return;
	case 1:
		{
# line 478 "../Keithley2kDMM_mf40.st"
			seqg_var->scan_chan = 0;
# line 479 "../Keithley2kDMM_mf40.st"
			seqg_var->done_read = 0;
# line 480 "../Keithley2kDMM_mf40.st"
			seq_pvPutTmo(seqg_env, 131/*done_read*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{P}{Dmm}ch1_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[0]), "ch_mode[0]", P_INT, 1, 9, 1, 1, 0, 0},
	{"{P}{Dmm}ch2_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[1]), "ch_mode[1]", P_INT, 1, 10, 1, 1, 0, 0},
	{"{P}{Dmm}ch3_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[2]), "ch_mode[2]", P_INT, 1, 11, 1, 1, 0, 0},
	{"{P}{Dmm}ch4_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[3]), "ch_mode[3]", P_INT, 1, 12, 1, 1, 0, 0},
	{"{P}{Dmm}ch5_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[4]), "ch_mode[4]", P_INT, 1, 13, 1, 1, 0, 0},
	{"{P}{Dmm}ch6_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[5]), "ch_mode[5]", P_INT, 1, 14, 1, 1, 0, 0},
	{"{P}{Dmm}ch7_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[6]), "ch_mode[6]", P_INT, 1, 15, 1, 1, 0, 0},
	{"{P}{Dmm}ch8_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[7]), "ch_mode[7]", P_INT, 1, 16, 1, 1, 0, 0},
	{"{P}{Dmm}ch9_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[8]), "ch_mode[8]", P_INT, 1, 17, 1, 1, 0, 0},
	{"{P}{Dmm}ch10_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[9]), "ch_mode[9]", P_INT, 1, 18, 1, 1, 0, 0},
	{"{P}{Dmm}ch11_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[10]), "ch_mode[10]", P_INT, 1, 19, 1, 1, 0, 0},
	{"{P}{Dmm}ch12_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[11]), "ch_mode[11]", P_INT, 1, 20, 1, 1, 0, 0},
	{"{P}{Dmm}ch13_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[12]), "ch_mode[12]", P_INT, 1, 21, 1, 1, 0, 0},
	{"{P}{Dmm}ch14_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[13]), "ch_mode[13]", P_INT, 1, 22, 1, 1, 0, 0},
	{"{P}{Dmm}ch15_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[14]), "ch_mode[14]", P_INT, 1, 23, 1, 1, 0, 0},
	{"{P}{Dmm}ch16_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[15]), "ch_mode[15]", P_INT, 1, 24, 1, 1, 0, 0},
	{"{P}{Dmm}ch17_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[16]), "ch_mode[16]", P_INT, 1, 25, 1, 1, 0, 0},
	{"{P}{Dmm}ch18_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[17]), "ch_mode[17]", P_INT, 1, 26, 1, 1, 0, 0},
	{"{P}{Dmm}ch19_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[18]), "ch_mode[18]", P_INT, 1, 27, 1, 1, 0, 0},
	{"{P}{Dmm}ch20_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[19]), "ch_mode[19]", P_INT, 1, 28, 1, 1, 0, 0},
	{"{P}{Dmm}ch21_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[20]), "ch_mode[20]", P_INT, 1, 29, 1, 1, 0, 0},
	{"{P}{Dmm}ch22_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[21]), "ch_mode[21]", P_INT, 1, 30, 1, 1, 0, 0},
	{"{P}{Dmm}ch23_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[22]), "ch_mode[22]", P_INT, 1, 31, 1, 1, 0, 0},
	{"{P}{Dmm}ch24_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[23]), "ch_mode[23]", P_INT, 1, 32, 1, 1, 0, 0},
	{"{P}{Dmm}ch25_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[24]), "ch_mode[24]", P_INT, 1, 33, 1, 1, 0, 0},
	{"{P}{Dmm}ch26_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[25]), "ch_mode[25]", P_INT, 1, 34, 1, 1, 0, 0},
	{"{P}{Dmm}ch27_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[26]), "ch_mode[26]", P_INT, 1, 35, 1, 1, 0, 0},
	{"{P}{Dmm}ch28_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[27]), "ch_mode[27]", P_INT, 1, 36, 1, 1, 0, 0},
	{"{P}{Dmm}ch29_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[28]), "ch_mode[28]", P_INT, 1, 37, 1, 1, 0, 0},
	{"{P}{Dmm}ch30_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[29]), "ch_mode[29]", P_INT, 1, 38, 1, 1, 0, 0},
	{"{P}{Dmm}ch31_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[30]), "ch_mode[30]", P_INT, 1, 39, 1, 1, 0, 0},
	{"{P}{Dmm}ch32_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[31]), "ch_mode[31]", P_INT, 1, 40, 1, 1, 0, 0},
	{"{P}{Dmm}ch33_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[32]), "ch_mode[32]", P_INT, 1, 41, 1, 1, 0, 0},
	{"{P}{Dmm}ch34_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[33]), "ch_mode[33]", P_INT, 1, 42, 1, 1, 0, 0},
	{"{P}{Dmm}ch35_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[34]), "ch_mode[34]", P_INT, 1, 43, 1, 1, 0, 0},
	{"{P}{Dmm}ch36_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[35]), "ch_mode[35]", P_INT, 1, 44, 1, 1, 0, 0},
	{"{P}{Dmm}ch37_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[36]), "ch_mode[36]", P_INT, 1, 45, 1, 1, 0, 0},
	{"{P}{Dmm}ch38_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[37]), "ch_mode[37]", P_INT, 1, 46, 1, 1, 0, 0},
	{"{P}{Dmm}ch39_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[38]), "ch_mode[38]", P_INT, 1, 47, 1, 1, 0, 0},
	{"{P}{Dmm}ch40_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode[39]), "ch_mode[39]", P_INT, 1, 48, 1, 1, 0, 0},
	{"{P}{Dmm}Ch1_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[0]), "ch_on_off[0]", P_INT, 1, 49, 0, 1, 0, 0},
	{"{P}{Dmm}Ch2_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[1]), "ch_on_off[1]", P_INT, 1, 50, 0, 1, 0, 0},
	{"{P}{Dmm}Ch3_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[2]), "ch_on_off[2]", P_INT, 1, 51, 0, 1, 0, 0},
	{"{P}{Dmm}Ch4_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[3]), "ch_on_off[3]", P_INT, 1, 52, 0, 1, 0, 0},
	{"{P}{Dmm}Ch5_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[4]), "ch_on_off[4]", P_INT, 1, 53, 0, 1, 0, 0},
	{"{P}{Dmm}Ch6_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[5]), "ch_on_off[5]", P_INT, 1, 54, 0, 1, 0, 0},
	{"{P}{Dmm}Ch7_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[6]), "ch_on_off[6]", P_INT, 1, 55, 0, 1, 0, 0},
	{"{P}{Dmm}Ch8_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[7]), "ch_on_off[7]", P_INT, 1, 56, 0, 1, 0, 0},
	{"{P}{Dmm}Ch9_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[8]), "ch_on_off[8]", P_INT, 1, 57, 0, 1, 0, 0},
	{"{P}{Dmm}Ch10_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[9]), "ch_on_off[9]", P_INT, 1, 58, 0, 1, 0, 0},
	{"{P}{Dmm}Ch11_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[10]), "ch_on_off[10]", P_INT, 1, 59, 0, 1, 0, 0},
	{"{P}{Dmm}Ch12_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[11]), "ch_on_off[11]", P_INT, 1, 60, 0, 1, 0, 0},
	{"{P}{Dmm}Ch13_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[12]), "ch_on_off[12]", P_INT, 1, 61, 0, 1, 0, 0},
	{"{P}{Dmm}Ch14_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[13]), "ch_on_off[13]", P_INT, 1, 62, 0, 1, 0, 0},
	{"{P}{Dmm}Ch15_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[14]), "ch_on_off[14]", P_INT, 1, 63, 0, 1, 0, 0},
	{"{P}{Dmm}Ch16_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[15]), "ch_on_off[15]", P_INT, 1, 64, 0, 1, 0, 0},
	{"{P}{Dmm}Ch17_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[16]), "ch_on_off[16]", P_INT, 1, 65, 0, 1, 0, 0},
	{"{P}{Dmm}Ch18_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[17]), "ch_on_off[17]", P_INT, 1, 66, 0, 1, 0, 0},
	{"{P}{Dmm}Ch19_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[18]), "ch_on_off[18]", P_INT, 1, 67, 0, 1, 0, 0},
	{"{P}{Dmm}Ch20_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[19]), "ch_on_off[19]", P_INT, 1, 68, 0, 1, 0, 0},
	{"{P}{Dmm}Ch21_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[20]), "ch_on_off[20]", P_INT, 1, 69, 0, 1, 0, 0},
	{"{P}{Dmm}Ch22_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[21]), "ch_on_off[21]", P_INT, 1, 70, 0, 1, 0, 0},
	{"{P}{Dmm}Ch23_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[22]), "ch_on_off[22]", P_INT, 1, 71, 0, 1, 0, 0},
	{"{P}{Dmm}Ch24_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[23]), "ch_on_off[23]", P_INT, 1, 72, 0, 1, 0, 0},
	{"{P}{Dmm}Ch25_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[24]), "ch_on_off[24]", P_INT, 1, 73, 0, 1, 0, 0},
	{"{P}{Dmm}Ch26_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[25]), "ch_on_off[25]", P_INT, 1, 74, 0, 1, 0, 0},
	{"{P}{Dmm}Ch27_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[26]), "ch_on_off[26]", P_INT, 1, 75, 0, 1, 0, 0},
	{"{P}{Dmm}Ch28_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[27]), "ch_on_off[27]", P_INT, 1, 76, 0, 1, 0, 0},
	{"{P}{Dmm}Ch29_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[28]), "ch_on_off[28]", P_INT, 1, 77, 0, 1, 0, 0},
	{"{P}{Dmm}Ch30_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[29]), "ch_on_off[29]", P_INT, 1, 78, 0, 1, 0, 0},
	{"{P}{Dmm}Ch31_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[30]), "ch_on_off[30]", P_INT, 1, 79, 0, 1, 0, 0},
	{"{P}{Dmm}Ch32_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[31]), "ch_on_off[31]", P_INT, 1, 80, 0, 1, 0, 0},
	{"{P}{Dmm}Ch33_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[32]), "ch_on_off[32]", P_INT, 1, 81, 0, 1, 0, 0},
	{"{P}{Dmm}Ch34_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[33]), "ch_on_off[33]", P_INT, 1, 82, 0, 1, 0, 0},
	{"{P}{Dmm}Ch35_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[34]), "ch_on_off[34]", P_INT, 1, 83, 0, 1, 0, 0},
	{"{P}{Dmm}Ch36_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[35]), "ch_on_off[35]", P_INT, 1, 84, 0, 1, 0, 0},
	{"{P}{Dmm}Ch37_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[36]), "ch_on_off[36]", P_INT, 1, 85, 0, 1, 0, 0},
	{"{P}{Dmm}Ch38_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[37]), "ch_on_off[37]", P_INT, 1, 86, 0, 1, 0, 0},
	{"{P}{Dmm}Ch39_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[38]), "ch_on_off[38]", P_INT, 1, 87, 0, 1, 0, 0},
	{"{P}{Dmm}Ch40_on_off.VAL", offsetof(struct seqg_vars, ch_on_off[39]), "ch_on_off[39]", P_INT, 1, 88, 0, 1, 0, 0},
	{"{P}{Dmm}Ch1_raw.PROC", offsetof(struct seqg_vars, ch_raw[0]), "ch_raw[0]", P_INT, 1, 89, 0, 0, 0, 0},
	{"{P}{Dmm}Ch2_raw.PROC", offsetof(struct seqg_vars, ch_raw[1]), "ch_raw[1]", P_INT, 1, 90, 0, 0, 0, 0},
	{"{P}{Dmm}Ch3_raw.PROC", offsetof(struct seqg_vars, ch_raw[2]), "ch_raw[2]", P_INT, 1, 91, 0, 0, 0, 0},
	{"{P}{Dmm}Ch4_raw.PROC", offsetof(struct seqg_vars, ch_raw[3]), "ch_raw[3]", P_INT, 1, 92, 0, 0, 0, 0},
	{"{P}{Dmm}Ch5_raw.PROC", offsetof(struct seqg_vars, ch_raw[4]), "ch_raw[4]", P_INT, 1, 93, 0, 0, 0, 0},
	{"{P}{Dmm}Ch6_raw.PROC", offsetof(struct seqg_vars, ch_raw[5]), "ch_raw[5]", P_INT, 1, 94, 0, 0, 0, 0},
	{"{P}{Dmm}Ch7_raw.PROC", offsetof(struct seqg_vars, ch_raw[6]), "ch_raw[6]", P_INT, 1, 95, 0, 0, 0, 0},
	{"{P}{Dmm}Ch8_raw.PROC", offsetof(struct seqg_vars, ch_raw[7]), "ch_raw[7]", P_INT, 1, 96, 0, 0, 0, 0},
	{"{P}{Dmm}Ch9_raw.PROC", offsetof(struct seqg_vars, ch_raw[8]), "ch_raw[8]", P_INT, 1, 97, 0, 0, 0, 0},
	{"{P}{Dmm}Ch10_raw.PROC", offsetof(struct seqg_vars, ch_raw[9]), "ch_raw[9]", P_INT, 1, 98, 0, 0, 0, 0},
	{"{P}{Dmm}Ch11_raw.PROC", offsetof(struct seqg_vars, ch_raw[10]), "ch_raw[10]", P_INT, 1, 99, 0, 0, 0, 0},
	{"{P}{Dmm}Ch12_raw.PROC", offsetof(struct seqg_vars, ch_raw[11]), "ch_raw[11]", P_INT, 1, 100, 0, 0, 0, 0},
	{"{P}{Dmm}Ch13_raw.PROC", offsetof(struct seqg_vars, ch_raw[12]), "ch_raw[12]", P_INT, 1, 101, 0, 0, 0, 0},
	{"{P}{Dmm}Ch14_raw.PROC", offsetof(struct seqg_vars, ch_raw[13]), "ch_raw[13]", P_INT, 1, 102, 0, 0, 0, 0},
	{"{P}{Dmm}Ch15_raw.PROC", offsetof(struct seqg_vars, ch_raw[14]), "ch_raw[14]", P_INT, 1, 103, 0, 0, 0, 0},
	{"{P}{Dmm}Ch16_raw.PROC", offsetof(struct seqg_vars, ch_raw[15]), "ch_raw[15]", P_INT, 1, 104, 0, 0, 0, 0},
	{"{P}{Dmm}Ch17_raw.PROC", offsetof(struct seqg_vars, ch_raw[16]), "ch_raw[16]", P_INT, 1, 105, 0, 0, 0, 0},
	{"{P}{Dmm}Ch18_raw.PROC", offsetof(struct seqg_vars, ch_raw[17]), "ch_raw[17]", P_INT, 1, 106, 0, 0, 0, 0},
	{"{P}{Dmm}Ch19_raw.PROC", offsetof(struct seqg_vars, ch_raw[18]), "ch_raw[18]", P_INT, 1, 107, 0, 0, 0, 0},
	{"{P}{Dmm}Ch20_raw.PROC", offsetof(struct seqg_vars, ch_raw[19]), "ch_raw[19]", P_INT, 1, 108, 0, 0, 0, 0},
	{"{P}{Dmm}Ch21_raw.PROC", offsetof(struct seqg_vars, ch_raw[20]), "ch_raw[20]", P_INT, 1, 109, 0, 0, 0, 0},
	{"{P}{Dmm}Ch22_raw.PROC", offsetof(struct seqg_vars, ch_raw[21]), "ch_raw[21]", P_INT, 1, 110, 0, 0, 0, 0},
	{"{P}{Dmm}Ch23_raw.PROC", offsetof(struct seqg_vars, ch_raw[22]), "ch_raw[22]", P_INT, 1, 111, 0, 0, 0, 0},
	{"{P}{Dmm}Ch24_raw.PROC", offsetof(struct seqg_vars, ch_raw[23]), "ch_raw[23]", P_INT, 1, 112, 0, 0, 0, 0},
	{"{P}{Dmm}Ch25_raw.PROC", offsetof(struct seqg_vars, ch_raw[24]), "ch_raw[24]", P_INT, 1, 113, 0, 0, 0, 0},
	{"{P}{Dmm}Ch26_raw.PROC", offsetof(struct seqg_vars, ch_raw[25]), "ch_raw[25]", P_INT, 1, 114, 0, 0, 0, 0},
	{"{P}{Dmm}Ch27_raw.PROC", offsetof(struct seqg_vars, ch_raw[26]), "ch_raw[26]", P_INT, 1, 115, 0, 0, 0, 0},
	{"{P}{Dmm}Ch28_raw.PROC", offsetof(struct seqg_vars, ch_raw[27]), "ch_raw[27]", P_INT, 1, 116, 0, 0, 0, 0},
	{"{P}{Dmm}Ch29_raw.PROC", offsetof(struct seqg_vars, ch_raw[28]), "ch_raw[28]", P_INT, 1, 117, 0, 0, 0, 0},
	{"{P}{Dmm}Ch30_raw.PROC", offsetof(struct seqg_vars, ch_raw[29]), "ch_raw[29]", P_INT, 1, 118, 0, 0, 0, 0},
	{"{P}{Dmm}Ch31_raw.PROC", offsetof(struct seqg_vars, ch_raw[30]), "ch_raw[30]", P_INT, 1, 119, 0, 0, 0, 0},
	{"{P}{Dmm}Ch32_raw.PROC", offsetof(struct seqg_vars, ch_raw[31]), "ch_raw[31]", P_INT, 1, 120, 0, 0, 0, 0},
	{"{P}{Dmm}Ch33_raw.PROC", offsetof(struct seqg_vars, ch_raw[32]), "ch_raw[32]", P_INT, 1, 121, 0, 0, 0, 0},
	{"{P}{Dmm}Ch34_raw.PROC", offsetof(struct seqg_vars, ch_raw[33]), "ch_raw[33]", P_INT, 1, 122, 0, 0, 0, 0},
	{"{P}{Dmm}Ch35_raw.PROC", offsetof(struct seqg_vars, ch_raw[34]), "ch_raw[34]", P_INT, 1, 123, 0, 0, 0, 0},
	{"{P}{Dmm}Ch36_raw.PROC", offsetof(struct seqg_vars, ch_raw[35]), "ch_raw[35]", P_INT, 1, 124, 0, 0, 0, 0},
	{"{P}{Dmm}Ch37_raw.PROC", offsetof(struct seqg_vars, ch_raw[36]), "ch_raw[36]", P_INT, 1, 125, 0, 0, 0, 0},
	{"{P}{Dmm}Ch38_raw.PROC", offsetof(struct seqg_vars, ch_raw[37]), "ch_raw[37]", P_INT, 1, 126, 0, 0, 0, 0},
	{"{P}{Dmm}Ch39_raw.PROC", offsetof(struct seqg_vars, ch_raw[38]), "ch_raw[38]", P_INT, 1, 127, 0, 0, 0, 0},
	{"{P}{Dmm}Ch40_raw.PROC", offsetof(struct seqg_vars, ch_raw[39]), "ch_raw[39]", P_INT, 1, 128, 0, 0, 0, 0},
	{"{P}{Dmm}conf_dcv.PROC", offsetof(struct seqg_vars, dmm_modes[0]), "dmm_modes[0]", P_INT, 1, 129, 0, 0, 0, 0},
	{"{P}{Dmm}conf_acv.PROC", offsetof(struct seqg_vars, dmm_modes[1]), "dmm_modes[1]", P_INT, 1, 130, 0, 0, 0, 0},
	{"{P}{Dmm}conf_ohm2w.PROC", offsetof(struct seqg_vars, dmm_modes[2]), "dmm_modes[2]", P_INT, 1, 131, 0, 0, 0, 0},
	{"{P}{Dmm}conf_ohm4w.PROC", offsetof(struct seqg_vars, dmm_modes[3]), "dmm_modes[3]", P_INT, 1, 132, 0, 0, 0, 0},
	{"{P}{Dmm}conf_freq.PROC", offsetof(struct seqg_vars, dmm_modes[4]), "dmm_modes[4]", P_INT, 1, 133, 0, 0, 0, 0},
	{"{P}{Dmm}conf_tempj.PROC", offsetof(struct seqg_vars, dmm_modes[5]), "dmm_modes[5]", P_INT, 1, 134, 0, 0, 0, 0},
	{"{P}{Dmm}conf_tempk.PROC", offsetof(struct seqg_vars, dmm_modes[6]), "dmm_modes[6]", P_INT, 1, 135, 0, 0, 0, 0},
	{"{P}{Dmm}conf_tempt.PROC", offsetof(struct seqg_vars, dmm_modes[7]), "dmm_modes[7]", P_INT, 1, 136, 0, 0, 0, 0},
	{"{P}{Dmm}conf_dci.PROC", offsetof(struct seqg_vars, dmm_modes[8]), "dmm_modes[8]", P_INT, 1, 137, 0, 0, 0, 0},
	{"{P}{Dmm}conf_aci.PROC", offsetof(struct seqg_vars, dmm_modes[9]), "dmm_modes[9]", P_INT, 1, 138, 0, 0, 0, 0},
	{"{P}{Dmm}ch_mode_sel.VAL", offsetof(struct seqg_vars, ch_mode_sel), "ch_mode_sel", P_INT, 1, 139, 2, 1, 0, 0},
	{"{P}{Dmm}done_read.VAL", offsetof(struct seqg_vars, done_read), "done_read", P_INT, 1, 140, 0, 1, 0, 0},
	{"{P}{Dmm}dmm_chan.VAL", offsetof(struct seqg_vars, dmm_chan), "dmm_chan", P_INT, 1, 141, 3, 1, 0, 0},
	{"{P}{Dmm}dmm_chan2.VAL", offsetof(struct seqg_vars, dmm_chan2), "dmm_chan2", P_INT, 1, 142, 4, 1, 0, 0},
	{"{P}{Dmm}dmm_chan3.VAL", offsetof(struct seqg_vars, dmm_chan3), "dmm_chan3", P_INT, 1, 143, 5, 1, 0, 0},
	{"{P}{Dmm}dmm_chan4.VAL", offsetof(struct seqg_vars, dmm_chan4), "dmm_chan4", P_INT, 1, 144, 6, 1, 0, 0},
	{"{P}{Dmm}dmm_ch_range.VAL", offsetof(struct seqg_vars, dmm_ch_range), "dmm_ch_range", P_INT, 1, 145, 0, 1, 0, 0},
	{"{P}{Dmm}dmm_delay_read.PROC", offsetof(struct seqg_vars, dmm_delay_read), "dmm_delay_read", P_INT, 1, 146, 0, 0, 0, 0},
	{"{P}{Dmm}dmm_read.PROC", offsetof(struct seqg_vars, dmm_read), "dmm_read", P_INT, 1, 147, 0, 0, 0, 0},
	{"{P}{Dmm}Dmm_raw.PROC", offsetof(struct seqg_vars, Dmm_raw), "Dmm_raw", P_INT, 1, 148, 0, 0, 0, 0},
	{"{P}{Dmm}read_complete.VAL", offsetof(struct seqg_vars, read_complete), "read_complete", P_INT, 1, 149, 7, 1, 0, 0},
	{"{P}{Dmm}single_multi.VAL", offsetof(struct seqg_vars, single_multi), "single_multi", P_INT, 1, 150, 0, 1, 0, 0},
	{"{P}{Dmm}init_dmm.VAL", offsetof(struct seqg_vars, init_dmm), "init_dmm", P_INT, 1, 151, 8, 1, 0, 0},
	{"{P}{Dmm}init_string.PROC", offsetof(struct seqg_vars, do_init), "do_init", P_INT, 1, 152, 0, 0, 0, 0},
	{"{P}{Dmm}ch_close.VAL", offsetof(struct seqg_vars, ch_close), "ch_close", P_STRING, 1, 153, 0, 0, 0, 0},
	{"{P}{Dmm}model.VAL", offsetof(struct seqg_vars, model), "model", P_STRING, 1, 154, 0, 0, 0, 0},
	{"{P}{Dmm}channels.VAL", offsetof(struct seqg_vars, channels), "channels", P_INT, 1, 155, 0, 0, 0, 0},
	{"{P}{Dmm}units.VAL", offsetof(struct seqg_vars, dmm_units), "dmm_units", P_STRING, 1, 156, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ch_units), "ch_units", P_STRING, 1, 157, 0, 0, 0, 0},
};

/* Event masks for state set "mode_change" */
static const seqMask seqg_mask_mode_change_0_init[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_mode_change_0_monitor_mode_changes[] = {
	0x0000017e,
	0x00000000,
	0x00000000,
	0x00000000,
	0x08000000,
};

/* State table for state set "mode_change" */
static seqState seqg_states_mode_change[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_mode_change_0_init,
	/* event function */    seqg_event_mode_change_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_mode_change_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "monitor_mode_changes",
	/* action function */   seqg_action_mode_change_0_monitor_mode_changes,
	/* event function */    seqg_event_mode_change_0_monitor_mode_changes,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_mode_change_0_monitor_mode_changes,
	/* state options */     (0)
	},
};

/* Event masks for state set "read_meter" */
static const seqMask seqg_mask_read_meter_1_init[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_read_meter_1_wait_read[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00001000,
};
static const seqMask seqg_mask_read_meter_1_read_channel[] = {
	0x00000000,
	0xfffe0000,
	0x01ffffff,
	0x00000000,
	0x00400000,
};
static const seqMask seqg_mask_read_meter_1_single_read_response[] = {
	0x00000080,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00200000,
};
static const seqMask seqg_mask_read_meter_1_multi_read_response[] = {
	0x00000080,
	0x00000000,
	0x00000000,
	0x00000000,
	0x00200000,
};
static const seqMask seqg_mask_read_meter_1_next_channel[] = {
	0x00000000,
	0x00000000,
	0x00000000,
	0x00000000,
	0x08000000,
};

/* State table for state set "read_meter" */
static seqState seqg_states_read_meter[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_read_meter_1_init,
	/* event function */    seqg_event_read_meter_1_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_init,
	/* state options */     (0)
	},
	{
	/* state name */        "wait_read",
	/* action function */   seqg_action_read_meter_1_wait_read,
	/* event function */    seqg_event_read_meter_1_wait_read,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_wait_read,
	/* state options */     (0)
	},
	{
	/* state name */        "read_channel",
	/* action function */   seqg_action_read_meter_1_read_channel,
	/* event function */    seqg_event_read_meter_1_read_channel,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_read_channel,
	/* state options */     (0)
	},
	{
	/* state name */        "single_read_response",
	/* action function */   seqg_action_read_meter_1_single_read_response,
	/* event function */    seqg_event_read_meter_1_single_read_response,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_single_read_response,
	/* state options */     (0)
	},
	{
	/* state name */        "multi_read_response",
	/* action function */   seqg_action_read_meter_1_multi_read_response,
	/* event function */    seqg_event_read_meter_1_multi_read_response,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_multi_read_response,
	/* state options */     (0)
	},
	{
	/* state name */        "next_channel",
	/* action function */   seqg_action_read_meter_1_next_channel,
	/* event function */    seqg_event_read_meter_1_next_channel,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_read_meter_1_next_channel,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "mode_change",
	/* states */            seqg_states_mode_change,
	/* number of states */  2
	},

	{
	/* state set name */    "read_meter",
	/* states */            seqg_states_read_meter,
	/* number of states */  6
	},
};

/* Program table (global) */
seqProgram Keithley2kDMM_mf40 = {
	/* magic number */      2002005,
	/* program name */      "Keithley2kDMM_mf40",
	/* channels */          seqg_chans,
	/* num. channels */     149,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "P=13LAB:, Dmm=DMM1, channels=40, model=2700",
	/* num. event flags */  8,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void Keithley2kDMM_mf40Registrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&Keithley2kDMM_mf40);
}
epicsExportRegistrar(Keithley2kDMM_mf40Registrar);
